### ISSUE TITLE
strapi sql connection throws ER_TOO_LONG_KEY: Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by Taekondainc** [strapi/strapi#10248]
- Node.js version: Node LTS version (v12 / v14) 
- NPM version:6.14.11
- Strapi version: 
- Database: msql (wamp)
- Operating system:windows

### Additional context
 so i was creating a new project which i want to use sql and the it returned  ER_TOO_LONG_KEY: Specified key was too long; max key length is 1000 bytes when i ran npm run develop. i have the latest version of wamp. need help solving this issue.

**Comment by Taekondainc** [comment]
also the weirdest thing happens , when i change email from null on the schema the error shows but it runs. maybe somone can shed some light on this

**Comment by derrickmehaffy** [comment]
Related: https://github.com/strapi/strapi/issues/7273

**Comment by derrickmehaffy** [comment]
@Taekondainc can you please link to your code (if it's public) or create a reproduction repo and link to that?

**Comment by Taekondainc** [comment]
cool i will upload

**Comment by kelvindimson** [comment]
Was this issue ever resolve?

**Comment by giorgionetg** [comment]
I've got same error in ubuntu and mariadb...

**Comment by Taekondainc** [comment]
run project only when server fully running

**Comment by derrickmehaffy** [comment]
Issue has not been "fixed" per say, but there is a work-around to set the collection name to a shorter one in the model settings file:

We plan to address the issue in v4

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed

**Comment by nilsmich** [comment]
Hi
The issue seems to still exist for me. It appears whenever I try to add a field of the type uid. 
Here is the error message:  
"error: alter table `collection_name` add unique `collection_name_test_unique`(`test`) - ER_TOO_LONG_KEY: Specified key was too long; max key length is 1000 bytes"


Node.js version: 14.17.0
NPM version:7.19.0
Strapi version: 4.0.2
Database: msql
Operating system: windows

The error occurs on a fresh installed Strapi installation with an empty DB.

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.

**Comment by kskrlinnorth2** [comment]
Database storage engine (or at least this table) must be InnoDB, not MyISAM, to support this key length.

**Comment by Ahmadnurahsan** [comment]
![image](https://github.com/strapi/strapi/assets/72061385/78281f62-51fe-4504-915a-18e9d601ed8d)
still returned ER_TOO_LONG_KEY: Specified key was too long; max key length is 1000 bytes when i ran npm run develop. i have the latest version of wamp. need help solving this issue.

**Comment by g00seberry** [comment]
ваша шляпа не работает 

[Error: EPERM: operation not permitted, unlink 'C:\Users\DATTEB~1\AppData\Local\Temp\strapi-upload-qO4WRv\optimized-daviddoe_strapi_8c8f2047f9'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\DATTEB~1\\AppData\\Local\\Temp\\strapi-upload-qO4WRv\\optimized-daviddoe_strapi_8c8f2047f9'
}

**Comment by derrickmehaffy** [comment]
> ![image](https://github.com/strapi/strapi/assets/72061385/78281f62-51fe-4504-915a-18e9d601ed8d)
> still returned ER_TOO_LONG_KEY: Specified key was too long; max key length is 1000 bytes when i ran npm run develop. i have the latest version of wamp. need help solving this issue.
> ![image](https://github.com/strapi/strapi/assets/72061385/d1384a6d-ef30-4578-814a-1e4801668dbb)
> 
> 
> ![image](https://github.com/strapi/strapi/assets/72061385/5665c6e0-b30c-4270-8b56-927e1b30819a)
> ![image](https://github.com/strapi/strapi/assets/72061385/2ccd8b80-c356-4ad1-9a08-539b4e265dcf)
> 

Entirely different issue, what you mentioned are naming lengths, not data lengths.
