### ISSUE TITLE
Editing content-types in MySQL throws errors due to timestamps

### ISSUE THREAD

**Issue by piere129** [strapi/strapi#1119]
**Informations**
- **Node.js version**: 9.9.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha-12.1.2
- **Database**: MySQL
- **Operating system**: Windows

**What is the current behavior?**

Updating a content-type with timestamps returns the following error in MySQL:
` error update 'tests' set 'id' = 2, 'teststring' = 'test2', 'created_at' = '2018-05-03T13:11:33.000Z', 'updated_at' = '2018-05-03T13:11:33.000Z', 'link' = 1 where 'id' = 2 - ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2018-05-03T13:11:33.000Z' for column 'created_at' at row 1
`

I also tried setting the timestamps value in the content-type model (at api/"content-type_name"/models/"content-type_name".settings.json) to false but timestamps are still getting generated when creating a new object of this content-type

**Steps to reproduce the problem**

1) create content-type with timestamps enabled
2) try to edit a field of the content-type
3) save
4) error gets thrown that created_at has the wrong value and is incorrect 

**What is the expected behavior?**

updated_at field should get updated. 

**Suggested solutions**

Fix the formatting of the datetime, as i assume that's where the problem occurs. At creation of the content-type datetime throws no errors. It's only when updating this updated_at value that problems occur.

- [ x ] I'm sure that this issue hasn't already been referenced

**Comment by piere129** [comment]
Setting the timestamps option to false fixed my issue, but it seems like this shouldn't happen. I currently can't seem to find where the error occurs..

**Comment by lauriejim** [comment]
Can you give me the column type you have in your database please.

**Comment by piere129** [comment]
@lauriejim both created_at as updated_at are datatype: timestamp

**Comment by lauriejim** [comment]
I try to add and update data with MySQL database and it works without errors.

![9idd6wvt1x-3000x3000](https://user-images.githubusercontent.com/5716596/39747541-dd1066ee-52ad-11e8-8cca-3a8256e30620.png)

Just have an issue on update, the time zone is different than create.

**Comment by derrickmehaffy** [comment]
@piere129 and @lauriejim just curious, in your testing which version of MySQL are you both using? I believe, though I could be wrong, that in MySQL 5.5 and below you could only have one CURRENT_TIMESTAMP. This was fixed in MySQL 5.6+ and MariaDB 10.0+

**Comment by lauriejim** [comment]
Using `5.6.38` for MySQL. So you have to update your MySQL please.

**Comment by derrickmehaffy** [comment]
@lauriejim this issue still exists above mysql 5.5. I just had it happen running MariaDB 10.0+ where trying to remove a relation causes an issue with trying to update the created_at (which by the way shouldn't be updated when a record is updated, that should remain static)

**Comment by piere129** [comment]
@lauriejim I also still have the issue. I'm currently at MySQL Server 5.7.22 and the error still persists

**Comment by derrickmehaffy** [comment]
@piere129 I messaged Jim on the Slack to ask if it can be re-opened

**Comment by lauriejim** [comment]
Can you guys @piere129  and @derrickmehaffy find a way to fix it please. It will help us a lot :) 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by derrickmehaffy** [comment]
@lauriejim can you provide some context as to how strapi generates the date time? 

IE how does strapi get this value: `2018-05-03T13:11:33.000Z`

**Comment by derrickmehaffy** [comment]
@Aurelsicoko maybe you can also help provide some info on how the above is generated ^

**Comment by derrickmehaffy** [comment]
Alright I think I found part of the issue:

```
                          case 'timestampUpdate':
                            type = definition.client === 'pg' ? 'timestamp with time zone' : 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP';
```

Mysql/Mariadb don't accept the time zone in the `timestamp` field

**Comment by derrickmehaffy** [comment]
As I stated in the related issue the issue is with the adminUI and how moment.js is formatting the timestamps:

> It seems the following two files have an improperly formatted moment.js datetime its trying to push to the database:
> 
> https://github.com/strapi/strapi/blob/88a3da813274e1140db9b3b410098d445de2c54d/packages/strapi-plugin-content-manager/admin/src/containers/EditPage/index.js#L189-L196
> 
> https://github.com/strapi/strapi/blob/88a3da813274e1140db9b3b410098d445de2c54d/packages/strapi-plugin-content-type-builder/admin/src/containers/Form/index.js#L384-L401

**Comment by derrickmehaffy** [comment]
@soupette when you get a moment can you explain how these tie into the adminUI and how we could change the format? All my attempts to modify this have resulted in the adminUI not loading after building

**Comment by derrickmehaffy** [comment]
Doing some testing, then we can prob close this @lauriejim it should be related to this PR: https://github.com/strapi/strapi/pull/1187

**Comment by derrickmehaffy** [comment]
@piere129 if you want to test the latest changes too that would be great.

**Comment by peder1001** [comment]
I too would like to test the changes. Had the same issue

**Comment by derrickmehaffy** [comment]
It is working as intended however after cloning the Strapi Master branch:

- run `npm run setup:build` in the repo folder
- create a new project with --dev (important) 
- run `npm install` in the project folder
- Start and test

No more datetime errors appear and only `updatedAt` is actually updated on changes. Note if you don't start with --dev the changes in the PR are not applied.

Nice job @soupette 
@lauriejim we should be able to close this issue as well, but leave it open to reply on in case there are further issues

**Comment by lauriejim** [comment]
We will link further issue to this one and class it as duplicate.
Thank you for the update @derrickmehaffy

**Comment by derrickmehaffy** [comment]
@toshkoevoets there should be a migration guide from 12.1.3 to 12.2 (sorry on mobile at the moment) but these issues are resolved in the latest update. It can be quite difficult right now, mainly due to Strapi being in alpha, it isn't quite 100% ready for real production use.

**Comment by lauriejim** [comment]
@ToshKoevoets You will have to manually update (with a script) all your data.

**Comment by mstapp** [comment]
I'm still getting this error in v3.0.0-alpha.13.0.1 & mysql 5.7.

- Using strapi docker image for v3.0.0-alpha.13.0.1.
- Mysql 5.7 (docker image)
- OS X 10.13.6 (High Sierra)

I have a simple Content Type with a date field called "pubdate" (mysql type "timestamp", default CURRENT_TIMESTAMP). If I add a new record using the admin UI and I leave the pubdate field blank, then I can save the record successfully & it gets the default current timestamp. But if I use the admin UI's date & time picker to specify a date & time, then I can't save & get an error message saying that I'm trying to add a date in the wrong format.

**Comment by lauriejim** [comment]
Here has already been re-created https://github.com/strapi/strapi/issues/1579
