### ISSUE TITLE
[v4] Various WYSIWYG "paper cut" issues

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#11510]
### Describe the bug

While testing the latest beta (11) and checking on all existing features in the current WYSIWYG I noticed the following issues:

- Selecting multiple lines and trying to set either the unordered and ordered lists, only the first entry is prefixed by it's list option
- Selecting a line and trying to set ordered list will always give you `1. ` and not continue the ordered list (only way to do it is to press enter after the first entry)
- Underline is using the HTML code instead of standard markdown
- Underline, Strikethrough, and code block all have an odd red color to them, like the syntax isn't correct
- Pressing enter after a link gives some really odd index level on the next line
- Maximized window has it's scroll bars offset in a really weird way and doesn't get very big
- Impossible to put proper spacing around code blocks

### Steps to reproduce the behavior

Various, recommend just playing around in the WYSIWYG

### Expected behavior

None of the above should happen :stuck_out_tongue: 

### Screenshots

![image](https://user-images.githubusercontent.com/8593673/140850931-0dadb11b-48af-4bad-a331-dfdf42daafe4.png)
https://www.loom.com/share/66bf78e886b34057af1d5d666b097089

### Code snippets

N/A

### System

- Node.js version: v14.17.5
- NPM version: v6.14.14
- Strapi version: 4.0.0-beta.11
- Database: SQLite
- Operating system:  Linux Mint 20.2

### Additional context

N/A

**Comment by derrickmehaffy** [comment]
Most fixed in beta.12 setting as closed.

**Comment by soupette** [comment]
@derrickmehaffy maybe we should some new issues for the ones that we did not fixed and maybe new upcoming ones  :joy:?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy maybe we should some new issues for the ones that we did not fixed and maybe new upcoming ones joy?

Yeah I'll probably create separate issues for those, it was my mistake to loop all of them into one issue, the remaining ones are just small stuff we can handle later
