### ISSUE TITLE
Strapi V4 not working with Node 16 + npm7/8 (without yarn installed globally)

### ISSUE THREAD

**Issue by jeromelaurens** [strapi/strapi#11729]
### Describe the bug

When running the first command line provided for strapi V4 `npx create-strapi-app my-project --quickstart` , it ends with an error

### Steps to reproduce the behavior

1. Go to your terminal App
2. type `npx create-strapi-app my-project --quickstart`
3. wait
```
> my-project@0.1.0 build
> strapi build "--no-optimization"

Building your admin UI with development configuration ...

● Webpack █████████████████████████ building (10%) 0/1 entries 114/121 dependencies 9/87 modules 71 active
 node_modules/regenerator-runtime/runtime.js

ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/design-system/themes' in '/xxxxxxxxxx/my-project/.cache/admin/src'
...
```
### Expected behavior

Strapi working

### System

- Node.js version: latest LTS : v16.13.0
- NPM version: 8.1.0
- Strapi versionV4
- Database: not yet the problem
- Operating system: MacOS Monterey with ARM Silicon chip

**Comment by be90728** [comment]
I am using the M1 system, and I encountered this situation at the beginning, but then I solved it by the following methods
Maybe you can try the following
(Only for v4)

`npx create-strapi-starter my-project next-blog`

After the installation is over, it will be built automatically, break it.
Then

`cd my-project && cd backend && npm run develop`

This should not be a system problem

Translated By Google

**Comment by derrickmehaffy** [comment]
Issue only occurs when using Node 16 + NPM 7/8 **without** yarn.

Downgrading to Node 14 or installing yarn globally is the workaround

**Comment by jeromelaurens** [comment]
Great ! I can confirm that @derrickmehaffy 's solution to go through yarn installed globally works.
Seems a good workaround to the problem.
The problem with npx is still there, and as @derrickmehaffy says, has probably nothing to do with CPU base, arm or x86.
Is it a problem with MacOS Monterey or simply with V4 + `npm` ?
We can change the issue's title depending on the origin of the problem

**Comment by derrickmehaffy** [comment]
It's v4 + npm 8 only

**Comment by ankit-kumar-jat** [comment]
`npm install @strapi/design-system`
solved problem for me

**Comment by joachimfbinhouse** [comment]
> `npm install @strapi/design-system` solved problem for me

Solved it for me too.

Node v16.13.0
NPM 8.1.0
Strapi 4.0.0

**Comment by biapar** [comment]
I've the same problem.

**Comment by biapar** [comment]
> npm install @strapi/design-system


npx create-strapi-app@latest my-project --quickstart

**Comment by biapar** [comment]
> I am using the M1 system, and I encountered this situation at the beginning, but then I solved it by the following methods Maybe you can try the following (Only for v4) `npx create-strapi-starter my-project next-blog` After the installation is over, it will be built automatically, break it Then `cd my-project && cd backend && npm run develop` This should not be a system problem
> 
> At the same time, you should also use `npx create-strapi-starter my-project next-blog` to build Strapi v4 I don't know why the strapi version created by `npx create-strapi-app` is 3.6.8(v3)


npx create-strapi-app@latest my-project --quickstart

**Comment by marianhlavac** [comment]
There are more issues relevant to missing support for npm, which forces us to use Yarn. Such as failing production builds described in https://github.com/strapi/strapi/issues/12000.

I'm glad there is high severity assigned to this kind of issue. Yarn is great, but let's be considerate to developers who prefer not to use alternative package managers.

👉 Not sure how long the fix will take, but for now, until the issue is resolved, **yarn should be listed as a mandatory requirement in the README file**, not just as a recommended option. Also the [Installation section](https://github.com/strapi/strapi#-installation) shouldn't list npm as a way to install, because it always fails. This causes headaches to many developers who tries to set-up Strapi using npm. Or simply a warning note should be enough.

**Comment by Torsten85** [comment]
Just tried Strapi for the first time. This is really not a good developer experience. 

```sh
$ node -v
v16.13.1

$ npm -v
8.1.2

$ npx create-strapi-app@latest --quickstart --no-run --use-npm strapi-test 
...

$ cd strapi-test && npm run build
> strapi-test@0.1.0 build
> strapi build

Building your admin UI with development configuration ...
TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (/Users/tb/strapi-test/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:141:10)
    at /Users/tb/strapi-test/node_modules/terser-webpack-plugin/dist/index.js:566:67
    at _next33 (eval at create (/Users/tb/strapi-test/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:44:1)
    at _next11 (eval at create (/Users/tb/strapi-test/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (/Users/tb/strapi-test/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:123:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/tb/strapi-test/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/tb/strapi-test/node_modules/@strapi/admin/node_modules/webpack/lib/Compiler.js:1031:26)
    at /Users/tb/strapi-test/node_modules/@strapi/admin/node_modules/webpack/lib/Compiler.js:1073:29
    at Hook.eval [as callAsync] (eval at create (/Users/tb/strapi-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/tb/strapi-test/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/tb/strapi-test/node_modules/@strapi/admin/node_modules/webpack/lib/Compiler.js:1068:28)
    at /Users/tb/strapi-test/node_modules/@strapi/admin/node_modules/webpack/lib/Compiler.js:496:12
    at Compiler.readRecords (/Users/tb/strapi-test/node_modules/@strapi/admin/node_modules/webpack/lib/Compiler.js:908:11)
    at /Users/tb/strapi-test/node_modules/@strapi/admin/node_modules/webpack/lib/Compiler.js:493:11
    at Hook.eval [as callAsync] (eval at create (/Users/tb/strapi-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/tb/strapi-test/node_modules/tapable/lib/Hook.js:18:14)
```

**Comment by abdonrd** [comment]
I just had the same problem as @Torsten85.

**Comment by abdonrd** [comment]
> I just had the same problem as @Torsten85.

Fixed in the `v4.0.3`!

**Comment by JabStrapi** [comment]
Fixed in v4.0.3

**Comment by rdemint** [comment]
I just tried 'npx create-strapi-starter qms-project next-corporate' today with npm 8.1.2 and it did not work.  

It was fixed for me using yarn, although the build errors did not prevent completion of creating the frontend and backend. 

It would have been helpful to have this as an issue on the repo. I created an unnecessary issue.

**Comment by weber-daniel** [comment]
Node: v.16.13.1
npm: 8.1.2

Trying to run: "npx create-strapi-app@latest my-project --quickstart"
even after "npm i -g yarn" it still does not work. Can someone help?
"yarn create strapi-app my-project --quickstart" does not work too.

**Comment by Leviathan91** [comment]
How is this marked as fixed?
I just decided to get started with strapi and wanted the starter to play around a bit.
I use npm v 7.20.0 and node v14.17.3
I am in a new directory, and this is what happens (clearly still broken, even though I followed [the github instruction](https://github.com/strapi/strapi-starter-next-blog)
```
npx create-strapi-starter my-project next-blog
Need to install the following packages:
  create-strapi-starter
Ok to proceed? (y) y
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
? Choose your installation type Quickstart (recommended)
Installing @strapi/starter-next-blog starter.
Creating a quickstart project.
Creating a new Strapi application at /home/philipp/code/ownProjects/strapi/my-project/backend.
Creating files.
Installing @strapi/template-blog template.
Error while installing dependencies:
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: graphql@15.8.0
npm WARN node_modules/graphql
npm WARN   graphql@"^15.5.1" from @strapi/plugin-graphql@4.1.5
npm WARN   node_modules/@strapi/plugin-graphql
npm WARN     @strapi/plugin-graphql@"^4.0.0" from the root project
npm WARN   6 more (@apollo/federation, @graphql-tools/schema, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer graphql@"^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0" from graphql-iso-date@3.6.1
npm WARN node_modules/graphql-iso-date
npm WARN   graphql-iso-date@"^3.6.1" from @strapi/plugin-graphql@4.1.5
npm WARN   node_modules/@strapi/plugin-graphql
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: graphql@15.8.0
npm WARN node_modules/graphql
npm WARN   graphql@"^15.5.1" from @strapi/plugin-graphql@4.1.5
npm WARN   node_modules/@strapi/plugin-graphql
npm WARN     @strapi/plugin-graphql@"^4.0.0" from the root project
npm WARN   6 more (@apollo/federation, @graphql-tools/schema, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer graphql@"^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from graphql-type-long@0.1.1
npm WARN node_modules/graphql-type-long
npm WARN   graphql-type-long@"^0.1.1" from @strapi/plugin-graphql@4.1.5
npm WARN   node_modules/@strapi/plugin-graphql
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   react@"^17.0.2" from @strapi/plugin-users-permissions@4.1.5
npm WARN   node_modules/@strapi/plugin-users-permissions
npm WARN     @strapi/plugin-users-permissions@"4.1.5" from the root project
npm WARN   21 more (@strapi/helper-plugin, react-select, react-dom, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^15.3.0 || ^16.0.0-alpha" from react-virtualized@9.22.3
npm WARN node_modules/react-virtualized
npm WARN   react-virtualized@"^9.22.3" from @strapi/admin@4.1.5
npm WARN   node_modules/@strapi/admin
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   react-dom@"^17.0.2" from @strapi/plugin-users-permissions@4.1.5
npm WARN   node_modules/@strapi/plugin-users-permissions
npm WARN     @strapi/plugin-users-permissions@"4.1.5" from the root project
npm WARN   8 more (@strapi/helper-plugin, react-select, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^15.3.0 || ^16.0.0-alpha" from react-virtualized@9.22.3
npm WARN node_modules/react-virtualized
npm WARN   react-virtualized@"^9.22.3" from @strapi/admin@4.1.5
npm WARN   node_modules/@strapi/admin
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: @types/node@10.17.60
npm ERR! node_modules/@types/node
npm ERR!   @types/node@"^10.1.0" from @apollo/protobufjs@1.2.2
npm ERR!   node_modules/@apollo/protobufjs
npm ERR!     @apollo/protobufjs@"1.2.2" from apollo-reporting-protobuf@3.3.1
npm ERR!     node_modules/apollo-reporting-protobuf
npm ERR!       apollo-reporting-protobuf@"^3.0.0" from apollo-server-core@3.1.2
npm ERR!       node_modules/apollo-server-core
npm ERR!         apollo-server-core@"3.1.2" from @strapi/plugin-graphql@4.1.5
npm ERR!         node_modules/@strapi/plugin-graphql
npm ERR!         1 more (apollo-server-koa)
npm ERR!       1 more (apollo-server-types)
npm ERR!   @types/node@"*" from @types/accepts@1.3.5
npm ERR!   node_modules/@types/accepts
npm ERR!     @types/accepts@"^1.3.5" from apollo-server-koa@3.1.2
npm ERR!     node_modules/apollo-server-koa
npm ERR!       apollo-server-koa@"3.1.2" from @strapi/plugin-graphql@4.1.5
npm ERR!       node_modules/@strapi/plugin-graphql
npm ERR!         @strapi/plugin-graphql@"^4.0.0" from the root project
npm ERR!     @types/accepts@"*" from @types/koa@2.13.4
npm ERR!     node_modules/@types/koa
npm ERR!       @types/koa@"^2.11.6" from apollo-server-koa@3.1.2
npm ERR!       node_modules/apollo-server-koa
npm ERR!         apollo-server-koa@"3.1.2" from @strapi/plugin-graphql@4.1.5
npm ERR!         node_modules/@strapi/plugin-graphql
npm ERR!       3 more (@types/koa__cors, @types/koa-bodyparser, @types/koa-compose)
npm ERR!   16 more (@types/koa, @types/cookies, @types/connect, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @types/node@">= 12" from react-dnd@14.0.5
npm ERR! node_modules/react-dnd
npm ERR!   react-dnd@"^14.0.2" from @strapi/admin@4.1.5
npm ERR!   node_modules/@strapi/admin
npm ERR!     @strapi/admin@"4.1.5" from @strapi/strapi@4.1.5
npm ERR!     node_modules/@strapi/strapi
npm ERR!       @strapi/strapi@"4.1.5" from the root project
npm ERR!       1 more (@strapi/plugin-graphql)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/philipp/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/philipp/.npm/_logs/2022-03-21T20_59_10_038Z-debug.log

 Keep trying!             

Oh, it seems that you encountered errors while installing dependencies in your project.
```

**Comment by torres-leo** [comment]
It works for me!
Node Version: 16.14.2
npm: 8.7.0
strapi: 4.1.8

command: npx create-strapi-app@latest name-project --quickstart

**Comment by oyedeletemitope** [comment]
> It works for me! Node Version: 16.14.2 npm: 8.7.0 strapi: 4.1.8
> 
> command: npx create-strapi-app@latest name-project --quickstart

mine didn't work. Any ideas why?

**Comment by Leviathan91** [comment]
How  is this closed, I just tried again today and still not fixed. Such a bad experience

**Comment by khalidabdou** [comment]
i uninstall plugin awesome seo and it's work fine
`npm uninstall @exfabrica/strapi-plugin-awesome-seo`

**Comment by stevechen** [comment]
> i uninstall plugin awesome seo and it's work fine `npm uninstall @exfabrica/strapi-plugin-awesome-seo`

Thank you! This solved my problem.

**Comment by sangdth** [comment]
> i uninstall plugin awesome seo and it's work fine `npm uninstall @exfabrica/strapi-plugin-awesome-seo`

I have error:
```
backend:dev: ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client' ...
```

Uninstalled the seo and it works now.

**Comment by MatthewJRoybal** [comment]
[> > i uninstall plugin awesome seo and it's work fine `npm uninstall @exfabrica/strapi-plugin-awesome-seo`
> 
> I have error:
> 
> ```
> backend:dev: ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client' ...
> ```
> backend:dev: ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client' ...
> Uninstalled the seo and it works now.](backend:dev: ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client' ...)

I am having this same error when trying to upgrade to 14.3.3. What do you mean by you uninstalled the seo?

**Comment by MatthewJRoybal** [comment]
> npm uninstall @exfabrica/strapi-plugin-awesome-seo

I have this same issue trying to upgrade to 4.13.3, but I do not have '@exfabrica/strapi-plugin-awesome-seo' installed. Is there another reason why this is happening?
