### ISSUE TITLE
[v4] sort by graphql duplicating rows

### ISSUE THREAD

**Issue by GautierDele** [strapi/strapi#11892]
### Describe the bug

Graphql sort on nested relations is basically duplicating rows as a join would do.
This was working in v3.

### Steps to reproduce the behavior

Create your graphql query on a resource that has a relation. This is a one to many in this case, this should work for any relation i think
![image](https://user-images.githubusercontent.com/12382966/145875139-6c35a982-2145-42ad-b8a6-f300eaf9a03b.png)

Call this in your sort parameters:
![image](https://user-images.githubusercontent.com/12382966/145875198-7df2f9b2-a47a-41d8-9bea-44105940d34c.png)

### Expected behavior

Should only have one row per item but this is duplicated:
![image](https://user-images.githubusercontent.com/12382966/145875347-61f3bb05-b552-421f-96c7-b5ce9c163bda.png)

As you can see there i have multiples rows with the same id depending on the number of nested articles linked to the category.

### System

- Node.js version: 14.18.1
- NPM version: 6.14.15
- Strapi version: 4.0.0
- Database: MySQL
- Operating system: Windows 11

**Comment by iicdii** [comment]
Is it the same when you request data through REST API?

**Comment by GautierDele** [comment]
Yes it is:
![image](https://user-images.githubusercontent.com/12382966/146079585-7e85683a-877c-4096-a8d7-ea27c138dd9f.png)

**Comment by derrickmehaffy** [comment]
I don't believe this is possible as I'm looking at the sort code and I believe sort can only be at the parent level (you can sort the relational data itself but you can't sort the parent data on the relational responses.)

Looping in @strapi/maintainers here as I'm honestly not sure.
(Tested and validated the above doesn't work, nor does something like this:

![image](https://user-images.githubusercontent.com/8593673/146996531-44c002f1-b6e1-411f-ac5c-14503ca0b110.png)

**Comment by GautierDele** [comment]
This was working in v3 and is something I think really usefull when you want to avoid multiple queries

**Comment by alexandrebodin** [comment]
Nested sorting should work. There seems to be an issue with joins that aren't distinct for some reason. that's a valid bug

**Comment by GautierDele** [comment]
@derrickmehaffy do we have anything new on this please ?

**Comment by derrickmehaffy** [comment]
I haven't tested in latest versions but nothing new

**Comment by GautierDele** [comment]
Can confirm this is still hapening in 4.0.6

![image](https://user-images.githubusercontent.com/12382966/151672335-4a3b86af-beee-4168-8959-c61887d266d6.png)

**Comment by GautierDele** [comment]
Hello @Convly,

Do you have anything new on this maybe ? Thanks :)

**Comment by Convly** [comment]
Hey, it's definitely something that I have in my backlog. I'll try to get at it as soon as I can, even though it'll probably be not before ~one or two weeks. Sorry for the time it's taking, I know this is quite an annoying one.

**Comment by GautierDele** [comment]
Ok thanks for the feedback ! have a great week

**Comment by GautierDele** [comment]
Hello, Anything new on this maybe ?

**Comment by Convly** [comment]
Hey, sorry for the time it's taking and for the time it took me to answer you, I've been dealing with Typescript support for the last month and it left very little time for anything else. It's definitely something I've on my radar but I cannot promise any ETA right now. Really sorry for this situation. I'll keep you updated when I'll work on it.

**Comment by ReyRod** [comment]
This is happening on my end too, had to manually sort in the frontend

**Comment by xelinorg** [comment]
I have tested https://github.com/strapi/strapi/pull/13387 but it looks like it is breaking filtering on related field.

What I have tried is to normalize joins and it is working for the duplication problem but is not sorting at all the nested items.

Here on the join helper I have created a function where I am using joinTable and qb.state.joins to fish out an alias that could satisfy the query and avoid running the createPivotJoin function that is adding more alias and joins that potentially are causing the issue.

https://github.com/strapi/strapi/blob/c006f74a4e3f19ff0e70e8a30d10f3aa10ff13c2/packages/core/database/lib/query/helpers/join.js#L51

So I have changed the code in line 51 of the join helper into something like this...

` return existing(joinTable, qb.state.joins) || createPivotJoin(qb, joinTable, alias, tragetMeta);`

The function looks like this

```
const existing = (nextJoin, stateJoins) => {
  const foundA = stateJoins.filter(j => j.referencedTable === nextJoin.name
    && j.referencedColumn === nextJoin.joinColumn.name
    && j.rootColumn === nextJoin.inverseJoinColumn.referencedColumn
  )
  const found = foundA.length && foundA[0].alias ? foundA[0]: null;
  if (found) {
    const usable = stateJoins.filter(j => j.rootTable === found.alias
      && j.rootColumn === nextJoin.inverseJoinColumn.name
      && j.referencedColumn === nextJoin.inverseJoinColumn.referencedColumn
    )
    return usable.length && usable[0].alias ? usable[0].alias: null;
  }
}
```

The code I have created is pretty ugly and that is because I do not know if my logic is correct in order to make it better. 

I am struggling to understand how strapi is handling relations and nested items. I am logging all the queries and I can see that is doing two queries when there is a relation and I have not find out yet how it is creating the nested data and if it needs the data to be flat or not.

Another issue that I can see is the use of distinct in cases that should be using groupBy, Actually I believe that the groupBy is never used and there is no code that will drive execution to the place that will create grouping at the sql level through the query builder.

I hope that I am not causing any confusion as I am trying to help. I have some spare time and I will continue looking into this and all the related issues hoping that someone will eventually solve that.

**Comment by xelinorg** [comment]
The previous attempt is missing some things... is hard to test manually all the cases if there are not automated test to tell you what is effected by the changes. This needs groupBy if there is no filtering on the related field something similar with solution on https://github.com/strapi/strapi/pull/13387 given by @Bassel17 

But in general the inner sorting needs more work at least when populating, so I had to add some more ugly code to try out a fix for the many to many case. I have read most of the database package and I can not find a better way to fix the sql queries as should be in my view. I do not know if what I have done is breaking something else that I have not tested. 

Take a look a the diff here https://github.com/strapi/strapi/commit/48d3e0ec68255c97116581afc529c7449f8ffe52

Is messy because the rest of the codebase needs some refactoring to be more friendly for an engineer to give a better solution without having to do crazy things.

I am not going to make a pull request because this needs more work to be sane. I am trying to give you some hints about what I see while I have been digging on some of the database issues you have open. If you want you can check for yourselves and evaluate if this direction could give some solutions to the databases related problems.

**Comment by GautierDele** [comment]
We are nearly coming to a year of this issue, is this fixed by any other way right now or still there ?

**Comment by akasummer** [comment]
@GautierDele Unfortunately, still happening on the latest version...

**Comment by GautierDele** [comment]
@akasummer for almost a year i forgave, this wont be fixed for such a major problem. Either you find an alternative or you find another solution

**Comment by taker93** [comment]
This is also a problem with the REST API, not only GraphQL.

I'd call it a gamebreaker...

**Comment by Pawel-dev5** [comment]
I resolved that problem by sorting items with two parameters: title which is for me sorting items and you must add sorting by id, then pagination working great.

`qs.stringify(
		{
			populate: {
				[`${shopName}Prices`]: {
					populate: '*',
				},
			},
			filters: {
				category: {
					$in: category,
				},
			},
			sort: ['title:asc', 'id:asc'],
			pagination: {
				page: paginationStart,
				pageSize: 50,
			},
		},
		{
			encodeValuesOnly: true,
		},
	)`

**Comment by LapX** [comment]
This is a real problem. Why isn't this solved yet ?

**Comment by Bassel17** [comment]
@LapX this is considered a rather complicated issue, fixing it correctly on the DB level would require a different solution for every database we support. We just didn't get the time or priority to move forward with it yet.

**Comment by iamandrewluca** [comment]
We also started experiencing this issue 2 weeks ago.
Today we realised that the problem was in some custom code in the lifecycle hooks of the Content-Type.

So I would recommend giving a look at your lifecycle hooks if you have any.

**Comment by lcxfs1991** [comment]
Same issue here. Hope that it will be fixed soon.

**Comment by DeividVeloso** [comment]
Trying to sort using this code is not working and I could not find any documentation to it


Query:


![image](https://github.com/strapi/strapi/assets/16343871/29b460cc-f612-43cf-8c46-fe238ecc9835)


I tried in many ways like 

```
  "sort": [
   "name:desc"
  ]

  "sort": "name:desc"
```

**Comment by HarjasSodhi** [comment]
Issue is there when using repeatable components as well. Can anybody suggest a solution? I cant sort manually because i have applied pagination as well and getting all the data first and then sorting and paging it would not be efficient.

**Comment by MaximeDetaille** [comment]
Any update on this issue ?

**Comment by ihor-zinchenko** [comment]
same for me, any updates?

**Comment by Convly** [comment]
Hey there :wave: 

The issue has been addressed in #20543.

The fix will be released tomorrow in `5.0.0-beta.14`.
As of now, we don't plan on porting this fix to v4, but if someone wants to take a look at it, feel free to do so.

Have a good day!
