### ISSUE TITLE
[v4] filling from another locale

### ISSUE THREAD

**Issue by GautierDele** [strapi/strapi#12002]
### Describe the bug

Basically when you fill from another locale the app is either crashing or infinitely loading

### Steps to reproduce the behavior

Basically you need to have multiple locales.

There are 2 cases on this bug:

Either you copy a locale on an existing entity and it creates infinite loading:
![image](https://user-images.githubusercontent.com/12382966/147145072-a73083b4-1b34-4e20-ae63-a6e4e8adee36.png)
![image](https://user-images.githubusercontent.com/12382966/147144726-8e14db20-b28c-46ce-8232-531fd6c36f8e.png)

or on a not existing entity (not saved when switching locale):
![image](https://user-images.githubusercontent.com/12382966/147144943-f173ee19-80db-49bf-b2b5-f11ec8a0e024.png)
![image](https://user-images.githubusercontent.com/12382966/147144808-3d8bd777-c958-467e-b75d-8c5d064efb9b.png)

On this resource i have:
- A dynamic zone with multiple components
![image](https://user-images.githubusercontent.com/12382966/147145303-62370610-4d2e-4aae-af43-c9edb98574f9.png)
- A component
![image](https://user-images.githubusercontent.com/12382966/147145265-08ed15ff-1e00-433f-8f62-32c0573f48f0.png)
- A relation to another field 
![image](https://user-images.githubusercontent.com/12382966/147145236-1484ea9e-d9cb-46ad-84be-8266e693556e.png)
- some basic fields
![image](https://user-images.githubusercontent.com/12382966/147145342-0e389ad1-2e97-4074-9caf-4328ef412a49.png)

### Expected behavior

Should be able to copy the other locale on current one correctly.

I thought this was supposed to be fixed in 4.0.2 but I had a misunderstanding.

### System

- Node.js version: 14.18.1
- NPM version: 6.14.15
- Strapi version: 4.0.0
- Database: MySQL
- Operating system: Windows 11

**Comment by derrickmehaffy** [comment]
> Strapi version: 4.0.0

Are you on v4.0.0 or v4.0.2?

**Comment by GautierDele** [comment]
My bad, i'm on 4.0.2 but this wasn't working on both version

**Comment by GautierDele** [comment]
I have more on this, it seems like it only works when you fill english from another locale, filling locale from english is working well !

**Comment by ari-motors-team** [comment]
same for me on every locale

**Comment by derrickmehaffy** [comment]
Can you all test on the latest release, I believe this should be fixed.

**Comment by GautierDele** [comment]
I can confirm that this bug is still present if you fill from another locale and the entry already exists
