### ISSUE TITLE
populateCreatorFields not working in Strapi v4

### ISSUE THREAD

**Issue by vandrieu** [strapi/strapi#12228]
### Describe the bug

Creator fields are not returned by Strapi V4 REST API even when `populateCreatorFields` is set to true.

### Steps to reproduce the behavior

1. Install Strapi v4
2. Start the server using `npm run develop`
3. Using Strapi admin panel, create a collection type with a `name` field
4. Add an entry manually using the admin panel GUI
5. Allow the collection to be queried through the public API (settings > roles and permissions > Public > add `find` and `findOne` on your collection and save)
6. Query the data using the REST API
7. Creator fields are not shown which is normal as per the V4 docs since populateCreatorFields is false by default: https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#model-options
8. Change the `options` in `src/api/<collection>/content-types/<collection>/schema.json` to the following:
```
{
  "kind": "collectionType",
  //...some configs
  "options": {
    "privateAttributes": ["name"],
    "populateCreatorFields": true
  },
```
9. Make sure the server restarts or restart it
10. Query the API again

### Expected behavior

`name` field is not returned anymore
`created_by` field is returned

### Actual behavior

`name` field is not returned anymore
**_`created_by` field is not returned_**

### System

- Node.js version: v14.18.2
- NPM version: 6.14.13
- Strapi version: 4.0.4
- Database: sqlite
- Operating system: MacOS

**Comment by redakzter01** [comment]
some workaround?

**Comment by niwasmala** [comment]
Here is some workaround. It doesn't need to set "populateCreatorFields" options. You can use strapi db query and ask to populate createdBy field.

If you use Graphql API, you need to extend the query you want

```js
// path: ./src/index.js

module.exports = {
  register({ strapi }) {
    const extensionService = strapi.plugin('graphql').service('extension');

    const extension = ({ nexus }) => ({
      types: [
        // creating new object type called Creator
        nexus.objectType({
          type: 'Creator',
          name: 'Creator',
          definition(t) {
            t.int('id');
            t.string('firstname');
            t.string('lastname');
          },
        }),
        nexus.extendType({
          type: 'Article',
          definition(t) {
            // we want to know who is the creator
            t.field('createdBy', {
              type: 'Creator',
              async resolve(root, args, ctx) {
                // when we use query, we can populate createdBy
                const query = strapi.db.query('api::article.article');
                const article = await query.findOne({
                  where: {
                    id: root.id,
                  },
                  populate: ['createdBy'],
                });
                
                return {
                  id: page.createdBy.id,
                  firstname: page.createdBy.firstname,
                  lastname: page.createdBy.lastname,
                };
              },
            })
          }
        }),
      ],
    });

    extensionService.use(extension);
  }
}    
```

When I query articles, I can ask for the createdBy
```gql
query {
  articles {
    data {
      attributes {
        createdBy {
          id
          firstname
          lastname
        }
      }
    }
  }
}
```

If you use REST API, you can extend the controller

```js
'use strict';

/**
 *  article controller
 */

const { createCoreController } = require('@strapi/strapi').factories;

module.exports = createCoreController('api::article.article', ({ strapi }) => ({
  async find(ctx) {
    // Calling the default core action
    const { data, meta } = await super.find(ctx);

    const query = strapi.db.query('api::article.article');

    await Promise.all(
      data.map(async (item, index) => {
        const article = await query.findOne({
          where: {
            id: item.id,
          },
          populate: ['createdBy'],
        });
        
        data[index].attributes.createdBy = {
          id: page.createdBy.id,
          firstname: page.createdBy.firstname,
          lastname: page.createdBy.lastname,
        };
      })
    );

    return { data, meta };
  },
}));
```

**Comment by derrickmehaffy** [comment]
This is correct, we don't populate anything by default so you need to specify the population in v4

**Comment by vandrieu** [comment]
@derrickmehaffy the last version of the docs reads:
```
populateCreatorFields
Boolean
Toggles including the created_by and updated_by fields in the API response.
```

English is not my main language so maybe I just don't understand the sentence correctly. To me, it means if populateCreatorFields is true, then the created_by and updated_by fields will be included in the API response.

Did I misunderstood? If I misunderstood, then would you please clarify what is the real meaning of populateCreatorFields?

Also, if populateCreatorFields does not allow to include created_by and updated_by in the API response then what is the 'official' way of doing it (besides using fancy workarounds like the ones above)?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy the last version of the docs reads:
> ```
> populateCreatorFields
> Boolean
> Toggles including the created_by and updated_by fields in the API response.
> ```
> 
> English is not my main language so maybe I just don't understand the sentence correctly. To me, it means if populateCreatorFields is true, then the created_by and updated_by fields will be included in the API response.
> 
> Did I misunderstood? If I misunderstood, then would you please clarify what is the real meaning of populateCreatorFields?
> 
> Also, if populateCreatorFields does not allow to include created_by and updated_by in the API response then what is the 'official' way of doing it (besides using fancy workarounds like the ones above)?

This is a legacy setting from Strapi v3 which automatically populated those fields, in v4 this is no longer an option so this setting I believe now only allows you to populate them at query time.

We have no method to auto populate anything in Strapi v4, so this documentation probably could be updated to reflect that.

**Comment by jsanta** [comment]
I know this issue is closed but, is the creator fields issue solved in version 4.* ? I'm trying it  using the REST API and  those fields are not appearing on the response.

**Comment by arkni8** [comment]
Hello maintainers of this documentation. I see that this issue is still confusing some people who are coming in new to Strapi (as was I) so after I figured it out, I thought I should just help you guys update the documentation a bit to reflect the steps better for v4.

So I have made the necessary changes in my local environment but I am not completely sure how to proceed with the push request after that (this is my first time doing an contribution :) )

https://github.com/arkni8/documentation/blob/dev/populating-field/docs/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.md

That the link to the fork I have worked on, you guys can check the changes I have made in the commit. And then maybe instruct me what to do next

**Comment by derrickmehaffy** [comment]
> Hello maintainers and @derrickmehaffy of this documentation. I see that this issue is still confusing some people who are coming in new to Strapi (as was I) so after I figured it out, I thought I should just help you guys update the documentation a bit to reflect the steps better for v4.
> 
> So I have made the necessary changes in my local environment but I am not completely sure how to proceed with the push request after that (this is my first time doing a contribution :) )
> 
> https://github.com/arkni8/documentation/blob/dev/populating-field/docs/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.md
> 
> That's the link to the fork I have worked on, you guys can check the changes I have made in the commit. And then maybe instruct me what to do next..

Can you open a PR against the documentation repo :pray:

**Comment by ciekawy** [comment]
wow and I just found the createdBy isn't even regular user who signed up e.g. via google, thats sooo confusing ;(

**Comment by kristijorgji** [comment]
I created a `Post` content type and want to return the `author` back when I fetch the posts, how can I do this?

I do see in Strapi admin panel on the right side "author: Somename" but even with query parameter populate=* I still don't receive author and createdAt fields
