### ISSUE TITLE
[v4] [Docker] Missing style with production env build

### ISSUE THREAD

**Issue by andriivasylchenko** [strapi/strapi#12371]
### Describe the bug

Good afternoon! I'm trying to deploy v4 Strapi to Kubernetes with a custom docker image (to have minimal changes to the list of installed plugins, translation, and logo). I've managed to set up the whole CI flow, but for some unknown reason, styles are missing from the Admin dashboard. I don't know exactly where to look for an error, so any advice is highly appreciated. To exclude additional complexity in the ask, I've removed Kubernetes and DevOps pieces from steps to reproduce to stick with pure docker.

### Steps to reproduce the behavior

1. Perform regular Strapi v4 project creation with CLI

2. Create the following files on the filesystem

**Dockerfile**
```
FROM node:14-alpine
RUN apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash
WORKDIR /
COPY . .
RUN npm install
ENV NODE_ENV=production
RUN npm run build
CMD ["node", "server.js"]
EXPOSE 1337
```

**.dockerignore**
```
node_modules
env.example
.cache
.tmp
build
Dockerfile
```

**server.js**
```
const strapi = require('@strapi/strapi');

strapi(/* {...} */).start();
```

3. Build the image

```
docker build -t strapi-v4-custom-image .
```

4. Launch image locally

```
docker run --publish 1337:1337 strapi-v4-custom-image
```

5. Navigate to admin dashboard

https://localhost:1337/admin/

### Expected behavior

Styles should be loaded (including fonts, colors, padding and etc)

### Screenshots

![image](https://user-images.githubusercontent.com/10487371/152024649-b362e660-0c7b-4341-a90f-f5aee557475c.png)

### System

- Node.js version: v14-alpine
- Strapi version: v4.0.6
- Database: sqlite

Thanks in advance for any reply!

**Comment by andriivasylchenko** [comment]
So typical.. it took me to write it all down just to realize that the issue is within improper bootstrap inside **server.js**.
I've took that file example from documentation https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment.html with a hope to use pm2 after, but seems like it is the one causing troubles.

Step to fix the problem:

- replace *CMD ["node", "server.js"]*  with *CMD npm run start* inside Dockerfile

So this issue now transforms into a question of what's wrong with this bootstrap for v4?

```
const strapi = require('@strapi/strapi');

strapi(/* {...} */).start();
```

**Comment by derrickmehaffy** [comment]
> So typical.. it took me to write it all down just to realize that the issue is within improper bootstrap inside **server.js**. I've took that file example from documentation https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment.html with a hope to use pm2 after, but seems like it is the one causing troubles.
> 
> Step to fix the problem:
> 
> * replace _CMD ["node", "server.js"]_  with _CMD npm run start_ inside Dockerfile
> 
> So this issue now transforms into a question of what's wrong with this bootstrap for v4?
> 
> ```
> const strapi = require('@strapi/strapi');
> 
> strapi(/* {...} */).start();
> ```

That looks perfectly fine :thinking: 

I was just debugging this issue with another user the other day and I couldn't reproduce it locally but I wasn't using the server.js file.

And testing that exact server.js locally doesn't have the same problem. There is something going on with docker that is breaking the styles

![image](https://user-images.githubusercontent.com/8593673/152044533-8e8650f9-ae76-438b-934f-cdb1c334cc47.png)

**Comment by derrickmehaffy** [comment]
Note I did not test with docker yet as I don't generally use docker (don't even have it installed), but my assumption here is that spinning it up in docker will yield the error. 

No idea how this is even possible but something is a little off.

**Comment by niftytushar** [comment]
Any update here? I am also facing the same problem.

**Comment by Jon-Myrstad** [comment]
We're also facing the same issue using the example custom Dockerfile found here https://github.com/strapi/strapi-docker/blob/master/examples/custom/Dockerfile based on strapi/base. Everything works fine when working on it locally, either in development or built for production, but once we wrap it up inside docker it breaks.

**Comment by andriivasylchenko** [comment]
As I was saying above, for me it was fixed when I replace the launch command. So resulting Dockerfile will look like this 
`
FROM node:14-alpine
RUN apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash
WORKDIR /
COPY . .
RUN npm install
ENV NODE_ENV=production
RUN npm run build
CMD npm run start
EXPOSE 1337
`

**Comment by derrickmehaffy** [comment]
> As I was saying above, for me it was fixed when I replaced the launch command. So resulting Dockerfile will look like this
> 
> ```
> FROM node:14-alpine
> RUN apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash
> WORKDIR /
> COPY . .
> RUN npm install
> ENV NODE_ENV=production
> RUN npm run build
> CMD npm run start
> EXPOSE 1337
> ```

What was your launch command before the change? develop instead of start? (changing that command shouldn't be doing anything differently other than disabling the auto-restart watcher.

**Comment by Sylchi** [comment]
For some reason if I changed the workdir to /opt/app/strapi then the styles magically returned. Could be something to do with root directory

**Comment by derrickmehaffy** [comment]
> For some reason if I changed the workdir to /opt/app/strapi then the styles magically returned. Could be something to do with root directory

That's interesting :thinking: what is your base image?

**Comment by pridemusvaire** [comment]
> For some reason if I changed the workdir to /opt/app/strapi then the styles magically returned. Could be something to do with root directory

@Sylchi , changing the directory works like a charm

**Comment by derrickmehaffy** [comment]
Well now, that's odd :thinking:

**Comment by gu-stav** [comment]
Hey everyone. I'm working on a fix for something else at the moment and I'm wondering if it would even apply to this issue. Could you do me a favor and replace the content of `node_modules/@strapi/admin/webpack.alias.js` with:

```js
'use strict';

const path = require('path');

const aliasExactMatch = [
  '@strapi/design-system',
  '@strapi/helper-plugin',
  '@strapi/icons',
  '@fortawesome/fontawesome-svg-core',
  '@fortawesome/free-solid-svg-icons',
  'date-fns',
  'formik',
  'history',
  'immer',
  'qs',
  'lodash',
  'moment',
  'react',
  'react-copy-to-clipboard',
  'react-dnd',
  'react-dnd-html5-backend',
  'react-dom',
  'react-error-boundary',
  'react-fast-compare',
  'react-helmet',
  'react-is',
  'react-intl',
  'react-query',
  'react-redux',
  'react-router',
  'react-router-dom',
  'react-virtualized',
  'react-select',
  'redux',
  'reselect',
  'styled-components',
  'whatwg-fetch',
  'yup',
];

const alias = [
  'react-select/animated',
  'react-select/async',
  'react-select/async-creatable',
  'react-select/base',
  'react-select/creatable',
];

// See https://webpack.js.org/configuration/resolve/
module.exports = {
  ...alias.reduce((acc, name) => {
    acc[name] = require.resolve(name);
    return acc;
  }, {}),

  ...aliasExactMatch.reduce((acc, name) => {
    acc[`${name}$`] = require.resolve(name);
    return acc;
  }, {}),

  ee_else_ce: path.resolve(__dirname),
};
```

and then run `yarn build` / `npm build` again.

**Comment by gu-stav** [comment]
Hello again everybody. We have released version `4.2.1-alpha.0` which contains the fix done in https://github.com/strapi/strapi/pull/13606 to properly test it in real-world scenarios. It does not contain anything else, so it should be safe to install.

If you could give it a run and report back, if you experience any problems or if this problem seems to be fixed for you, that would be awesome.

**Comment by derrickmehaffy** [comment]
I believe this issue to be resolved as we should have long since merged this and I'm unable to reproduce given the new docker documentation we released. Marking as closed

**Comment by ScarletFlash** [comment]
Looks like this issue is still reproducible.

```dockerfile
# Dockerfile

FROM node:18-alpine
ENV NODE_ENV = production

WORKDIR /
COPY . .

RUN npm ci && npm run build:no-optimization

CMD npm run start
EXPOSE 1337

```

```ignore
# .dockerignore

.cache
node_modules
dist
```

```json
# package.json

{
  "name": "my-project",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "build:no-optimization": "strapi build --no-optimization",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/strapi": "latest",
    "@strapi/plugin-users-permissions": "latest",
    "@strapi/plugin-i18n": "latest",
    "pg": "latest"
  },
  "strapi": {
    "uuid": "d342b29f-d840-40c4-a4aa-f715bbedb98b"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  }
}
```

```json
# package-lock.json

    ...
    "node_modules/@strapi/strapi": {
      "version": "4.4.5",
      ...
```

This is raw installation.

**Comment by derrickmehaffy** [comment]
Could things:

- you should never use "latest" like that with our packages, albeit it's rare, but sometimes we do issue small migration guides in patch versions if required
- change your workdir to something other than root like `/opt/`
