### ISSUE TITLE
[i18n] Create locale

### ISSUE THREAD

**Issue by sunnysonx** [strapi/strapi#12381]
### Describe the bug

When trying to create the locale programmatically with `query().create()`, e.g.:
```
strapi.query("plugin::i18n.locale").create({
      data: {
          name: "Spanish",
          code: "es",
        },
    });
```
An error occurs:
ValidationError: [1] is not an existing permission action

Works fine with query().createMany(), e.g.:
```
await strapi.query("plugin::i18n.locale").createMany({
      data: [
        {
          name: "Spanish",
          code: "es",
        },
      ],
    });
```

### Expected behavior

The locale to be created with query().create().

### Screenshots

![image](https://user-images.githubusercontent.com/14160283/152138689-7a9ad941-a3ed-4ff6-812d-1de3d19e92da.png)

- Node.js version: v14
- NPM version: latest
- Strapi version: v4
- Database: PostgreSQL
- Operating system: WSL2

**Comment by derrickmehaffy** [comment]
@sunnysonx shouldn't these be `strapi.db.query` not `strapi.query`?

**Comment by sunnysonx** [comment]
> @sunnysonx shouldn't these be `strapi.db.query` not `strapi.query`?

@derrickmehaffy sorry, I have missed your reply.

There is no difference between `strapi.db.query` and `strapi.query` (screen from strapi's source code):
![image](https://user-images.githubusercontent.com/14160283/154483404-6cc4c88d-9873-4314-93f2-d435cb08c773.png)
Btw, tested with both `strapi.db.query` and `strapi.query`, same error. 
I traced the error, and it seems to be related to the fact that when a locale is created, strapi tries to attach the permissions for a new locale to the super-admin role, but something goes wrong when trying to create it programmatically.

**Comment by aique** [comment]
Hi!.

Same problem here.

I fixed it by adding an `id` to de object:

```
async function enableLocales(strapi) {
  const esLocale = await strapi.service('plugin::i18n.locales').findById(2);

  if (esLocale === null) {
    await strapi.service('plugin::i18n.locales').create({
      id: 2,
      name: 'Spanish (es)',
      code: 'es',
    });
  }
}
```

**Comment by roberto-red** [comment]
Using [the i18n service](https://github.com/strapi/strapi/blob/master/packages/plugins/i18n/server/services/locales.js#L17):

```
  async bootstrap({ strapi }) {
    const i18nService = strapi.service('plugin::i18n.locales');

    if (null === await i18nService.findByCode('es')) {
      await i18nService.create({
        name: 'Spanish (es)',
        code: 'es',
      });
    }
    
    /* ... */
  }
```

I'm getting the following when running `yarn develop`:
```
[2022-07-14 10:58:10.759] error: [29] is not an existing permission action
ValidationError: [29] is not an existing permission action
    at handleYupError (/Users/<User>/<Project>/node_modules/@strapi/utils/lib/validators.js:63:9)
    at /Users/<User>/<Project>/node_modules/@strapi/utils/lib/validators.js:73:5
    at async Object.assignPermissions (/Users/<User>/<Project>/node_modules/@strapi/admin/server/services/role.js:313:3)
    at async Object.syncSuperAdminPermissionsWithLocales (/Users/<User>/<Project>/node_modules/@strapi/plugin-i18n/server/services/permissions/actions.js:95:3)
    at async Object.afterCreate (/Users/<User>/<Project>/node_modules/@strapi/plugin-i18n/server/bootstrap.js:52:7)
    at async Object.run (/Users/<User>/<Project>/node_modules/@strapi/database/lib/lifecycles/index.js:76:11)
    at async Object.create (/Users/<User>/<Project>/node_modules/@strapi/database/lib/entity-manager.js:185:7)
    at async bootstrap (/Users/<User>/<Project>/src/index.js:40:7)
    at async Strapi.runLifecyclesFunctions (/Users/<User>/<Project>/node_modules/@strapi/strapi/lib/Strapi.js:484:7)
    at async Strapi.bootstrap (/Users/<User>/<Project>/node_modules/@strapi/strapi/lib/Strapi.js:417:5)
error Command failed with exit code 1.
```

The mentioned `id` trick doesn't seem to work.

Node.js version: v16.16.0
Yarn version: v1.22.17
Strapi version: v4.2.2
Database (local development): SQLite
Operating system: MacOS Monterey (12.4)

**Comment by roberto-red** [comment]
Spanish locale isn't a custom locale, [it's included in the i18n plugin constants](https://github.com/strapi/strapi/blob/v4.2.2/packages/plugins/i18n/server/constants/iso-locales.json#L1654-L1657). I think this fact discards the need to patch that package, doesn't it?

What we want to do is add a locale to the Strapi installation programmatically, not through the admin panel GUI. My own use case is to add it in the `bootstrap` lifecycle hook before seeding some initial localized data.

**Comment by derrickmehaffy** [comment]
As in add it to the list of enabled locales? Then yeah patch-package shouldn't be needed. I'm not sure of the API needed in this case :thinking:

**Comment by derrickmehaffy** [comment]
Just tested this on v4.4.5:

```js
const result = await strapi.query('plugin::i18n.locale').create({ data: { name: 'German (de)', code: 'de' }})
```

**Comment by segovia** [comment]
> Just tested this on v4.4.5:
> 
> ```js
> const result = await strapi.query('plugin::i18n.locale').create({ data: { name: 'German (de)', code: 'de' }})
> ```
> 
> And it worked fine, for now I'll mark this one as closed but if someone runs into issues let me know and I can reopen

Running exactly the command you mentioned to add german locale in v4.11.7 throws the error. I don't believe this is solved.
```
ValidationError: [1] is not an existing permission action
    at handleYupError (/home/seg/modules/cms/node_modules/@strapi/admin/node_modules/@strapi/utils/lib/validators.js:67:9)
    at /home/seg/modules/cms/node_modules/@strapi/admin/node_modules/@strapi/utils/lib/validators.js:79:7
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.assignPermissions (/home/seg/modules/cms/node_modules/@strapi/admin/server/services/role.js:323:3)
    at async Object.syncSuperAdminPermissionsWithLocales (/home/seg/modules/cms/node_modules/@strapi/plugin-i18n/server/services/permissions/actions.js:95:3)
    at async Object.afterCreate (/home/seg/modules/cms/node_modules/@strapi/plugin-i18n/server/bootstrap.js:29:7)
    at async Object.run (/home/seg/modules/cms/node_modules/@strapi/database/lib/lifecycles/index.js:76:11)
    at async Object.create (/home/seg/modules/cms/node_modules/@strapi/database/lib/entity-manager/index.js:258:7)
    at async synchronizeLocales (/home/seg/modules/cms/packages/cms-plugin-core/lib/server/service/persistence/locale.js:26:9)
    at async initializeLocales (/home/seg/modules/cms/packages/cms-plugin-core/lib/server/bootstrap.js:41:5)
```

**Comment by sunnysonx** [comment]
No, it's still not solved. Not a big deal, but it seems that there create() and createMany() has different logica for the permissions which causes different behaviors
