### ISSUE TITLE
[documentation-plugin] "overrides" does not work

### ISSUE THREAD

**Issue by LukaszUrb** [strapi/strapi#12522]
### Describe the bug

Cannot replace documentation with "overrides" directory

### Steps to reproduce the behaviour 

Following the documentation, when you want to replace existing documentation you have to put file in "overrides" folder:

```
api
    my-api
        documentation
            documentationVersion // 1.0.0
                overrides // Folder to override the generated documentation
```

I have created a system entity and I want to replace response data model with file system.json placed in the right place: 
`src\api\system\documentation\1.0.0\overrides\system.json`

```
{
    "paths": {
      "/systems": {
        "get": {
          "deprecated": false,
          "description": "",
          "responses": {
            "200": {
              "description": "response",
              "content": {
                "application/json": {
                  "schema": {
                    "properties": {
                      "foo": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
```

There is no effect

### Expected behaviour

Documentation for get method for System should be replaced

### System

- Node.js version: v14.18.0
- NPM version: 6.14.15
- Strapi version: 4.0.1
- Database: Postgres
- Operating system: Windows

**Comment by derrickmehaffy** [comment]
fixed in: https://github.com/strapi/strapi/pull/12465

Should be out in the next release

**Comment by Felpat0** [comment]
@derrickmehaffy 
Actually this still doesn't work for me, isn't the fix only for the settings.json override?

**Comment by derrickmehaffy** [comment]
Reopening

**Comment by thucltzigvy** [comment]
This is my patch file. Try it
```diff --git a/node_modules/@strapi/plugin-documentation/server/services/documentation.js b/node_modules/@strapi/plugin-documentation/server/services/documentation.js
index 810b0be..d6a2479 100755
--- a/node_modules/@strapi/plugin-documentation/server/services/documentation.js
+++ b/node_modules/@strapi/plugin-documentation/server/services/documentation.js
@@ -138,6 +138,12 @@ module.exports = ({ strapi }) => {
         await fs.ensureFile(apiDocPath);
         await fs.writeJson(apiDocPath, apiPathsObject, { spaces: 2 });
 
+        // override api doc
+        const overridedApiDocPath = path.join(apiDirPath, 'overrides', `${apiName}.json`);
+        if (fs.existsSync(overridedApiDocPath)) {
+          apiPathsObject.paths = JSON.parse(fs.readFileSync(overridedApiDocPath, 'utf8')).paths;
+        }
+
         paths = { ...paths, ...apiPathsObject.paths };
       }
 
```

**Comment by elanizi43998** [comment]
Yes, I have the same issue, and I can't figure out the solution.

**Comment by markkaylor** [comment]
Hello thank you for reporting this. We are aware of the issue. I will be working on this soon.

**Comment by emiller12** [comment]
Hi @markkaylor , any updates on this one? 
I have just installed the documentation plugin into my project and can't seen to get the overrides to work for my custom controller functions at all.
It doesn't seem to pick up anything in `/src/api/<content-type>/documentation/1.0.0/overrides/<content-type>.json`

**Comment by markkaylor** [comment]
The overrides are still a WIP but a patch was put in place here: https://github.com/strapi/strapi/commit/573d56bc30af6b318f75928b8e07eee2e429e74d. It allows you to override components, paths, and tags. You can see how it is used in the users-permissions plugin.

**Comment by emiller12** [comment]
Great thanks, I'll check it out 👍

**Comment by reyalpsirc** [comment]
I created a patch using [patch-package](https://www.npmjs.com/package/patch-package) and following the solution of @thucltzigvy (adapted for version 4.4.5).

Install patch-package and @strapi/plugin-documentation@4.4.5

Place a file named "**@strapi+plugin-documentation+4.4.5.patch**" under a folder called "**patches**":

	diff --git a/node_modules/@strapi/plugin-documentation/server/services/documentation.js b/node_modules/@strapi/plugin-documentation/server/services/documentation.js
	index 564b8f5..39f60ca 100755
	--- a/node_modules/@strapi/plugin-documentation/server/services/documentation.js
	+++ b/node_modules/@strapi/plugin-documentation/server/services/documentation.js
	@@ -150,6 +150,12 @@ module.exports = ({ strapi }) => {
	 
	         await fs.ensureFile(apiDocPath);
	         await fs.writeJson(apiDocPath, apiPath, { spaces: 2 });
	+        // override api doc
	+        let extraPaths = {}
	+        const overridedApiDocPath = path.join(apiDirPath, 'overrides', `${apiName}.json`);
	+        if (fs.existsSync(overridedApiDocPath)) {
	+          extraPaths = JSON.parse(fs.readFileSync(overridedApiDocPath, 'utf8')).paths;
	+        }
	 
	         const componentSchema = buildComponentSchema(api);
	 
	@@ -158,7 +164,7 @@ module.exports = ({ strapi }) => {
	           ...componentSchema,
	         };
	 
	-        paths = { ...paths, ...apiPath };
	+        paths = { ...paths, ...apiPath, ...extraPaths };
	       }
	 
	       const fullDocJsonPath = path.join(

Add a postinstall script to your package.json to run patch-package whenever you do yarn install:

		"scripts": {
		  ...
		  "postinstall": "patch-package"
		},

Now run yarn install and the next time that you regenerate the documentation, it should work

**Comment by derrickmehaffy** [comment]
Updating and raising this as I believe it is impacting the upload plugin:

https://github.com/strapi/strapi/blob/5541a32440d5e3f58df27243e4dc1591654e388a/packages/core/upload/documentation/1.0.0/overrides/upload-File.json#L3-L100

![image](https://user-images.githubusercontent.com/8593673/201748795-ad3fb777-3483-4e4c-bd95-18b4a0ea7839.png)

**Comment by vixper** [comment]
I have the same problem on strapi 4.6.1.
Any update on this?

**Comment by rcdk** [comment]
So almost one year later and this is still not fixed :-( - Its so sad since a lot of our frontenders rely on our generated OpenAPI / Swagger docs to generate a strongly typed servicelayer - All this works everywhere else then here - Is there any chance you could find time to get this fixed in the near future ? :-)

**Comment by markkaylor** [comment]
A PR is currently open to address various issues related to the documentation plugin, including the overrides. I have created an experimental release if anyone would like to try it out.

```bash
0.0.0-experimental.4c2a2ca9c9e07bd22101abe79e583950609bb966
```

[The documentation](https://documentation-git-fix-docs-plugin-documentation-strapijs.vercel.app/dev-docs/plugins/documentation) for the plugin has also been updated.

Feedback is welcome, here are the PRs:
strapi/strapi: https://github.com/strapi/strapi/pull/16265
strapi/docs: https://github.com/strapi/documentation/pull/1622

**Comment by dassiorleando** [comment]
I still can't override my APIs using the documentation plugin.
I'm using **Strapi 4.20.0**, the latest as of today.

**Comment by dassiorleando** [comment]
@markkaylor, @Feranchz, @remidej  I still can't override my APIs using the documentation plugin.
I'm using **Strapi 4.20.0**, the latest as of today.
