### ISSUE TITLE
Pagination parameters not working in Users endpoint

### ISSUE THREAD

**Issue by redakzter01** [strapi/strapi#12911]
### Describe the bug

Hello, when i try to make a request to users endpoint with pagination parameters they get ignored.
I always get all the records.

### Steps to reproduce the behavior

GET /users?pagination[pageSize]=1
GET /users?pagination[limit]=1

Will always give the full amount of the table records. (Tried only with less of 100 hits)
I am also able to get the total count of the table with a GET request to /users/count

### System
Strapi 4.1.5, MySQL 8, Node 14.17, MacOS

**Comment by dubem-design** [comment]
Seems to be the same with when getting files
It just returns an array of the files

**Comment by derrickmehaffy** [comment]
@petersg83 I believe this relates to your message last week internally about plugins not following the same format as the content-api.

**Comment by riteshtailor2002** [comment]
Does anybody found the solution?

**Comment by ziayamin** [comment]
I have the same problem, Did anybody find the solution?

**Comment by derrickmehaffy** [comment]
I believe this should be fixed in v4.2.x+ if someone wants to confirm.

**Comment by digitaldesigndj** [comment]
I am still seeing this issue on `v4.3.0`

**Comment by jpcasa** [comment]
Yeah! Still seeing it too in `v4.3.0`.. PLEASE FIX! The user-permissions model has been all over the place in v4

**Comment by derrickmehaffy** [comment]
I can confirm that using the v4 pagination does not currently work. As a temporary workaround you can use the old v3 synatx (confirmed working) with `start=1&limit=1`

**Comment by Nikoxx99** [comment]
Still having the issue on 4.4.3
Anyone have news on this?

**Comment by gorden0929** [comment]
Strapi version: v4.5.2
Node: 16.18.1
GET /api/users?pagination[page]=1&pagination[pageSize]=25&sort=id:desc

Expected Response:
```
{
    data: [
        {
            "id": 1,
            "attributes": {
                "username": "abc",
                "email": "example@example.com",
                "provider": null,
                "confirmed": true,
                "blocked": false,
                "createdAt": "2022-11-23T05:20:25.905Z",
                "updatedAt": "2022-11-24T04:48:16.656Z",
                "name": null
            }
        }
    ],
    meta: {
        pagination: {
            "page": 1,
            "pageSize": 25,
            "pageCount": 3,
            "total": 54
        }
    }
}
```

Response: 
```
[
    {
        "id": 1,
        "username": "abc",
        "email": "example@example.com",
        "provider": null,
        "confirmed": true,
        "blocked": false,
        "createdAt": "2022-11-23T05:20:25.905Z",
        "updatedAt": "2022-11-24T04:48:16.656Z",
        "name": null
    }
]
```

**Comment by douglaschalegre** [comment]
On version 4.4.7, pagination parameters are not working.

What our team did was insert those with Entity Service API
https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/entity-service/order-pagination.html#pagination

We catch start and limit params via url and set on the entity service, the pagination behaves normal doing this

**Comment by molul** [comment]
> On version 4.4.7, pagination parameters are not working.
> 
> What our team did was insert those with Entity Service API https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/entity-service/order-pagination.html#pagination
> 
> We catch start and limit params via url and set on the entity service, the pagination behaves normally doing this

I'm interested on this. How does it work?

**Comment by douglaschalegre** [comment]
@molul Hey!

Here is a snippet of this applied to a controller retrieving news information
```js
export default factories.createCoreController(
  'api::noticia.noticia',
  ({ strapi }) => ({
      async find(ctx) {
      const { start, limit } = ctx.query?.pagination || {
        start: null,
        limit: null
      };
      const entries = await strapi.entityService.findMany(
        'api::noticia.noticia',
        {
          sort: { updatedAt: 'desc' },
          start,
          limit,
          filters: {
            publishedAt: {
              $ne: null
            }
          }
        }
      );
      const sanitizedEntity = await this.sanitizeOutput(entries, ctx);
      return sanitizedEntity;
    }
  })
);
```

This code is on the following path: src\api\noticia\controllers\news.ts
```
src
│   admin
│   components    
│   extensions
│   ...
└─── api
│   │   author
│   │   tag
│   │   ...
│   └─── news
│       │   content-types
│       │   middlewares
│       │   ...
│       └───  controllers
│       │   │   news.ts
```

As you can see, we catch start and limit params via url
```js
const { start, limit } = ctx.query?.pagination || {
        start: null,
        limit: null
      };
```
And then set on the entity service
```js
 const entries = await strapi.entityService.findMany(
        'api::noticia.noticia',
        {
          start,
          limit,
        }
      );
```

**Comment by molul** [comment]
I see. Thanks! However, how to use this with users? Inside /src/api I see all my collections except Users (for being internal, I guess).

**Comment by douglaschalegre** [comment]
@molul i think Users is not a collection available via api because it referees to internal users of strapi. Therefore your problem is not reletad to pagination.

**Comment by hubert-ix** [comment]
I'm currently reviewing Strapi to use as a back-end for a big community app, but things like this not being fixed after one year of being first mentioned is not very encouraging. For anyone building an app that needs to list users, this pagination issue is a major problem.

Are there any updates on when this can be expected to be fixed?

**Comment by molul** [comment]
I ended up separating User from Profile. User has username, email, password and some other requested fields, and Profile has other fields like country, city, date of birth... And it also has the username (not a big fan of duplicating content, but this way I can have pagination).

**Comment by hubert-ix** [comment]
> I ended up separating User from Profile. User has username, email, password and some other requested fields, and Profile has other fields like country, city, date of birth... And it also has the username (not a big fan of duplicating content, but this way I can have pagination).

Thanks, that makes sense as a workaround.

I have to say though that seeing issues like these for such as common task is making us think twice about using Strapi.

**Comment by myesn** [comment]
any updates?

**Comment by ducviet321** [comment]
It's 4.9.1 and yet still not fixed

**Comment by adishare** [comment]
I write a temporary workaround by extending the users-permissions plugin
`Strapi V 4.9.0`
> src/extensions/users-permissions/strapi-server.js

    const {
        getPaginationInfo,
        transformPaginationResponse,
    } = require("@strapi/strapi/lib/core-api/service/pagination");
    const utils = require("@strapi/utils");

    module.exports = (plugin) => {
    
        plugin.controllers.user.find = async (ctx) => {
            const uid = "plugin::users-permissions.user";
            const { pagination = {}, ...restOfCtxQueries } = ctx.query;
            const params = { ...restOfCtxQueries, ...pagination };
            const query = utils.convertQueryParams.transformParamsToQuery(
                uid,
                params
            );

            const [users, count] = await strapi.db.query(uid).findWithCount(query);

            const paginationInfo = getPaginationInfo(ctx.query);
            const paginationResult = transformPaginationResponse(
                paginationInfo,
                count
            );

            ctx.body = {
                data: users,
                meta: {
                    pagination: paginationResult,
                },
            };
        };

        
        return plugin;
    };

I believe that a fix for this feature would benefit the Strapi community as a whole and make the platform even more robust and user-friendly. look forward to seeing this issue resolved soon.

**Comment by Marc-Roig** [comment]
hello , I agree that this should be the default behaviour of this endpoint but to add pagination we would require to break the endpoint response contract, which we should not do in the v4 major version.

Right now we have:

```ts
Array<Users>
```

To add pagination:
```ts
data: Array<Users>
meta: {
  pagination: {
     total: number,
	page: number
	pageSize: number
}
}
```

what do you think could be a good compromise here that could fit your needs?

Also, @adishare , I would recommend you to sanitize the input and output of the endpoint, to not expose sensitive information. That can be achieved by using `sanitizeQuery` and `sanitizeOutput`, an example:
```js
  async find(ctx) {
    const sanitizedQuery = await sanitizeQuery(ctx.query, ctx);
    const users = await getService('user').fetchAll(sanitizedQuery);

    ctx.body = await Promise.all(users.map((user) => sanitizeOutput(user, ctx)));
  },
  ```

**Comment by ssshammi** [comment]
> I write a temporary workaround by extending the users-permissions plugin `Strapi V 4.9.0`
> 
> > src/extensions/users-permissions/strapi-server.js
> 
> ```
> const {
>     getPaginationInfo,
>     transformPaginationResponse,
>     convertPagedToStartLimit,
> } = require("@strapi/strapi/lib/core-api/service/pagination");
> const utils = require("@strapi/utils");
> const { sanitize } = utils;
> 
> const sanitizeQuery = async (query, ctx) => {
>     const schema = strapi.getModel("plugin::users-permissions.user");
>     const { auth } = ctx.state;
> 
>     return sanitize.contentAPI.query(query, schema, { auth });
> };
> 
> const sanitizeOutput = async (user, ctx) => {
>     const schema = strapi.getModel("plugin::users-permissions.user");
>     const { auth } = ctx.state;
> 
>     return sanitize.contentAPI.output(user, schema, { auth });
> };
> 
> module.exports = (plugin) => {
> 
>     plugin.controllers.user.find = async (ctx) => {
>         const uid = "plugin::users-permissions.user";
>         const sanitizedQuery = await sanitizeQuery(ctx.query, ctx);
>         const { pagination = {}, ...restOfCtxQueries } = sanitizedQuery;
>         const queryPagination = convertPagedToStartLimit(pagination);
>         const params = { ...restOfCtxQueries, ...queryPagination };
>         const query = utils.convertQueryParams.transformParamsToQuery(
>             uid,
>             params
>         );
> 
>         const [users, count] = await strapi.db.query(uid).findWithCount(query);
> 
>         const paginationInfo = getPaginationInfo(sanitizedQuery);
>         const paginationResult = transformPaginationResponse(
>             paginationInfo,
>             count
>         );
> 
>         let data = await Promise.all(
>             users.map((user) => sanitizeOutput(user, ctx))
>         );
> 
>         ctx.body = {
>             data: data,
>             meta: {
>                 pagination: paginationResult,
>             },
>         };
>     };
> 
>     return plugin;
> };
> ```
> 
> I believe that a fix for this feature would benefit the Strapi community as a whole and make the platform even more robust and user-friendly. look forward to seeing this issue resolved soon.
> 
> thanks to @Marc-Roig , this extended code is now able to handle my needs

Hello ,

My code is bit different. 

![image](https://user-images.githubusercontent.com/2300969/235125036-657a6e32-6e8a-4285-a450-7e4472d5f564.png)
` plugin.controllers.user.me = async (ctx) => {
  if (!ctx.state.user) {
      return ctx.unauthorized();
    }
    const user = await strapi.entityService.findOne(
      'plugin::users-permissions.user',
      ctx.state.user.id,
      { populate: ['role','displaypic'] }
    );

    ctx.body = sanitizeOutput(user);
  };
  
  plugin.controllers.user.findOne = async (ctx) => {
   const { id } = ctx.params.id;
   console.log("params "+ctx.params.id);
    const user = await strapi.entityService.findOne(
      'plugin::users-permissions.user',
		ctx.params.id,
       {populate: ['role','displaypic'] }
    );

    ctx.body = sanitizeOutput(user);
  };
  
  //plugin.controllers.auth.callback

  plugin.controllers.user.find = async (ctx) => {
    const users = await strapi.entityService.findMany(
      'plugin::users-permissions.user',
      { ...ctx.params, populate: ['role','displaypic'] }
    );

    ctx.body = users.map(user => sanitizeOutput(user));
  };

  return plugin;
}`

how to i modify this to add pagination ?

**Comment by ssshammi** [comment]
I modified it like so 

`    ctx.body = {
      data: users.map(user => sanitizeOutput(user)),
      meta: {
          pagination: paginationResult,
      },
   };`

**Comment by adishare** [comment]
yes @ssshammi , and as far as I know, the Strapi entity service findMany does not include users count returned CMIIW. To achieve this, I have found that using database query findWithCount and other Strapi core and utility pagination functions can be useful.

**Comment by augustocmarinho-tlf** [comment]
This snipped does not work to me at the strapi v4.2.0

I make  a change that works, but i don't know if this is the correct way.

\src\extensions\users-permissions\strapi-server.js
```plaintext
const {
    getPaginationInfo,
    transformPaginationResponse,
    convertPagedToStartLimit
} = require("@strapi/strapi/lib/core-api/service/pagination");
const { sanitize } = require('@strapi/utils')
const { contentAPI } = sanitize;
const uid = "plugin::users-permissions.user";

const sanitizeQuery = async (ctx) => {
    const contentType = strapi.contentType(uid)
    return await contentAPI.input(ctx.query, contentType, ctx.state.auth)
};

const sanitizeOutput = async (user, ctx) => {
    const schema = strapi.getModel(uid);
    const { auth } = ctx.state;

    return sanitize.contentAPI.output(user, schema, { auth });
};

module.exports = (plugin) => {

    plugin.controllers.user.find = async (ctx) => {
        const sanitizedQuery = await sanitizeQuery(ctx);
        const { pagination = {}, ...restOfCtxQueries } = sanitizedQuery;

        const queryPagination = convertPagedToStartLimit(pagination);

        const params = {
            ...restOfCtxQueries,
            limit: queryPagination.limit,
            offset: queryPagination.start
        };

        const [users, count] = await strapi.db.query(uid).findWithCount(params);
        const paginationInfo = getPaginationInfo(sanitizedQuery);
        const paginationResult = transformPaginationResponse(
            paginationInfo,
            count
        );

        let data = await Promise.all(
            users.map((user) => sanitizeOutput(user, ctx))
        );

        ctx.body = {
            data: data,
            meta: {
                pagination: paginationResult,
            },
        };
    };

    return plugin;
};
```

**Comment by MichaelEvtushenko** [comment]
The code above does NOT work, resulting with the error `error: Populate must be an object`.

**Comment by Angel-Morales-R** [comment]
> This snipped does not work to me at the strapi v4.2.0
> 
> I make a change that works, but i don't know if this is the correct way.
> 
> \src\extensions\users-permissions\strapi-server.js
> 
> ```
> const {
>     getPaginationInfo,
>     transformPaginationResponse,
>     convertPagedToStartLimit
> } = require("@strapi/strapi/lib/core-api/service/pagination");
> const { sanitize } = require('@strapi/utils')
> const { contentAPI } = sanitize;
> const uid = "plugin::users-permissions.user";
> 
> const sanitizeQuery = async (ctx) => {
>     const contentType = strapi.contentType(uid)
>     return await contentAPI.input(ctx.query, contentType, ctx.state.auth)
> };
> 
> const sanitizeOutput = async (user, ctx) => {
>     const schema = strapi.getModel(uid);
>     const { auth } = ctx.state;
> 
>     return sanitize.contentAPI.output(user, schema, { auth });
> };
> 
> module.exports = (plugin) => {
> 
>     plugin.controllers.user.find = async (ctx) => {
>         const sanitizedQuery = await sanitizeQuery(ctx);
>         const { pagination = {}, ...restOfCtxQueries } = sanitizedQuery;
> 
>         const queryPagination = convertPagedToStartLimit(pagination);
> 
>         const params = {
>             ...restOfCtxQueries,
>             limit: queryPagination.limit,
>             offset: queryPagination.start
>         };
> 
>         const [users, count] = await strapi.db.query(uid).findWithCount(params);
>         const paginationInfo = getPaginationInfo(sanitizedQuery);
>         const paginationResult = transformPaginationResponse(
>             paginationInfo,
>             count
>         );
> 
>         let data = await Promise.all(
>             users.map((user) => sanitizeOutput(user, ctx))
>         );
> 
>         ctx.body = {
>             data: data,
>             meta: {
>                 pagination: paginationResult,
>             },
>         };
>     };
> 
>     return plugin;
> };
> ```

Good work

**Comment by adishare** [comment]
However, the temporary workaround no longer seems to work in the recent version. 
seems like "@strapi/strapi/lib/core-api/service/pagination" not exported
Could someone please guide me on the correct way to import and use the pagination function of core-api in the latest version?
@Marc-Roig

**Comment by romeonuen** [comment]
Another worked solution for strapi 4.15.5
\src\extensions\users-permissions\strapi-server.js
```javascript
module.exports = (plugin) => {
  plugin.controllers.user.find = async (ctx) => {
      const schema = strapi.getModel('plugin::users-permissions.user');
      const { auth } = ctx.state;
      await validate.contentAPI.query(ctx.query, schema, { auth });
  
      let sanitizedQueryParams = await sanitize.contentAPI.query(ctx.query, schema, { auth });
      //cheating here, because currently user findPage only accept page & pageSize, not pagination object.
      sanitizedQueryParams = { ...sanitizedQueryParams, ...sanitizedQueryParams.pagination as Record<string, unknown> };
      const { results, pagination } = await strapi.entityService.findPage('plugin::users-permissions.user', sanitizedQueryParams);
      const users = await Promise.all(results.map((user) => sanitize.contentAPI.output(user, schema, { auth })));
      ctx.body = {
        data: users,
        meta: {
          pagination: pagination,
        },
      };
    };
  return plugin;
}
```

**Comment by adishare** [comment]
> @adishare Another worked solution for strapi 4.15.5 \src\extensions\users-permissions\strapi-server.js
> 
> ```js
> module.exports = (plugin) => {
>   plugin.controllers.user.find = async (ctx) => {
>       const schema = strapi.getModel('plugin::users-permissions.user');
>       const { auth } = ctx.state;
>       await validate.contentAPI.query(ctx.query, schema, { auth });
>   
>       let sanitizedQueryParams = await sanitize.contentAPI.query(ctx.query, schema, { auth });
>       //cheating here, because currently user findPage only accept page & pageSize, not pagination object.
>       sanitizedQueryParams = { ...sanitizedQueryParams, ...sanitizedQueryParams.pagination as Record<string, unknown> };
>       const { results, pagination } = await strapi.entityService.findPage('plugin::users-permissions.user', sanitizedQueryParams);
>       const users = await Promise.all(results.map((user) => sanitize.contentAPI.output(user, schema, { auth })));
>       ctx.body = {
>         data: users,
>         meta: {
>           pagination: pagination,
>         },
>       };
>     };
>   return plugin;
> }
> ```

thank you @romeonuen really help me for strapi 4.15.5
idk but pagination object work for me

`   plugin.controllers.user.find = async (ctx) => {
        const schema = strapi.getModel("plugin::users-permissions.user");
        const { auth } = ctx.state;
        await utils.validate.contentAPI.query(ctx.query, schema, { auth });

        let sanitizedQueryParams = await sanitize.contentAPI.query(
            ctx.query,
            schema,
            { auth }
        );

        const { results, pagination } = await strapi.entityService.findPage(
            "plugin::users-permissions.user",
            sanitizedQueryParams
        );
        const users = await Promise.all(
            results.map((user) =>
                sanitize.contentAPI.output(user, schema, { auth })
            )
        );
        
        ctx.body = {
            data: users,
            meta: {
                pagination: pagination,
            },
        };
    };`

**Comment by jmfernandez-dev** [comment]
> ```js
>   plugin.controllers.user.find = async (ctx) => {
>       const schema = strapi.getModel('plugin::users-permissions.user');
>       const { auth } = ctx.state;
>       await validate.contentAPI.query(ctx.query, schema, { auth });
>   
>       let sanitizedQueryParams = await sanitize.contentAPI.query(ctx.query, schema, { auth });
>       //cheating here, because currently user findPage only accept page & pageSize, not pagination object.
>       sanitizedQueryParams = { ...sanitizedQueryParams, ...sanitizedQueryParams.pagination as Record<string, unknown> };
>       const { results, pagination } = await strapi.entityService.findPage('plugin::users-permissions.user', sanitizedQueryParams);
>       const users = await Promise.all(results.map((user) => sanitize.contentAPI.output(user, schema, { auth })));
>       ctx.body = {
>         data: users,
>         meta: {
>           pagination: pagination,
>         },
>       };
>     };
> ```

This solution is perfect, it seems incredible that strapi no longer has support for user pagination. Thank you

**Comment by vitalijalbu** [comment]
> This snipped does not work to me at the strapi v4.2.0
> 
> I make a change that works, but i don't know if this is the correct way.
> 
> \src\extensions\users-permissions\strapi-server.js
> 
> ```
> const {
>     getPaginationInfo,
>     transformPaginationResponse,
>     convertPagedToStartLimit
> } = require("@strapi/strapi/lib/core-api/service/pagination");
> const { sanitize } = require('@strapi/utils')
> const { contentAPI } = sanitize;
> const uid = "plugin::users-permissions.user";
> 
> const sanitizeQuery = async (ctx) => {
>     const contentType = strapi.contentType(uid)
>     return await contentAPI.input(ctx.query, contentType, ctx.state.auth)
> };
> 
> const sanitizeOutput = async (user, ctx) => {
>     const schema = strapi.getModel(uid);
>     const { auth } = ctx.state;
> 
>     return sanitize.contentAPI.output(user, schema, { auth });
> };
> 
> module.exports = (plugin) => {
> 
>     plugin.controllers.user.find = async (ctx) => {
>         const sanitizedQuery = await sanitizeQuery(ctx);
>         const { pagination = {}, ...restOfCtxQueries } = sanitizedQuery;
> 
>         const queryPagination = convertPagedToStartLimit(pagination);
> 
>         const params = {
>             ...restOfCtxQueries,
>             limit: queryPagination.limit,
>             offset: queryPagination.start
>         };
> 
>         const [users, count] = await strapi.db.query(uid).findWithCount(params);
>         const paginationInfo = getPaginationInfo(sanitizedQuery);
>         const paginationResult = transformPaginationResponse(
>             paginationInfo,
>             count
>         );
> 
>         let data = await Promise.all(
>             users.map((user) => sanitizeOutput(user, ctx))
>         );
> 
>         ctx.body = {
>             data: data,
>             meta: {
>                 pagination: paginationResult,
>             },
>         };
>     };
> 
>     return plugin;
> };
> ```

that works in v5 as well??

**Comment by vitalijalbu** [comment]
> > ```js
> >   plugin.controllers.user.find = async (ctx) => {
> >       const schema = strapi.getModel('plugin::users-permissions.user');
> >       const { auth } = ctx.state;
> >       await validate.contentAPI.query(ctx.query, schema, { auth });
> >   
> >       let sanitizedQueryParams = await sanitize.contentAPI.query(ctx.query, schema, { auth });
> >       //cheating here, because currently user findPage only accept page & pageSize, not pagination object.
> >       sanitizedQueryParams = { ...sanitizedQueryParams, ...sanitizedQueryParams.pagination as Record<string, unknown> };
> >       const { results, pagination } = await strapi.entityService.findPage('plugin::users-permissions.user', sanitizedQueryParams);
> >       const users = await Promise.all(results.map((user) => sanitize.contentAPI.output(user, schema, { auth })));
> >       ctx.body = {
> >         data: users,
> >         meta: {
> >           pagination: pagination,
> >         },
> >       };
> >     };
> > ```
> 
> This solution is perfect, it seems incredible that strapi no longer has support for user pagination. Thank you

validate is not found in v5

**Comment by skywalker282** [comment]
Please this trans-version bug still make us wonder on every version change, how to handle pagination for the user-permissions plugin's users model. @derrickmehaffy @Marc-Roig any insights on this ?

**Comment by hsensh** [comment]
> > > plugin.controllers.user.find = async (ctx) => {
> > >       const schema = strapi.getModel('plugin::users-permissions.user');
> > >       const { auth } = ctx.state;
> > >       await validate.contentAPI.query(ctx.query, schema, { auth });
> > >   
> > >       let sanitizedQueryParams = await sanitize.contentAPI.query(ctx.query, schema, { auth });
> > >       //cheating here, because currently user findPage only accept page & pageSize, not pagination object.
> > >       sanitizedQueryParams = { ...sanitizedQueryParams, ...sanitizedQueryParams.pagination as Record<string, unknown> };
> > >       const { results, pagination } = await strapi.entityService.findPage('plugin::users-permissions.user', sanitizedQueryParams);
> > >       const users = await Promise.all(results.map((user) => sanitize.contentAPI.output(user, schema, { auth })));
> > >       ctx.body = {
> > >         data: users,
> > >         meta: {
> > >           pagination: pagination,
> > >         },
> > >       };
> > >     };
> > 
> > 
> > This solution is perfect, it seems incredible that strapi no longer has support for user pagination. Thank you
> 
> validate is not found in v5
```
async find(ctx) {
      const schema = strapi.getModel('plugin::users-permissions.user');
      const { auth } = ctx.state;
      await strapi.contentAPI.validate.query(ctx.query, schema, { auth });
  
      let sanitizedQueryParams = await strapi.contentAPI.sanitize.query(ctx.query, schema, { auth });
      //cheating here, because currently user findPage only accept page & pageSize, not pagination object.
      sanitizedQueryParams = { ...sanitizedQueryParams, ...sanitizedQueryParams.pagination as Record<string, unknown> };
      const { results, pagination } = await strapi.entityService.findPage('plugin::users-permissions.user', sanitizedQueryParams);
      const users = await Promise.all(results.map((user) => strapi.contentAPI.sanitize.output(user, schema, { auth })));
      ctx.body = {
        data: users,
        meta: {
          pagination: pagination,
        },
      };
    };
```

Updated version, although findPage is deprecated and there is no alternative. They say in the [docs](https://docs.strapi.io/dev-docs/migration/v4-to-v5/breaking-changes/no-find-page-in-document-service) we should use findMany instead, except findMany does not return the pagination object, so it seems we need to do the calculation manually.

Not a well-thought out release, as version 4 was not a thought-out release either. I have the same complaints since v3, they have their priorities focused on Strapi cloud they ignored the very messy core of the system itself. Quite a shame.

**Comment by ihor-zinchenko** [comment]
One more solution

!!!!!!!!!!! **Do not use**
``` 
populate: {
  role: {
    populate: '*',
  },
}
```
It will brake BE when you will have a lot of data.


Solution:

```
const { page = 1, pageSize = 10 } = ctx.query;
const limit = parseInt(pageSize, 10) || 10;
const offset = (parseInt(page, 10) - 1) * limit;

const sanitizedQueryParams: any = await sanitize.contentAPI.query(
  ctx.query,
  schema,
  { auth },
);

const where = {
  ...sanitizedQueryParams.filters,
};

const users = await strapi.db
  .query('plugin::users-permissions.user')
  .findMany({
    where,
    offset,
    limit,
    populate: {
      role: true,
    },
  });

const total = await strapi.db
  .query('plugin::users-permissions.user')
  .count({ where });

const data = users.map((user) => sanitizeOutput(user, ctx));

ctx.body = {
  data,
  meta: {
    pagination: {
      page: parseInt(page, 10),
      pageSize: limit,
      pageCount: Math.ceil(total / limit),
      total,
    },
  },
};
`

**Comment by mo9a7i** [comment]
v5
```typescript
// ./src/extensions/users-permissions/strapi-server.ts

export default (plugin: any) => {
    plugin.controllers.user.find = async (ctx) => {
      const { query } = ctx;
      
      // Extract pagination parameters with Strapi v5 defaults
      const { page = 1, pageSize = 25, start, limit } = query;
      
      // Build the query options using Strapi v5 format
      const queryOptions = {
        ...query,
        pagination: {
          pageSize: parseInt(String(pageSize)),
          page: parseInt(String(page)),
          // Support both page/pageSize and start/limit
          ...(start !== undefined && limit !== undefined ? { start, limit } : {})
        }
      };
  
      try {
        // Use entityService for consistent behavior
        const { results, pagination } = await strapi.entityService.findPage('plugin::users-permissions.user', queryOptions);
  
        // Sanitize users for response
        const sanitizedUsers = results.map(user => {
          const { password, resetPasswordToken, confirmationToken, ...sanitizedUser } = user;
          return sanitizedUser;
        });
  
        // Return in Strapi v5's standard format
        ctx.body = {
          data: sanitizedUsers,
          meta: {
            pagination: {
              page: pagination.page,
              pageSize: pagination.pageSize,
              pageCount: pagination.pageCount,
              total: pagination.total
            }
          }
        };
      } catch (error) {
        ctx.throw(500, error);
      }
    };
  
    return plugin;
  };
```

**Comment by h1km4t1ll0** [comment]
plugin-users-permissions: 4.20.4
strapi: 4.20.4
node: 18.18.0
typescript: 4.9.5

I used the code provided by @augustocmarinho-tlf but an error occurred: `Package subpath './dist/core-api/service/pagination' is not defined by "exports"`

Solution: patch file /node_modules/@strapi/strapi/package.json,
add the following lines: 

`"./dist/core-api/service/pagination": {
      "types": "./dist/core-api/service/pagination.d.ts",
      "source": "./dist/core-api/service/pagination.ts",
      "import": "./dist/core-api/service/pagination.mjs",
      "require": "./dist/core-api/service/pagination.js",
      "default": "./dist/core-api/service/pagination.js"
    },`

**Comment by fl034** [comment]
> Actually, seems like the old `?start=value&limit=value` is working in v5.4.2

Thanks for mentioning this. I can use this as a workaround, but it's hard to believe that this is not being fixed after being open for 3 years.
As a mobile developer, I'm afraid I can't assist with a pull request.

@derrickmehaffy can you increase the bug severity here?

**Comment by coderdix24** [comment]
im getting this issue as well for a basic content type
