### ISSUE TITLE
Unable to set a custom logo with enterprise version

### ISSUE THREAD

**Issue by fingeg** [strapi/strapi#13762]
## Bug report
When trying to save the settings page after uploading a custom logo, the admin console simply gives a popup with `Warning: An error occurred` and the logo did not get updated, there are no error messages in either the browser of the strapi console, but a failed POST request. More details are below.

### Required System information

- Node.js version: 16.13.0
- NPM version: 8.1.0
- Strapi version: 4.3.0-beta.2 (enterprise)
- Database: PostgreSQL
- Operating system: Ubuntu

### Describe the bug

There are no error messages in either the browser or the strapi console, but a failed post request to `/admin/project-settings`.
I could trace back the error to the following lines:
https://github.com/strapi/strapi/blob/e2b48c6aef8bb966b1cf6efd199d804b72581356/packages/core/admin/server/controllers/admin.js#L79
and then within that function
https://github.com/strapi/strapi/blob/e2b48c6aef8bb966b1cf6efd199d804b72581356/packages/core/utils/lib/validators.js#L80
but don't really understand why it's not working.

The message in the response of the post request is:
```
message: "menuLogo  must be a `object` type, but the final value was: `{\n  \"width\":  \"750\",\n  \"height\": \"750\",\n  \"stream\": {\n    \"fd\":  \"null\",\n    \"path\":  \"\\\"/tmp/upload_bd0982d854ebbc0e8f17d9d5af241704\\\"\",\n     \"flags\": \"\\\"r\\\"\",\n    \"mode\": \"438\",\n    \"start\":  \"undefined\",\n    \"end\": \"Infinity\",\n    \"pos\":  \"undefined\",\n    \"bytesRead\": \"0\",\n    \"closed\": \"false\",\n     \"_readableState\": {\n      \"objectMode\": \"false\",\n       \"highWaterMark\": \"65…loseEmitted\": \"false\",\n       \"defaultEncoding\": \"\\\"utf8\\\"\",\n      \"awaitDrainWriters\":  \"null\",\n      \"multiAwaitDrain\": \"false\",\n      \"readingMore\":  \"false\",\n      \"dataEmitted\": \"false\",\n      \"decoder\":  \"null\",\n      \"encoding\": \"null\"\n    },\n    \"_events\": {},\n     \"_eventsCount\": \"1\",\n    \"_maxListeners\": \"undefined\"\n   },\n  \"tmpPath\":  \"\\\"/tmp/upload_bd0982d854ebbc0e8f17d9d5af241704\\\"\",\n   \"provider\": \"\\\"restricted-access\\\"\"\n}`.
```

as you can see in the error message, I'm using a custom provider, but tried the same thing with default local provider and that did not work either.

Thanks in advance

### Steps to reproduce the behavior

1. Go to 'settings'
2. Upload a custom logo
3. click save
4. See the error message on the website

### Expected behavior

Just save the page and update the logo everywhere

**Comment by gildonei** [comment]
I have this same issue

**Comment by guolin** [comment]
same with me

**Comment by ronronscelestes** [comment]
thank you for highlighting this issue, the fix should be merged and released for tomorrow :)

**Comment by OCLi** [comment]
Same with me

STRAPI VERSION v4.5.5 
NODE VERSION v18.12.1

**Comment by OCLi** [comment]
Same with me

STRAPI VERSION v4.5.5
NODE VERSION v18.12.1

**Comment by Flowko** [comment]
facing the same issue, any news about this ?

**Comment by ronak-betaflux** [comment]
Yes plase fix for strapi v4.5.6 and node version 16.3.0

**Comment by derrickmehaffy** [comment]
Was fixed in v4.6.0

**Comment by spoilerdo** [comment]
For me it is still not working even with v4.6.0 (node 18). Are you sure it is really fixed?

**Comment by FranckL01** [comment]
Facing the same issue
Strapi community ; v4.6.1
node v16.13

**Comment by derrickmehaffy** [comment]
Tested on v4.6.1:

![image](https://user-images.githubusercontent.com/8593673/219449654-6818cef6-5305-4975-a4bc-b5819962bbae.png)
![image](https://user-images.githubusercontent.com/8593673/219449675-13cf0f8a-0e67-409b-beb8-82473ae03b64.png)

**Comment by FranckL01** [comment]
Fixed it, the problem was in my config file / upload.
