### ISSUE TITLE
Cannot change Dashboard logo in v4.5.5

### ISSUE THREAD

**Issue by WebShapedBiz** [strapi/strapi#15318]
### Required System information

- Node.js version: 16.13.1
- NPM version: 8.19.2
- Strapi version: 4.5.5
- Database: Postgres
- Operating system: elementaryOS 6.1 (Ubuntu 20.04 based distro)

### Describe the bug

Hi,
Using Strapi v4.5.5 when I try to change the logo (png file that I've used before) I receive `Warning: An error occurred` message in the Dashboard and in the terminal I get `error: Cannot read properties of undefined (reading 'menuLogo')`

### Steps to reproduce the behavior

1. Go to 'Settings'
2. In the Customization section, Logo, click on the `+` sign to change the logo
3. Select and upload the new logo file
4. The new logo is immediately shown in the Customization section as a preview, so that's working
5. Clicking `Save` displays  `Warning: An error occurred` 

### Expected behavior

To be able to change the logo

### Screenshots

[A screencast of the issue](https://watch.screencastify.com/v/iz2ZYEGo5cX3F40VlBfb
)

Cheers.

**Comment by simonwidjaja** [comment]
Same here. Double checked and I can reproduce the error with a fresh install of Strapi (4.5.5).
I get the same warning in the UI but no error in the terminal.
The new logo is briefly shown in the upload preview section. After the warning nothing happens and the blue strapi logo still remains.

**Comment by simonwidjaja** [comment]
FYI: I successfully changed the logo (and admin title and subtitle) using the config file (src/admin/app.tsx).

<img width="606" alt="image" src="https://user-images.githubusercontent.com/1757398/210337062-3e4a228f-eca1-4c69-84b4-2d752b46e51c.png">

**Comment by WebShapedBiz** [comment]
Thank you @simonwidjaja for this

**Comment by anuragsharanjuspay** [comment]
Facing the same issue, the menuLogo being sent in the request is `{}` 

<img width="354" alt="Screenshot 2023-01-06 at 1 04 20 PM" src="https://user-images.githubusercontent.com/110665830/210952696-11c48f90-3808-43d3-b677-026586e929c1.png">

**Comment by n3b0r** [comment]
Same issue here.

**Comment by eucciferri** [comment]
Same issue here!

**Comment by derrickmehaffy** [comment]
Reproducible on v4.5.6, Admin API responds with:

```json
{
  "data": null,
  "error": {
    "status": 400,
    "name": "ValidationError",
    "message": "menuLogo must be a `string` type, but the final value was: `{}`.",
    "details": {
      "errors": [
        {
          "path": ["menuLogo"],
          "message": "menuLogo must be a `string` type, but the final value was: `{}`.",
          "name": "ValidationError"
        }
      ]
    }
  }
}
```

From the URL: http://localhost:1337/admin/project-settings

**Comment by joshwcorbett** [comment]
Still dealing with this issue in `4.5.6`

**Comment by ronronscelestes** [comment]
hi, thank you everyone for reporting this issue 🙂
this should be fixed by [this PR](https://github.com/strapi/strapi/pull/15096) and released today!

**Comment by derrickmehaffy** [comment]
Closing as should be fixed in v4.6.0 that was released yesterday

**Comment by Cohvir** [comment]
As of today, this issue is still present.

![image](https://github.com/user-attachments/assets/c6b9c99b-bcd1-4cb2-9f3a-cd831043e015)
