### ISSUE TITLE
Repeatable components with relationship type fields will be messed up after dragging to change the order

### ISSUE THREAD

**Issue by Frully** [strapi/strapi#15492]
### Required System information

- Node.js version: 18.12.1
- Strapi version: 4.5.6
- Database: MySQL 8.0.3.1
- Operating system: macOS 13.0.1

### Describe the bug

My collection type contains a repeatable component Field A and this component contains a one-way relation Field B.
Field A contains component1 and component2, When I adjust the order of component 1 and component 2, the field B of component 1 will appear the value of field B of component 1 and component 2, and the same for component 2.

### Steps to reproduce the behavior

1. Create collection type X
2. Add field A in X, whose type is repeatable component Y
3. Add field B in Y, whose type is a one-way relation
4. Save
5. Create a new entry for X
6. Set the values ​​of field A to component 1, component 2, and component 3, and set field B of the components to b1, b2, and b3 respectively
7. Save
8. Drag component 3 before component 1
9. An error occurs: the values ​​of field B of component 3 become b1 and b3, the values ​​of field B of component 1 become b2 and b1, and the values ​​of field B of component 2 become b3 and b2

### Expected behavior

After dragging the components, the order of the components changes, but the fields in the components do not change

### Screenshots

![WX20230119-113155@2x](https://user-images.githubusercontent.com/1008448/213349082-4ee8f955-940b-4a2a-b2b7-46dff34f5f3e.png)
Collection type

![WX20230119-111919@2x](https://user-images.githubusercontent.com/1008448/213349270-c3b6aac3-0d5c-477b-a178-2b62dc3df05f.png)
Before error

![WX20230119-113538@2x](https://user-images.githubusercontent.com/1008448/213349562-96fc1e27-539c-407b-9907-be70d7645a2f.png)
After error

**Comment by joshuaellis** [comment]
Hey @Frully!

We're aware of this and I believe it should be fixed with the `4.6.0` release ~next week. In the meanwhile you could try the latest `4.6.0` beta as it should be solved on there, and if not let us know :)

**Comment by Frully** [comment]
> Hey @Frully!
> 
> We're aware of this and I believe it should be fixed with the `4.6.0` release ~next week. In the meanwhile you could try the latest `4.6.0` beta as it should be solved on there, and if not let us know :)

Hi @joshuaellis !
I updated Strapi to 4.6.0, but this bug still exists. Hope you guys can recheck this bug, thanks a lot.

**Comment by joshuaellis** [comment]
I can't reproduce this in 4.6.0 and I should have closed it with #15119 so i'm going to for now and if you can provide reproduction steps we can revisit.
