### ISSUE TITLE
Unable to run strapi build with pnpm

### ISSUE THREAD

**Issue by elliason** [strapi/strapi#15992]
Hello,
with following setup:
- Node.js version: 18.9.0
- NPM version: x
- Strapi version: 4.7.1
- Database: Postrgres
- Operating system: Ubuntu host / Docker node:18 Debian base standard image
- Is your project Javascript or Typescript: Typescrip

There is this bug:
If Strapi is installed in pnpm workspace (monorepo) running  "strapi build" causes issues with missing packages.
`Can't resolve 'lodash/merge' in '/var/www/html/application/apps/cms/.cache/admin/src'`
I assume this is probably due to indirect dependencies not available in pnpm. 
Is there some workaround ? Adding packages to .npmrc public-hoist-pattern[] does not seem to fix the issue.

Running "strapi develop" is without issues

**Comment by joshuaellis** [comment]
This was resolved in #15848 and should be released in `4.7.2`.

**Comment by elliason** [comment]
I tried today with `4.8.2` but getting another similar error: ```Can't resolve 'codemirror5/addon/display/placeholder'```
This seems not to be resolved.

**Comment by Eventyret** [comment]
@elliason could you please provide some more information on how you set up this project so I can try to reproduce it, please?

**Comment by elliason** [comment]
Sure. I am currently building a JAM stack template. The repo is here https://github.com/elliason/mf-next-boilerplate
The monorepo workspace root is in /application folder. The Strapi folder is in /application/backends/cms.
I was not able to include this folder in pnpm monorepo, so its excluded from workspace and run in isolation with yarn classic.
The application is meant to run inside docker containers, but it should run without problems without them on node>18.0

**Comment by Eventyret** [comment]
Thank you for your report @elliason 
So I was able to create a brand new strapi application using
`pnpx create-strapi-app`, so I would suggest you check your configuration etc., from the way you have set up your own project.

**Comment by elliason** [comment]
@Eventyret 
Yes, you can run `pnpx create-strapi-app` and it will provide with some setup but that does not mean its all working.
It certainly creates initial structure but my issue is about working app in pnpm monorepo. `pnpx create-strapi-app` does not even use pnpm, it creates package with yarn classic.
I have created a minimalistic example of Strapi in pnpm monorepo here: https://github.com/elliason/strapi-pnpm-example
There is strapi installed via `pnpx create-strapi-app` inside `/packages/strapi` folder.
Indeed initial installation is without problems, and so is running "strapi develop". But the problems starts when you need to change some settings in `/config` folder and rebuild the admin UI with "strapi build" - thats where problems starts to happen.

![image](https://user-images.githubusercontent.com/6887123/226385094-53a7c489-25d4-4cda-82ac-4190b0876ae6.png)

The messages are all about missing some modules. I suppose this is phantom dependency problem as some module is using indirect dependencies that are not specified in its package.json. While this might work in Yarn Classic or NPM, it is problem with PNPM and also some resolution modes of Yarn Berry.

**Comment by joshuaellis** [comment]
A workaround seems to be to do:

```yaml
shamefully-hoist=true
```

in an `.npmrc` file.

**Comment by emirotin** [comment]
@joshuaellis I'm having the same issue with pnpm monorepo
Strapi version is 4.9.0

Without the .npmrc config it doesn't build, same lodash/merge issue

_With_ the above-mentioned .npmrc, the admin builds, but when it launches, there's this error in the browser console: `Fn.sheet.hydrate is not a function`. To my understanding, it's coming from the `emotion` package, and indeed, if I try to debug it, the `sheet` object exists but doesn't have the `hydrate` method.

**Comment by emirotin** [comment]
Sorry, forgot to mention. It's completely blank :D

Let me try to create the minimal repro

**Comment by moweiwei** [comment]
您需要添加一个包含以下内容的 .npmrc 文件：

shamefully-hoist=true

**Comment by arantespp** [comment]
I don't know how good it is, but I removed Strapi from the workspace root and created a workspace just for it. Temporally, my monorepo has this configuration:

On the root:

```yml
# ~/root/pnpm-workspace.yaml
packages:
  - projects/**/*
  - '!projects/cms/strapi'
```

On the package:

```yml
# ~/root/projects/cms/strapi/pnpm-workspace.yaml
packages:
  - './'
```

and

```yml
# ~/root/projects/cms/strapi/.npmrc
shamefully-hoist=true
```

**Comment by JoshuaAlzate** [comment]
Adding `shamefully-hoist=true` in `.npmrc` works for me as well. But again, it is shameful.

**Comment by vKongv** [comment]
I am running latest strapi version `4.11.3` created using `pnpx create-strapi-app@latest my-project --ts` cli with a monorepo setup. It works great in my local but when my teammate trying to run the application locally, we are getting error from `tsconfig.json` saying `@strapi/typescript-utils/tsconfigs/server is not found`.

Turns out, when installing strapi using `pnpm i` of a monorepo setup, it doesn't install all the node_modules required as compared to `npm i` which is confusing. What can we do here if we still want to use monorepo with pnpm setup?

**Comment by mmiszy** [comment]
> ## SO, The workaround
> ### Webpack (if you're not using 4.9.0)
> In your app go to `src/admin/webpack.config.js` and ensure the function includes the line:
> 
> ```js
> config.resolve.mainFields = ["browser", "module", "jsnext:main", "main"];
> ```
> 
> So the file might look like this if you've not changed anything else:
> 
> ```js
> "use strict";
> 
> /* eslint-disable no-unused-vars */
> module.exports = (config) => {
>   // Note: we provide webpack above so you should not `require` it
>   // Perform customizations to webpack config
>   // Important: return the modified config
> 
>   config.resolve.mainFields = ["browser", "module", "jsnext:main", "main"];
> 
>   return config;
> };
> ```
> 
> This workaround won't be necessary for long as i'll open a PR to solve it.
> 
> ### Dependencies
> You'll need to add an `.npmrc` file that includes:
> 
> ```yaml
> shamefully-hoist=true
> ```
> 
> and then run `pnpm install` to make sure it works correctly. You should then be able to build the admin panel 🙏🏼

Following this allowed me to `pnpm build` without any errors, but unfortunately the admin panel is now broken. It throws an error on the client side:

```
Uncaught TypeError: (0 , o.default) is not a function
```

**Comment by langdonholmes** [comment]
> Following this allowed me to `pnpm build` without any errors, but unfortunately the admin panel is now broken. It throws an error on the client side:

Hello, I was able to solve this issue in my team's pnpm monorepo.

In addition to the above configuration to `strapi/src/admin/webpack.config.js`, I added some additional configuration to `.npmrc`:
```
node-linker=hoisted
shamefully-hoist=true
resolve-peers-from-workspace-root=true
```

In the root level `package.json` (see #16684) :
```
  "dependencies": {
    ...
    "path-to-regexp": "^1.7.0",
  },
  "pnpm": {
    "packageExtensions": {
      "react-router": {
        "dependencies": {
          "path-to-regexp": "^1.7.0"
        }
      }
    }
```

The above problem was caused by another package in our monorepo that installs Express. Express installs an old path-to-regexp, and react-router does not correctly specify a version range for path-to-regexp, so that dependency needs to be patched. This problem should be solved once Strapi bumps the `react-router` version that it depends upon. `react-router` >=6.0.0 does not depend on `path-to-regexp`.

**Comment by ainsleyclark** [comment]
Is there any updated on when Strapi will be supporting pnpm?

**Comment by joshuaellis** [comment]
I hope to support it by V5, when we introduce vite in V4 there's a chance we will solve the issues we're facing now – but i cannot guarantee this. ETA on Vite, I'd like to have it introduced before end of November...

**Comment by ainsleyclark** [comment]
Thanks @joshuaellis 
Is there any workaround for the time being?

**Comment by nandomoreirame** [comment]
Hello! Any developments at this point?

**Comment by derrickmehaffy** [comment]
Locking this, it'll come when it comes. For now it's not a priority but might happen due to other work as a side effect

**Comment by joshuaellis** [comment]
If someone is interested, this experimental might actually work with PNPM, at least it does locally for me – `0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336`

**Comment by joshuaellis** [comment]
Believe this should be solved in 4.15.4.

**Comment by jbhammon** [comment]
Just updated to 4.15.4, and I still have issues with some TS config files that come from Strapi. After installing deps with `pnpm`, in both my current project and a fresh one created with `npx create-strapi-app@latest my-project`, I see this error with the `develop` command.

```bash
ERROR in ./tsconfig.json
TS6053: File '@strapi/typescript-utils/tsconfigs/server' not found.
```

Seems like `pnpm` doesn't pull in the `typescript-utils` stuff under the `@strapi` namespace. I don't see it in `node_modules`.

I added the dependency manually, `pnpm add @strapi/typescript-utils`, and then the develop command was able to run and start the server. I'll try the build command a little later today. This could be just a small blocker for people with TS projects, I could open an issue to tackle it if that would be helpful.

**Comment by joshuaellis** [comment]
> I could open an issue to tackle it if that would be helpful.

Can you please? I think the solution going forward is probably ensuring this dep is added automatically when creating a new project in TS :)

**Comment by 4li-ra** [comment]
> Just updated to 4.15.4, and I still have issues with some TS config files that come from Strapi. After installing deps with `pnpm`, in both my current project and a fresh one created with `npx create-strapi-app@latest my-project`, I see this error with the `develop` command.
> 
> ```shell
> ERROR in ./tsconfig.json
> TS6053: File '@strapi/typescript-utils/tsconfigs/server' not found.
> ```
> 
> Seems like `pnpm` doesn't pull in the `typescript-utils` stuff under the `@strapi` namespace. I don't see it in `node_modules`.
> 
> I added the dependency manually, `pnpm add @strapi/typescript-utils`, and then the develop command was able to run and start the server. I'll try the build command a little later today. This could be just a small blocker for people with TS projects, I could open an issue to tackle it if that would be helpful.

 `pnpm add @strapi/typescript-utils` works for me, thank you for saving my day :)
