### ISSUE TITLE
Edit entry in Content Manager fails

### ISSUE THREAD

**Issue by reppard** [strapi/strapi#17457]
### Required System information

- Node.js version: 18.12.1
- NPM version: 8.19.2
- Strapi version: 4.11.5
- Database: postgres
- Operating system: Linux
- Is your project Javascript or Typescript: Javascript

### Describe the bug
While in the Content Manager in the admin portal, when I selected a content type, and then click an item row or edit icon, I receive an error prompt in the UI
> Woops! Something went wrong. Please, try again.

Console output:
```
main.3d752c03.js:709 TypeError: Cannot read properties of undefined (reading 'code')
    at Qi (main.3d752c03.js:408:3119)
    at Nf (main.3d752c03.js:707:20418)
    at Vd (main.3d752c03.js:709:44842)
    at lh (main.3d752c03.js:709:40485)
    at sh (main.3d752c03.js:709:40413)
    at Gf (main.3d752c03.js:709:40267)
    at rc (main.3d752c03.js:709:36550)
    at Ud (main.3d752c03.js:709:35489)
    at z (main.3d752c03.js:788:1648)
    at MessagePort._e (main.3d752c03.js:788:2029)

# Output after making webpack config change

react-dom.production.min.js:189 TypeError: Cannot read properties of undefined (reading 'code')
    at Wt (index.js:24:73)
    at fu (react-dom.production.min.js:167:137)
    at ff (react-dom.production.min.js:290:337)
    at cf (react-dom.production.min.js:280:389)
    at Cf (react-dom.production.min.js:280:320)
    at uf (react-dom.production.min.js:280:180)
    at sf (react-dom.production.min.js:271:88)
    at bf (react-dom.production.min.js:268:429)
    at z (scheduler.production.min.js:13:203)
    at MessagePort.Pe (scheduler.production.min.js:14:128)
```

Should be noted that this backend is being migrated from v3.x. This happens for all content types, even those with no custom routing or controller functions.

### Steps to reproduce the behavior

1. Login to admin panel
2. Click Content Manager
3. Select a Content Type (doesn't matter which)
4. Attempt to edit an entry

**Comment by gu-stav** [comment]
👋🏼 

Could you please update your webpack config in `src/admin` to enable sourcemaps:

```
module.exports = (config, webpack) => {
  // Note: we provide webpack above so you should not `require` it
  // Perform customizations to webpack config
  // Important: return the modified config
  config.devtool = 'source-map';
  return config;
};
```

Otherwise we don't have a chance to understand where your application broke. Also please make sure you provide reproduction steps.

**Comment by esraasaadyassir** [comment]
As I have done this migration two weeks ago and it was working fine
I'd say you can try to run "strapi build" it maybe give you more detailed info about the issues.
Also make sure to make sure you DB has been updated as mentioned [here](https://strapi.io/blog/how-to-migrate-from-strapi-v3-to-v4-walkthrough)

Also if you're using strapi seo make sure to update it to the latest version.
One last thing maybe you can try to delete those entries and try to fill it again and then try editing them.

**Comment by reppard** [comment]
> 👋🏼
> 
> Could you please update your webpack config in `src/admin/webpack.config.js` to enable sourcemaps:
> 
> ```
> module.exports = (config, webpack) => {
>   // Note: we provide webpack above so you should not `require` it
>   // Perform customizations to webpack config
>   // Important: return the modified config
>   config.devtool = 'source-map';
>   return config;
> };
> ```
> 
> Otherwise we don't have a chance to understand where your application broke. Also please make sure you provide reproduction steps.

Done, edited original issue. Looks like something is messed up with locale. I've got `@strapi/plugin-i18n": "4.11.5` set as a dev dependency in my package.json

**Comment by gu-stav** [comment]
> Done, edited original issue. Looks like something is messed up with locale. I've got @strapi/plugin-i18n": "4.11.5 set as a dev dependency in my package.json

I still can't see the origin of the error and the code is minified. Could you please delete the `.cache` and `build` folder too and re-run the build?

**Comment by reppard** [comment]
> Thanks!
> 
> > Done, edited original issue. Looks like something is messed up with locale. I've got @strapi/plugin-i18n": "4.11.5 set as a dev dependency in my package.json
> 
> I still can't see the origin of the error and the code is minified. Could you please delete the `.cache` and `build` folder too and re-run the build?

so... i did that. but i also removed plugin-i18n, built, re-added it, rebuilt, and now the error is gone

**Comment by gu-stav** [comment]
I'm glad. In case you can find out how to reproduce the issue, feel free to ping me in here and I will re-open it.

Thanks!

**Comment by reppard** [comment]
> I'm glad. In case you can find out how to reproduce the issue, feel free to ping me in here and I will re-open it.
> 
> Thanks!

will do. when i could drill down into (index.js:24:73) it was trying to set a default locale, which led me to looking at i18n. i appreciate the help.
