### ISSUE TITLE
x-generation-date gets updated every time the server is run/restarted

### ISSUE THREAD

**Issue by Nirajn2311** [strapi/strapi#17643]
## Bug report
`x-generation-date` property in the `full_documentation.json` file is always updated each time the server is run/restarted even if there is no other change in the json file or any other code file. This keeps messing with git and we have to keep reverting the change everytime.

### Required System information

- Node.js version: 18.17.0
- NPM version: 9.6.7
- Strapi version: 4.12.1
- Database: PostgreSQL
- Operating system: MacOS 
- Is your project Javascript or Typescript: Javascript

### Expected behavior

The `x-generation-date` property should be updated when a change or update to documentation happens.

### Screenshots

![image](https://github.com/strapi/strapi/assets/36357875/249dc95a-349f-4401-a6bb-55990c30400d)

**Comment by anneau** [comment]
same issue

**Comment by CodeWithMuzzu** [comment]
Hey @Nirajn2311 where did you check the x-generation-date output , I am currently working on this issue, how did you check the output. I am little confused where did you see that attribute output.

**Comment by anneau** [comment]
I also reproduce [get-start example](https://github.com/strapi/strapi/tree/main/examples/getstarted).

`full_documentation.json` is ignored in this example, but in my project want not to ignore.

**Comment by anneau** [comment]
[The same problem occurred before](https://github.com/strapi/strapi/issues/7509) and seemed to have been resolved at that time, but seems to have returned due to [this PR](https://github.com/strapi/strapi/commit/3e9731a2af470c43b20ad786b6828d7ec6704469#diff-50124e4d75eb8ca909e44460cabcf1f16a622f1e43a3eaa272d429cc019c61ebL67).

What is the official position that it is better not to generate files at startup in production environments, since writing files is prohibited in serverless environments, etc.?

**Comment by Red-Asuka** [comment]
This issue still exists in `"@strapi/plugin-documentation": "^4.23.0"`.

**Comment by wendelsantosd** [comment]
any update ?

**Comment by derrickmehaffy** [comment]
Locking this, at the moment we have no plans to work on this for the foreseeable future. While the docs plugin was migrated to Strapi 5, we have plans to depreciate during the Strapi 5 lifecycle as it'll be replaced by our own API explorer built directly into the admin.

The reason for this decision is we no longer  follow the Open API specification (including in Strapi 4), and have switched to the JSON API specification as of v4.0.0+.
