### ISSUE TITLE
Restarting strapi trying to add constraints everytime to _components tables

### ISSUE THREAD

**Issue by bilalgodesto** [strapi/strapi#17676]
### Required System information

- Node.js version:v16.20.0
- NPM version: 8.19.4
- Strapi version:4.12.4
- Database:postgres
- Operating system:mac
- Is your project Javascript or Typescript:Javascript

### Describe the bug

After upgrading strapi to latest version i am facing this issue when ever i try to restart strapi by adding some new field 
in components i am getting below error

```
error: alter table "salesforce"."account_landings_components" add constraint "account_landings_unique" unique ("entity_id", "component_id", "field", "component_type") - relation "account_landings_unique" already exists
    at Parser.parseErrorMessage (/Users/bilalrabbi/sites/ADMINS/STRAPI_APP/my_project/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/bilalrabbi/sites/ADMINS/STRAPI_APP/my_project/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/bilalrabbi/sites/ADMINS/STRAPI_APP/my_project/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/Users/bilalrabbi/sites/ADMINS/STRAPI_APP/my_project/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 105,
  severity: 'ERROR',
  code: '42P07',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'index.c',
  line: '864',
  routine: 'index_create'
}
```
This unique id with all tables ending with _components throws error

### Steps to reproduce the behavior

Using package.json below

```
{
  "name": "MyProject",
  "private": true,
  "version": "0.1.1",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^1.0.7",
    "@strapi/icons": "^1.9.0",
    "@strapi/plugin-graphql": "^4.12.4",
    "@strapi/plugin-i18n": "^4.12.4",
    "@strapi/plugin-users-permissions": "^4.12.4",
    "@strapi/provider-email-sendgrid": "^4.4.3",
    "@strapi/provider-upload-aws-s3": "^4.12.4",
    "@strapi/strapi": "^4.12.4",
    "chargebee": "^2.10.0",
    "cheerio": "^1.0.0-rc.11",
    "koa-static": "^5.0.0",
    "mime-types": "^2.1.35",
    "moment": "^2.29.3",
    "pg": "^8.11.2",
    "pg-connection-string": "^2.6.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "sanitize-filename": "^1.6.3",
    "strapi-plugin-measurement-protocol": "^1.0.1",
    "strapi-provider-email-smtp": "^1.0.3"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "23232-bad0-4fee-a674-da565a2a2b4c"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": "8.11.0"
  },
  "license": "MIT"
}


```

and database.js in config is

```


module.exports = ({ env }) => ({
  connection: {
    client: "postgres",
    connection: {
      host: env("DATABASE_HOST"),
      port: env.int("DATABASE_PORT", 5432),
      database: env("DATABASE_NAME"),
      user: env("DATABASE_USERNAME"),
      password: env("DATABASE_PASSWORD"),
      ssl:
      {
        rejectUnauthorized: false,
      },
      schema: env("DATABASE_SCHEMA"),
    },
    acquireConnectionTimeout: 600000,
    pool: {
      min: 2,
      max: 6,
      acquireTimeoutMillis: 300000,
      createTimeoutMillis: 300000,
      destroyTimeoutMillis: 50000,
      idleTimeoutMillis: 300000,
      reapIntervalMillis: 10000,
      createRetryIntervalMillis: 2000,
      propagateCreateError: false,
    },
    debug: false,
  },
  settings: {
    forceMigration: false,
    runMigrations: false,
  },
});



// force migration set to false 




```

### Expected behavior

There should be DROP IF EXISTS for constraints or Strapi should not create unique index every time

**Comment by derrickmehaffy** [comment]
This most likely is related to the recent PG schema issue. @bilalgodesto can you update to v4.12.5 and confirm if you are using a different PG schema than the default `public` one?

**Comment by bilalgodesto** [comment]
Yes i am using different schema than ```public```
I was getting same issue in version 4.12.4.

**Comment by derrickmehaffy** [comment]
Yes this was fixed in v4.12.5 with this PR if you were using a different schema than public: https://github.com/strapi/strapi/pull/17620

Please update to 4.12.5 and for now I'll mark this issue as resolved

**Comment by bilalgodesto** [comment]
@derrickmehaffy 

```
{
  "name": "mytest",
  "private": true,
  "version": "0.1.1",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^1.0.7",
    "@strapi/icons": "^1.7.3",
    "@strapi/plugin-graphql": "4.12.5",
    "@strapi/plugin-i18n": "4.12.5",
    "@strapi/plugin-users-permissions": "4.12.5",
    "@strapi/provider-email-sendgrid": "4.12.5",
    "@strapi/provider-upload-aws-s3": "4.12.5",
    "@strapi/strapi": "4.12.5",
    "chargebee": "^2.10.0",
    "cheerio": "^1.0.0-rc.11",
    "koa-static": "^5.0.0",
    "mime-types": "^2.1.35",
    "moment": "^2.29.3",
    "pg": "^8.6.0",
    "pg-connection-string": "^2.5.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "sanitize-filename": "^1.6.3",
   
    "strapi-provider-email-smtp": "^1.0.3"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "test-bad0-4fee-a674-da565a2a2b4c"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": "8.11.0"
  },
  "license": "MIT"
}

```
every time we add a component or collection and restart a server
we are still getting error


```
error: alter table "salesforce"."account_landings_components" add constraint "account_landings_unique" unique ("entity_id", "component_id", "field", "component_type") - relation "account_landings_unique" already exists
```
all component tables show this type of error. we manually delete all existing keys and then restart server and then it works

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy 
> 
> ```
> {
>   "name": "mytest",
>   "private": true,
>   "version": "0.1.1",
>   "description": "A Strapi application",
>   "scripts": {
>     "develop": "strapi develop",
>     "start": "strapi start",
>     "build": "strapi build",
>     "strapi": "strapi"
>   },
>   "dependencies": {
>     "@_sh/strapi-plugin-ckeditor": "^1.0.7",
>     "@strapi/icons": "^1.7.3",
>     "@strapi/plugin-graphql": "4.12.5",
>     "@strapi/plugin-i18n": "4.12.5",
>     "@strapi/plugin-users-permissions": "4.12.5",
>     "@strapi/provider-email-sendgrid": "4.12.5",
>     "@strapi/provider-upload-aws-s3": "4.12.5",
>     "@strapi/strapi": "4.12.5",
>     "chargebee": "^2.10.0",
>     "cheerio": "^1.0.0-rc.11",
>     "koa-static": "^5.0.0",
>     "mime-types": "^2.1.35",
>     "moment": "^2.29.3",
>     "pg": "^8.6.0",
>     "pg-connection-string": "^2.5.0",
>     "react": "^17.0.2",
>     "react-dom": "^17.0.2",
>     "sanitize-filename": "^1.6.3",
>    
>     "strapi-provider-email-smtp": "^1.0.3"
>   },
>   "author": {
>     "name": "A Strapi developer"
>   },
>   "strapi": {
>     "uuid": "test-bad0-4fee-a674-da565a2a2b4c"
>   },
>   "engines": {
>     "node": ">=14.19.1 <=18.x.x",
>     "npm": "8.11.0"
>   },
>   "license": "MIT"
> }
> 
> ```
> every time we add a component or collection and restart a server
> we are still getting error
> 
> 
> ```
> error: alter table "salesforce"."account_landings_components" add constraint "account_landings_unique" unique ("entity_id", "component_id", "field", "component_type") - relation "account_landings_unique" already exists
> ```
> all component tables show this type of error. we manually delete all existing keys and then restart server and then it works
> 

Inside the database there is a database_schema table. Can you delete the single key that's in there and restart the server?

**Comment by bilalgodesto** [comment]
I follow the steps
Deleted the single entry in ```strapi_data_schema``` table.
I got the same error

**Comment by bilalgodesto** [comment]
@derrickmehaffy  kindly reopen this issue.

**Comment by derrickmehaffy** [comment]
I need steps to reproduce the issue to reopen it, I've been testing this specific issue quite a bit lately and as far as I can tell we resolved the issue with the schema for PG not working correctly and it's exactly the same issue here.

**Comment by bilalgodesto** [comment]
1. Add the package.json file
 ```
{
  "name": "mytest",
  "private": true,
  "version": "0.1.1",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^1.0.7",
    "@strapi/icons": "^1.7.3",
    "@strapi/plugin-graphql": "4.12.5",
    "@strapi/plugin-i18n": "4.12.5",
    "@strapi/plugin-users-permissions": "4.12.5",
    "@strapi/provider-email-sendgrid": "4.12.5",
    "@strapi/provider-upload-aws-s3": "4.12.5",
    "@strapi/strapi": "4.12.5",
    "chargebee": "^2.10.0",
    "cheerio": "^1.0.0-rc.11",
    "koa-static": "^5.0.0",
    "mime-types": "^2.1.35",
    "moment": "^2.29.3",
    "pg": "^8.6.0",
    "pg-connection-string": "^2.5.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "sanitize-filename": "^1.6.3",
   
    "strapi-provider-email-smtp": "^1.0.3"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "test-bad0-4fee-a674-da565a2a2b4c"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": "8.11.0"
  },
  "license": "MIT"
}
```

1. Strapi project with different collection and components
2. Try to add a new component and add it inside collection
3. Save the collection. During dev it will wait for a min and then throw the error
4. Remember that we have around 15 collections and more than 60 components
5. Use database schema other than public.
6. Use Postgres database
Please do not close the issue until resolved. It happen two issue i raised and with out any comment from developer it was closed by strapi team.

**Comment by AlbertCardo** [comment]
We have the same issue. Every time we change some content type (eg add a new column), after the server restarts automatically we get the error `error: alter table "up_users_components" add constraint "up_users_unique" unique ("entity_id", "component_id", "field", "component_type") - relation "up_users_unique" already exists`.

To start the server we need to first manually run some SQL to remove the `*_unique` indexes from all the `*_component` tables with `ALTER TABLE "up_users_components" DROP CONSTRAINT IF EXISTS "up_users_unique";`. This SQL statement needs to be run for all the existing `*_component` tables.

This particular error has been reported in other places:
- https://github.com/strapi/strapi/issues/16055
- https://github.com/strapi/strapi/issues/14912
- https://stackoverflow.com/questions/76231417/strapi-index-error-when-i-try-to-save-anything

Our database schema is called `public`.

**Comment by Sjlver** [comment]
We have seen the same issue, but only if `forceMigration: false` is specified in the settings. Note that the OP also had this setting.

#16055 also mentions that this can be solved by setting `forceMigration: true`.
