### ISSUE TITLE
Populate generated types doesn't work with filter on entityService

### ISSUE THREAD

**Issue by ArthurPedroti** [strapi/strapi#18263]
### Required System information

- Node.js version: v16.20.0
- NPM version: 8.19.4
- Strapi version: 4.13.7
- Database: postfgres
- Operating system: wsl
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I'm using entityService with the generated types, typing my strapi, and I note when a add a filter on my api, the populate fields type are gone from my types.

Before add filters (without error):
![image](https://github.com/strapi/strapi/assets/52859409/733f4462-7ad3-4ffa-b651-58372bd1cc4d)

On add filters (with type error):
![image](https://github.com/strapi/strapi/assets/52859409/3cd4b530-223d-472d-bfc5-214e6d33f9ad)

### Steps to reproduce the behavior

1. Creata a collection type with relation
2. Create a api with entityService without filters and populate and check the types
3. Add filters and check the types

### Expected behavior

Don't gone my populated fields from types.

### Additional context

I don't know if is a bug or I'm using wrong, if anyone can help, thanks.

**Comment by Convly** [comment]
Hey, thanks for sharing this issue!

I've tried to reproduce your issue, but couldn't manage to do so

![image](https://github.com/strapi/strapi/assets/25851739/5b867a2d-671d-45ea-9276-64be0647f497)

Would you mind sharing a minimal reproduction example in order to test your code in the same condition?

**Comment by mnokeefe** [comment]
I'm seeing something similar on Strapi 4.14.0, but with sorting instead.

This gives a type error `Property 'course' does not exist on type 'GetValues<"api::race.race", GetNonPopulatableKeys<"api::race.race">>'.ts(2339)`:
```
const races = await strapi.entityService.findMany("api::race.race", {
      populate: {
        course: {
          populate: {
            organiser: true,
          },
        },
      },
      filters: {
        $and: [
          {
            date: { $gte: startOfYear },
          },
          {
            date: { $lte: endOfYear },
          },
        ],
      },
      sort: { date: "asc" },
    });
```

But if I remove `sort: { date: "asc" }` the `course` is typed correctly. Removing filters has no effect.

**Comment by joeygeeeeee** [comment]
Didn't know whether to make a new report or not but I am getting the same thing on Strapi 14.4.0

```
strapi.entityService.findMany("api::document-acceptance.document-acceptance", {
        filters: {
          $and: [
            { user },
            {
              document: {
                type: 'TERMS'
              }
            }
          ]
        },
        populate: {
          document: {
            fields: ['type']
          }
        },
        sort: 'createdAt:desc'
      })

console.log(latestTermsAcceptance.document.id)
/* 
TS2339: Property  document  does not exist on type
GetValues<"api::document-acceptance.document-acceptance", GetNonPopulatableKeys<"api::document-acceptance.document-acceptance">>
*/
```

But works when I remove the document filter

```
strapi.entityService.findMany("api::document-acceptance.document-acceptance", {
        filters: {
          $and: [
            { user },
            // {
            //   document: {
            //     type: 'TERMS'
            //   }
            // }
          ]
        },
        populate: {
          document: {
            fields: ['type']
          }
        },
        sort: 'createdAt:desc'
      })
```

**Comment by arbuznik** [comment]
Same thing for me, removing `sort` removes TS errors
"@strapi/strapi": "4.14.5"

```
export default factories.createCoreController(
  "api::business.business",
  ({ strapi }) => ({
    async recent(ctx) {
      try {
        const businesses = await strapi.entityService.findMany(
          "api::business.business",
          {
            fields: ["name", "description", "slug", "updatedAt"],
            // sort: { updatedAt: "desc" },
            populate: {
              category: {
                fields: ["name", "slug"],
              },
              cover: true,
            },
            publicationState: "live",
            limit: 5,
          }
        );
```

With `sort` on

<img width="1005" alt="SCR-20231124-sfyo" src="https://github.com/strapi/strapi/assets/14814113/0b54e498-6f03-4200-8a3c-b2a2f51acc44">

**Comment by hussain-mustafa990** [comment]
Issue is still persisting on version 4.15.5

**Comment by Bassel17** [comment]
Hello thank you for reporting the issue,
I was attempting to reproduce this issue but failed to do so, I would need a little more information.
if some of you can provide a link to a public project that is facing this issue, or a copy of the schema so I can try it in my system.

**Comment by arbuznik** [comment]
@Bassel17 

Hello, is this what you require?

```
{
  "kind": "collectionType",
  "collectionName": "businesses",
  "info": {
    "singularName": "business",
    "pluralName": "businesses",
    "displayName": "business",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "slug": {
      "type": "uid",
      "targetField": "name",
      "required": true
    },
    "reviews": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::review.review",
      "mappedBy": "business"
    },
    "category": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "api::category.category",
      "inversedBy": "businesses"
    },
    "reviewCount": {
      "type": "integer"
    },
    "averageReviewRating": {
      "type": "decimal",
      "required": false
    },
    "contacts": {
      "displayName": "contacts",
      "type": "component",
      "repeatable": false,
      "component": "contacts.contacts"
    },
    "description": {
      "type": "richtext"
    },
    "cover": {
      "allowedTypes": [
        "images"
      ],
      "type": "media",
      "multiple": false
    },
    "biz_feedbacks": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::biz-feedback.biz-feedback",
      "mappedBy": "business"
    }
  }
}

```

**Comment by Bassel17** [comment]
yep thank you for the schema, I was able to reproduce the issue with it @arbuznik , will dig deeper into the issue

**Comment by Convly** [comment]
Hello there :wave:

We worked with @Bassel17 to reproduce and understand better the issue.

- On Friday, we managed to track down its origin but couldn't issue a proper fix. As Bassel is off at the moment, I've taken the liberty to take over this.

-  Today's led me to a better understanding of the issue. I've made a fix that works well on my end.

- I'm about to write a PR that will explain the changes etc... I'll also create an experimental release so that anyone can test the changes in their projects.

- Would anyone be interested in testing it locally to confirm it fixes the issue on your end too?

**Comment by Convly** [comment]
Experimental release available here for those interested to test the fix-> https://github.com/strapi/strapi/pull/19082#issuecomment-1861057855

**Comment by Convly** [comment]
Fixed the sort, but missed the filters, I'll issue a fix for the filters too, and check every other param.

**Comment by Convly** [comment]
Here's the new PR that should explain and fix both the `sort` and the `filters`

https://github.com/strapi/strapi/pull/19093

**Comment by Convly** [comment]
https://github.com/strapi/strapi/pull/19093 has been merged. The fix should appear in v4.16.3 (when it'll be released)

**Comment by Convly** [comment]
This should have been fixed in 4.17.0

**Comment by Dudy83** [comment]
Hello,
It seems the issue still persists after updating an existing project from v4.5.5 to 4.19.1. 
Before updating Strapi, I updated `node.js` to `v18.19.0` , deleted the `package-lock.json` file and the `node_modules`, `.cache` and `dist` folders.
The migration went successful until I tried to run my application, and I got this error where all the relations on my entity are not defined in the types.
![image](https://github.com/strapi/strapi/assets/48801109/6dede412-51f6-44f7-9c15-f3a6430cf559)

Here's is the `schema.json` of the entity:

`{
  "kind": "collectionType",
  "collectionName": "menus",
  "info": {
    "singularName": "menu",
    "pluralName": "menus",
    "displayName": "Menu",
    "description": ""
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "user": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "plugin::users-permissions.user",
      "inversedBy": "menus"
    },
    "categories": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::category.category",
      "mappedBy": "menu"
    },
    "stories": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::story.story",
      "mappedBy": "menu"
    },
    "name": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "string",
      "required": true
    },
    "articles": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::article.article",
      "mappedBy": "menu"
    },
    "currency": {
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      },
      "type": "enumeration",
      "enum": [
        "EUR",
        "CZK",
        "USD",
        "GBP"
      ],
      "required": true
    },
    "main_dishes": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::main-dish.main-dish",
      "mappedBy": "menu"
    },
    "uuid": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "customField",
      "customField": "plugin::strapi-advanced-uuid.uuid"
    }
  }
}
`
