### ISSUE TITLE
Media Library's replace media button not working

### ISSUE THREAD

**Issue by Matb85** [strapi/strapi#18352]
### Required System information

- Node.js version: v18.17.1
- NPM version: 9.6.7 
- Strapi version: 4.14.3
- Database: postgresql 13
- Operating system: Amazon Linux 2023 for prod & macOS Sonoma for dev
- Is your project Javascript or Typescript: TS
- Upload provider: AWS S3

### Describe the bug

I cannot replace any files in the media library

### Steps to reproduce the behavior

1. Go to 'Media Library'
2. Click on 'Click on a random image'
3. Click on 'Click on replace Media & choose another Files'
4. Nothing happens!

### Expected behavior

The media should be replaced

### Screenshots

https://github.com/strapi/strapi/assets/69219238/9815ff4f-36bc-4322-8613-384d44b5e87a

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

My upload provider is @strapi/provider-upload-aws-s3

**Comment by Boegie19** [comment]
should be fixed in the next version see pr https://github.com/strapi/strapi/pull/18301

**Comment by miguelfuentesautmix** [comment]
@Boegie19 Hi, I'm also experiencing this issue in version 4.25.1. I checked #18301, I have the changed of that PR but still having the same issue

**Comment by iDelTer** [comment]
@Boegie19 Same issue on Strapi 5.15.1. Cannot replace media. Was supposef to be fixed in Milestone 1.14.4 [#18301](https://github.com/strapi/strapi/pull/18301)
