### ISSUE TITLE
Strapi does not work on a custom port

### ISSUE THREAD

**Issue by maksymenkoml** [strapi/strapi#18600]
### Required System information

- Node.js version: 18
- NPM version: 9.6.7
- Strapi version: 4.15.0
- Database: sqlite
- Operating system: macos
- Is your project Javascript or Typescript: it's pure strapi

### Describe the bug

I've been using Strappy for over a year now.
Today I updated to version 4.15.0 and Strapi stopped working on a port other than the default.

I tried a fresh clean install of Strapi with the command: `yarn create strapi-app my-project --quickstart`
After running the command, Strapi runs on port 1337.
But if you change the PORT value in the .env file, and restart Strapi with the `strapi develop` or `strapi start` command, it starts on the new port, but we get the following errors in the browser:

### Steps to reproduce the behavior

1. Install fresh Strapi: `yarn create strapi-app my-project --quickstart`
2. Change PORT value in .env file from 1377 to 4444
3. Run Strapi with `strapi develop`
4. Go to http://localhost:4444/admin
5. Strapi admin not working

### Expected behavior

Strapi admin is working.

### Screenshots

<img width="1277" alt="image" src="https://github.com/strapi/strapi/assets/122663362/ca065dc3-7ecb-4acc-abdc-1ec794ee319d">

P.S. I created a new report because the previous one was closed and not reopened.

**Comment by maksymenkoml** [comment]
I read about the problems in the nearby problem https://github.com/strapi/strapi/issues/18594, and read how they were solved. I tried to do the same thing and it worked.
Here's what helped:
- deleted all .lock files (`yarn.lock`, `package-lock.json`)
- deleted the `node_modules` folder
- reinstalled the project using `npm install`
- rebuilt the project with `npm run build`
- ran the project with `npm run develop`
Everything is working.

So either the problem is in the .lock files or in the use of yarn.

**Comment by derrickmehaffy** [comment]
I'll go ahead and close this since it's work but indeed you need to rebuild the admin as the one we ship is compiled for port 1337.

**Comment by zirho** [comment]
I've just upgraded from 4.11.0 to 4.11.7 and encounter this issue as well. 
I followed your instructions but still getting the same error. 
What I found unusual is that it always build admin UI when I run `yarn develop` even after I ran `yarn build` myself.
I it intended change for the recent update?

thanks

**Comment by zirho** [comment]
I've test it with the latest version 4.15.0 and found no issues there.
When I change the port in .env file, it just works by restarting it without re-building the strapi admin UI.
so I guess it's project specific issue due to the some configs or cache status. 

thanks

**Comment by zirho** [comment]
It was one of the local plugin that causes the build failure. 
if anyone encounter this, check your custom plugins and error messages followed by `yarn build`
