### ISSUE TITLE
Entities are not deleted completely on heroku (content types, fields)

### ISSUE THREAD

**Issue by schmitzl** [strapi/strapi#1933]
**Informations**

*Local*
- **Node.js version**: 10.4.1
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14
- **Database**: Postgres
- **Operating system**: MacOS

*Heroku*
- **Node.js version**: 10.10.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14
- **Database**: Postgres

**What is the current behavior?**
On heroku, I can observe the following behaviour: When removing an existing field on a model, then adding a new field with the same name but with a different type, I cannot create new entries of this model.

**Steps to reproduce the problem**
1. Create new strapi project (with postgres)
2. Use the content-type-builder to create a model with the name “Comment” and then create a field “text” of type String
3. Deploy to heroku (I can now add an entry for the model "Comment")
4. Change model “Comment” locally. Remove the field “text”.
5. Deploy to heroku
6. Make sure the field “text” is deleted from the database
7. Change model “Comment” locally. Add a field named “text” with the type integer. (There might already be problems locally, however, this has been addressed in issue #1903)
8. Now deploy to heroku
9. Strapi starts normally, the db is modified correctly, but I am unable to load the view to add a new “Comment”. Either its loading forever or I get a completely blank screen.

**What is the expected behavior?**
I can create a new field with the same name as a previously deleted one but with a different type and it works on heroku.

**Note**
Issue  #1903 addresses almost the same problem. However, the fix for this seem to have been added to the content-type-builder plugin. I do not see how this could help with the issue on heroku, since it seems to be a problem with the content-manager plugin there.

**Comment by lauriejim** [comment]
Related issue here https://github.com/strapi/strapi/issues/1903
Has been fixed in `alpha.14.1`

**Comment by schmitzl** [comment]
I also tried this with Strapi version: 3.0.0-alpha.14.1. This does not fix the problem on heroku and it also does not fix it for manual changes in the api files. The problem still exists for the following two scenarios:

1) Heroku
The local store is not pushed to heroku. Heroku has its own store. Heroku also does not allow to modify anything through the content-type-builder plugin. Which means that the changes come only through pushes which does not update the store correctly.
2) Changes in the API model files instead of changes through the content-type-builder plugin
I can imagine there are people who do not want to build everything through the content-type-builder plugin. Any change, that is made directly in the files leads to the same problem as in issue #1903.

I think, that there need to be some sort of a refresh of the store on restart of the server. Compare the schema to the files in the api folder and update it. Or at least give an option for a refresh on restart, that sets the store to null and builds it from scratch. 

For now, I solved manually manipulating the schema in the store through the strapi console.
