### ISSUE TITLE
Infinite loading when creating new entry

### ISSUE THREAD

**Issue by LeBovin** [strapi/strapi#1957]
**Informations**
- **Node.js version**: 10.10.0 (9.x isn't supported for Fedora 28)
- **npm version**: 5.10
- **Strapi version**: 3.0.0-alpha.14.1.1
- **Database**: Mongodb
- **Operating system**: Fedora 28

**What is the current behavior?**
When trying to creating a new entry, admin panel never stop loading

**Steps to reproduce the problem**
1) go to Content Type Builder
2) create a new Content Type named Restaurant
3) add 3 fields to this Content Type: name (string), description (text) then save
4) go to "Restaurants" (top of left menu on admin panel) then click on "Add new Restaurant"
Here you should have an infinite loading

**What is the expected behavior?**
Allowing me inserting new entry

**Comment by lauriejim** [comment]
Hello @LeBovin !

Did you have any errors in your browser console ? and what is the browser you use ?
Did you have a pending network request ?

**Comment by NickBolles** [comment]
I just experienced this with a brand new instance, and trying to create a new user. I didn't see any browser errors, network errors or server output errors. Browser was both Firefox and Chrome, so I doubt it's a browser issue.

We modified the user object, saved the modifications, and the server restarted and then we were able to create a new user just fine through the admin UI.

**Comment by LeBovin** [comment]
@lauriejim @NickBolles Hi and thanks for your replies
As @NickBolles said, no error in the console, and I tried on both Firefox and Chrome

@NickBolles I'll try it and say if I can reproduce the "solution" you got
Anyway, thanks guys

**Comment by inoisy** [comment]
you find solution?

**Comment by soupette** [comment]
@LeBovin @inoisy I'm unable to reproduce the bug which version of strapi are you on?
Is the error occuring in production or in development?

**Comment by NickBolles** [comment]
I'm not 100% sure. But I may have resolved this by copying the `build` folder from 
`node_modules/strapi-admin/admin/` to `admin/admin/build`
Apologies if those paths aren't 100% correct. I'm going off of memory right now.

**Comment by LeBovin** [comment]
Hi everyone,

As @NickBolles said, I modified the entity structure, save the modifications and then I was able to create new entry.
Thanks you !

@soupette I am using the 3.0.0-alpha.14.1.1 in development mode

**Comment by inoisy** [comment]
> @LeBovin @inoisy I'm unable to reproduce the bug which version of strapi are you on?
> Is the error occuring in production or in development?

 3.0.0-alpha.14.1.1 in prod mode

**Comment by soupette** [comment]
@inoisy did you migrate your db (`core_store`) into your production db?

**Comment by soupette** [comment]
@inoisy I experienced the same issue deleting the `plugin_content_manager_schema` made it work again.

**Comment by anderson916** [comment]
<img width="760" alt="screen shot 2018-10-08 at 11 29 53 am" src="https://user-images.githubusercontent.com/195719/46618455-8c9d9e80-caed-11e8-997c-81e24cbff535.png">

**Comment by derrickmehaffy** [comment]
That doesn't look like a related error @anderson916 can you remove the graphQL plugin and try starting again?

**Comment by anderson916** [comment]
working now. thanks.

**Comment by Keatooon** [comment]
**Informations**
Node.js version: v10.2.0
npm version: 5.6.0
Strapi version: 3.0.0-alpha.14.3
Database: Mongodb
Operating system: Ubuntu 18.04.1 LTS

**What is the current behavior?**
When trying to creating a new entry, admin panel never stop loading

**Steps to reproduce the problem**

1) go to Content Type Builder
2) create a new Content Type named "division"
3) add 2 fields to this Content Type: name (string), title (string) then save
4) create a new Content Type named "subDivision"
5) go to "division" (top of left menu on admin panel) then click on "Add new"
6) Here you should have an infinite loading

**Comment by inoisy** [comment]
I understood why this is happening to me. after updating the strapi. that is, he does not want to create new entry to old content type. with new created everything is fine

**Comment by ak5** [comment]
I am having this issue with postgres using docker image ID 61992ba649f9

**Comment by abegehr** [comment]
@soupette deleting "plugin_content_manager_schema" in `core_store` fixed it for me as well. The entry was regenerated. Maybe a note should be added to the deployment documentation?

**Comment by ntloi95** [comment]
I have the same problem with postgres

**Comment by yeomann** [comment]
ok the solution that i found is... let me explain first.

so i created a `--dev` version, Created 1 test content-type and added few fields in it. Did logo changes and created a build afterwards. Next upon staring server, I had babel-polyfill issue, after resolving it (https://github.com/strapi/strapi/issues/514#issuecomment-453684059) on Dashboard i saw my previously created Data-type and i tried to create a post. Upon pressing "saving" it was infinitely loading and eventually gave error.

Solution: Just go to your Content-Type Manager > Choose previously created Content-type > Re "save" it. Now i was able to correctly create/edit/delete my post.

Final thoughts i feel like changes related to Content-type at the time of `--dev` were not tracked correctly, or there entries were missing from DB.

**Comment by yareyaredesuyo** [comment]
Fixed this issue by this procedure (when using heroku + mlab).

- strapi-verion: 3.0.0-alpha.18

```
heroku config // get heroku's mlab config info
mongo mongodb... // connect to mongodb
db.core_store.deleteMany({"key":"plugin_content-manager_schema"})
heroku restart
```

But this is very tricky , it should be documented in somewhere (like wiki).

**Comment by juji** [comment]
just writing for anybody having the same problem....

Deleting "plugin_content_manager_schema" in core_store does not solve my problem.
So, what u did was copying `value` from "plugin_content_manager_schema" from my local to live server. It worked form me.

Cheers..

**Comment by cupojoe** [comment]
I think this issue happens at random in dev too. I experienced it when working locally a lot. What concerns me the most is that there is no error message or timeout. It hangs indefinitely. There is no apparent memory leak anywhere either. It should throw an error of some sort.

**Comment by jsonpj3wt** [comment]
Also experiencing this issue with Mongo and in dev.  Deleting `plugin_content-manager_schema` did not help either.  Any other suggestions?

**Comment by inoisy** [comment]
I also had this error if there is an error in data type definition

**Comment by Ic3m4n34** [comment]
I'm also experiencing this bug

**Comment by rmcfadzean** [comment]
Encountering this in `3.0.0-beta.5` too.

The `db.core_store.deleteMany({"key":"plugin_content-manager_schema"})` and then restart fix worked for me too but this is definite a bug that needs addressing.

**Comment by pgjones** [comment]
I've also experienced this, and I also found that deleting the `plugin_content-manager_schema` in the core_store and then restarting the code fixes the issue.

**Comment by rhaft** [comment]
If Strapi provided clarity on the data structure stored in `plugin_content-manager_schema` then perhaps the community could help each other debug the serious issues everyone is experiencing with upgrades and moving between dev/staging/production. It is not an option to delete this document because it holds critical field display customizations that took a lot of time to create. I have an app headed for production but I don't know how it can happen with the issues in staging. Can't move dev's schema to staging. Once a copy of staging db is copied to dev and qa, those systems now experience the same problem. How can anyone expect to use Strapi as a viable production environment with the current issues? I can't add an administrator - infinite spin. Help!

**Comment by derrickmehaffy** [comment]
@rhaft the Content-Manager plugin is going to be completely rebuilt and that schema entry is going to be broken up to prevent these problems. (There is no ETA but trust me it is high on their list of priorities)

**Comment by har17bar** [comment]
@soupette  please help i dont have any colums in my core_store datatable to delete plugin_content_manager_schema 
![Screen Shot 2019-06-23 at 02 38 22](https://user-images.githubusercontent.com/26884501/59969538-8444a100-9560-11e9-804a-f552c49d96ac.png)

**Comment by derrickmehaffy** [comment]
@har17bar your SQL command is wrong.... lol

`SELECT * FROM core_store WHERE core_store.`key` = 'plugin_content-manager_schema';`

The problem is you are using `where false` which is going to return nothing.

**Comment by derrickmehaffy** [comment]
Also `key` is a reserved sql word hence the reason for the ```core_store.`key` ```

**Comment by har17bar** [comment]
@derrickmehaffy thank you for reply 
no no i I tried like that
  
![Screen Shot 2019-06-23 at 03 27 40](https://user-images.githubusercontent.com/26884501/59969779-09cb4f80-9567-11e9-9018-f6dad10450f6.png)

**Comment by har17bar** [comment]
thank you i mistakenly typed long time))) DELETE FROM core_store WHERE key='plugin_content_manager_schema';
instead of 
DELETE FROM core_store WHERE key='plugin_content-manager_schema';

**Comment by har17bar** [comment]
@derrickmehaffy  now i have in production this situation 
![Screen Shot 2019-06-23 at 03 38 01](https://user-images.githubusercontent.com/26884501/59969824-814dae80-9568-11e9-9719-11dcea74afeb.png)
and lost all CONTENT TYPES

**Comment by derrickmehaffy** [comment]
@har17bar you need to "restart" strapi, however  heroku does that. That entry is created when strapi starts.

**Comment by har17bar** [comment]
@derrickmehaffy wtf web. development is))) thank you

**Comment by har17bar** [comment]
if you using postgreSQL

1.go to heroku type in terminal value of Heroku CLI
![Screen Shot 2019-06-23 at 02 15 04](https://user-images.githubusercontent.com/26884501/59969876-d6d68b00-9569-11e9-8218-01170ee24495.png)

2.DELETE FROM core_store WHERE key='plugin_content-manager_schema';

3. heroku restart

**Comment by hezzze** [comment]
> ok the solution that i found is... let me explain first.
> 
> so i created a `--dev` version, Created 1 test content-type and added few fields in it. Did logo changes and created a build afterwards. Next upon staring server, I had babel-polyfill issue, after resolving it ([#514 (comment)](https://github.com/strapi/strapi/issues/514#issuecomment-453684059)) on Dashboard i saw my previously created Data-type and i tried to create a post. Upon pressing "saving" it was infinitely loading and eventually gave error.
> 
> Solution: Just go to your Content-Type Manager > Choose previously created Content-type > Re "save" it. Now i was able to correctly create/edit/delete my post.
> 
> Final thoughts i feel like changes related to Content-type at the time of `--dev` were not tracked correctly, or there entries were missing from DB.

This method solved my issue, I was actually recreating the type in `Content Type Builder` and it worked. I'm using `v3.0.0-alpha.23`

**Comment by mkhizeryounas** [comment]
> same problem here. @soupette where is "plugin_content_manager_schema"?

Thnak You.!

**Comment by paddymccallan** [comment]
> ![Screen Shot 2019-06-23 at 02 23 16](https://user-images.githubusercontent.com/26884501/59969553-dab1df80-9560-11e9-93a1-a6223eacba1e.png)
> 
> @soupette please help i dont have any colums in my core_store datatable to delete plugin_content_manager_schema
> ![Screen Shot 2019-06-23 at 02 38 22](https://user-images.githubusercontent.com/26884501/59969538-8444a100-9560-11e9-804a-f552c49d96ac.png)
> 
> i am using strapi 3.0.0-beta.6

How did you solve this?

**Comment by muhajirdev** [comment]
Hey guys.
This issue still exist right? Shouldn't we open it back untik it's resolved?

**Comment by miguelangeltorresfp** [comment]
I have the same problem in several entries. I'm getting it resolved as NickBolles said.
I'm adding a fake field to each entry, save it and then it works.

**Comment by barbgegrasse** [comment]
Still struggling with this

**Comment by barbgegrasse** [comment]
> Hey guys.
> This issue still exist right? Shouldn't we open it back untik it's resolved?
 Why is this closed, i spent my day on this.

**Comment by derrickmehaffy** [comment]
This issue has been widely discussed, it's known and has been fixed in the develop branch and will be released in beta.16

Not to mention there are about 20 issues that are all the same thing.
