### ISSUE TITLE
4.15.0: Application Error is returning Internal Server Error instead of actual error.

### ISSUE THREAD

**Issue by gregg-cbs** [strapi/strapi#19686]
### Required System information
- Node.js version: 18.16.0
- NPM version: 9.5.1
- Strapi version: 4.15.0
- Operating system: Windows and Mac
- Is your project Javascript or Typescript: TS

### Describe the bug
When throwing `throw new ApplicationError` in a controller or service strapi is returning "Internal Server Error" instead of the application error. This was not always the case although we have once seen this before due to a node version.

Now all of a sudden it is happening again on two different devices and we are not sure if some dependency has updated.

### Steps to reproduce the behavior

1. Controller throws 'throw new ApplicationError("You do not have permissions to do this")
2. Rest api querying said controller is receiving "Internal Server Error" instead of the application error

### Expected behavior

This behaviour has been before but we got rid of it by changing to node 18. Now it is happening again since we had an issue with strapi auto bumping to the next version and we downgraded back to 4.15.0.

### Screenshots
Query:
![image](https://github.com/strapi/strapi/assets/57114335/20304629-35ac-4a07-a19b-b0a7dd4132e9)

Controller:
![image](https://github.com/strapi/strapi/assets/57114335/c6c9c513-df31-4d14-8efd-6a3732114e48)

**Comment by gregg-cbs** [comment]
Some help here would be great. We are launching our product tomorrow and all errors are coming back as Internal Server Error. Any ideas we can try out today?

**Comment by gregg-cbs** [comment]
@ProfXponent -> to begin with on 4.15.0 this was not an issue for me but it was an issue for my colleague who was running a node version higher then i was. Upon downgrading to my version it solved the issue for him.

But now after removing strapi and reinstalling 4.15.0 again this has become an issue for both of us and we are on the same node version from when it was working.

So im not sure if some sub dependency is updating somewhere.

The reason we uninstalled strapi is because it automatically bumped up a version and broken everything and then we had hell trying to reverse versions. Now we have this issue.

**Comment by gregg-cbs** [comment]
@ProfXponent -> what node version are you on? Documentation says:
"Only Active LTS or Maintenance LTS versions are supported (currently v18 and v20). Odd-number releases of Node, known as "current" versions of Node.js, are not supported (e.g. v19, v21)."

**Comment by gregg-cbs** [comment]
I upgraded to 4.20.4 and this issue is resolved. I am using node 18.6.0.

**Comment by ProfXponent** [comment]
we are still seeing the error on strapi@4.20.3 & node@18.19.1

i will upgrade later and confirm whether or not it is present on 4.20.4

<img width="703" alt="server-error" src="https://github.com/strapi/strapi/assets/106058741/f87b98c8-0196-4b93-8c01-c56bab276aac">
<img width="441" alt="client-error" src="https://github.com/strapi/strapi/assets/106058741/d3451bcf-ef01-4cd8-a15a-e4e504f880f6">
<img width="352" alt="versions" src="https://github.com/strapi/strapi/assets/106058741/34be9405-b516-4d6a-93ca-ac3933d86afa">

**Comment by gregg-cbs** [comment]
Yeah this can be very frustrating. Just make sure to delete node_modules after bumping up to 4.20.4.

1. Change version in package.json file
2. Delete node_modules folder
3. npm i
4. npm run build
5. npm run dev

**Comment by ProfXponent** [comment]
@gregg-cbs strapi@4.20.4 doesn't even build for us

we run strapi in a docker container and don't externally mount `node_modules` so its a fresh install every time `package.json` changes.

getting the following error after upgrading to `strapi@4.20.4`

```shell
cms        | [ERROR] Module not found: Error: Can't resolve '@strapi/design-system/Box' in '/opt/app/node_modules/@strapi/plugin-seo/admin/src/components/CMEditView/RightLinksCompo'
```

starting with `strapi develop --debug` yields

```shell
cms  | 
cms  | > cms@0.1.0 develop
cms  | > strapi develop --debug
cms  | 
cms  | [DEBUG] Loaded package.json: 
cms  |  {
cms  |   name: 'cms',
cms  |   version: '0.1.0',
cms  |   description: 'A Strapi application',
cms  |   scripts: {
cms  |     develop: 'strapi develop --debug',
cms  |     start: 'strapi start',
cms  |     build: 'strapi build',
cms  |     strapi: 'strapi',
cms  |     import: 'strapi import --file ./seeds/seed-data.tar.gz',
cms  |     export: 'strapi export --no-encrypt --file ./exports/export'
cms  |   },
cms  |   dependencies: {
cms  |     '@strapi/plugin-documentation': '4.20.4',
cms  |     '@strapi/plugin-i18n': '4.20.4',
cms  |     '@strapi/plugin-seo': '1.9.8',
cms  |     '@strapi/plugin-users-permissions': '4.20.4',
cms  |     '@strapi/provider-email-sendgrid': '4.20.4',
cms  |     '@strapi/strapi': '4.20.4',
cms  |     react: '18.2.0',
cms  |     'react-dom': '18.2.0',
cms  |     'react-router-dom': '5.3.4',
cms  |     'styled-components': '5.3.11',
cms  |     'better-sqlite3': '9.4.3'
cms  |   },
cms  |   strapi: { uuid: '42b937aa-0f16-4a30-bb55-95f60ec03b48' },
cms  |   engines: { node: '>=14.19.1 <=18.x.x', npm: '>=6.0.0' },
cms  |   readme: 'ERROR: No README data found!',
cms  |   _id: 'cms@0.1.0'
cms  | }
cms  | 
cms  | - Building build context
cms  | [INFO] Including the following ENV variables as part of the JS bundle:
cms  |     - ADMIN_PATH
cms  |     - STRAPI_ADMIN_BACKEND_URL
cms  |     - STRAPI_TELEMETRY_DISABLED
cms  | [DEBUG] Cleaning dist folder: /opt/app/build
cms  | [DEBUG] Cleaned dist folder
cms  | [DEBUG] Dependencies from user's project 
cms  |  {
cms  |   '@strapi/plugin-documentation': '4.20.4',
cms  |   '@strapi/plugin-i18n': '4.20.4',
cms  |   '@strapi/plugin-seo': '1.9.8',
cms  |   '@strapi/plugin-users-permissions': '4.20.4',
cms  |   '@strapi/provider-email-sendgrid': '4.20.4',
cms  |   '@strapi/strapi': '4.20.4',
cms  |   react: '18.2.0',
cms  |   'react-dom': '18.2.0',
cms  |   'react-router-dom': '5.3.4',
cms  |   'styled-components': '5.3.11',
cms  |   'better-sqlite3': '9.4.3'
cms  | }
cms  | [DEBUG] User's plugins file 
cms  |  {
cms  |   seo: { enabled: true },
cms  |   email: {
cms  |     config: {
cms  |       provider: 'sendgrid',
cms  |       providerOptions: [Object],
cms  |       settings: [Object]
cms  |     }
cms  |   },
cms  |   documentation: {
cms  |     enabled: true,
cms  |     config: {
cms  |       openapi: '3.0.0',
cms  |       info: [Object],
cms  |       'x-strapi-config': [Object],
cms  |       servers: [Array],
cms  |       externalDocs: [Object],
cms  |       security: [Array]
cms  |     }
cms  |   }
cms  | }
cms  | [DEBUG] Enabled plugins 
cms  |  {
cms  |   documentation: {
cms  |     name: 'documentation',
cms  |     importName: 'documentation',
cms  |     type: 'module',
cms  |     modulePath: '@strapi/plugin-documentation'
cms  |   },
cms  |   i18n: {
cms  |     name: 'i18n',
cms  |     importName: 'i18N',
cms  |     type: 'module',
cms  |     modulePath: '@strapi/plugin-i18n'
cms  |   },
cms  |   seo: {
cms  |     name: 'seo',
cms  |     importName: 'seo',
cms  |     type: 'module',
cms  |     modulePath: '@strapi/plugin-seo'
cms  |   },
cms  |   'users-permissions': {
cms  |     name: 'users-permissions',
cms  |     importName: 'usersPermissions',
cms  |     type: 'module',
cms  |     modulePath: '@strapi/plugin-users-permissions'
cms  |   }
cms  | }
cms  | [DEBUG] Enabled plugins with FE 
cms  |  [
cms  |   {
cms  |     name: 'documentation',
cms  |     importName: 'documentation',
cms  |     type: 'module',
cms  |     modulePath: '@strapi/plugin-documentation/strapi-admin'
cms  |   },
cms  |   {
cms  |     name: 'i18n',
cms  |     importName: 'i18N',
cms  |     type: 'module',
cms  |     modulePath: '@strapi/plugin-i18n/strapi-admin'
cms  |   },
cms  |   {
cms  |     name: 'seo',
cms  |     importName: 'seo',
cms  |     type: 'module',
cms  |     modulePath: '@strapi/plugin-seo/strapi-admin'
cms  |   },
cms  |   {
cms  |     name: 'users-permissions',
cms  |     importName: 'usersPermissions',
cms  |     type: 'module',
cms  |     modulePath: '@strapi/plugin-users-permissions/strapi-admin'
cms  |   }
cms  | ]
cms  | ✔ Building build context (74ms)
cms  | - Creating admin
cms  | [DEBUG] Created the runtime directory
cms  | [DEBUG] Rendered the HTML
cms  | [DEBUG] Wrote the index.html file
cms  | [DEBUG] Wrote the app.js file
cms  | [DEBUG] Webpack config {
cms  |   experiments: { topLevelAwait: true },
cms  |   entry: { main: [ './.strapi/client/app.js' ] },
cms  |   resolve: {
cms  |     alias: {
cms  |       '@strapi/design-system$': '/opt/app/node_modules/@strapi/admin/node_modules/@strapi/design-system',
cms  |       '@strapi/helper-plugin$': '/opt/app/node_modules/@strapi/admin/node_modules/@strapi/helper-plugin',
cms  |       '@strapi/icons$': '/opt/app/node_modules/@strapi/admin/node_modules/@strapi/icons',
cms  |       'date-fns$': '/opt/app/node_modules/date-fns',
cms  |       'formik$': '/opt/app/node_modules/formik',
cms  |       'history$': '/opt/app/node_modules/history',
cms  |       'immer$': '/opt/app/node_modules/immer',
cms  |       'qs$': '/opt/app/node_modules/qs',
cms  |       'lodash$': '/opt/app/node_modules/lodash',
cms  |       'react$': '/opt/app/node_modules/react',
cms  |       'react-dnd$': '/opt/app/node_modules/react-dnd',
cms  |       'react-dnd-html5-backend$': '/opt/app/node_modules/react-dnd-html5-backend',
cms  |       'react-dom$': '/opt/app/node_modules/react-dom',
cms  |       'react-error-boundary$': '/opt/app/node_modules/react-error-boundary',
cms  |       'react-helmet$': '/opt/app/node_modules/react-helmet',
cms  |       'react-is$': '/opt/app/node_modules/react-is',
cms  |       'react-intl$': '/opt/app/node_modules/react-intl',
cms  |       'react-query$': '/opt/app/node_modules/react-query',
cms  |       'react-redux$': '/opt/app/node_modules/react-redux',
cms  |       'react-router-dom$': '/opt/app/node_modules/react-router-dom',
cms  |       'react-window$': '/opt/app/node_modules/react-window',
cms  |       'react-select$': '/opt/app/node_modules/react-select',
cms  |       'redux$': '/opt/app/node_modules/redux',
cms  |       'reselect$': '/opt/app/node_modules/reselect',
cms  |       'styled-components$': '/opt/app/node_modules/styled-components',
cms  |       'yup$': '/opt/app/node_modules/yup'
cms  |     },
cms  |     extensions: [ '.js', '.jsx', '.react.js', '.ts', '.tsx' ]
cms  |   },
cms  |   module: {
cms  |     rules: [
cms  |       [Object], [Object],
cms  |       [Object], [Object],
cms  |       [Object], [Object],
cms  |       [Object]
cms  |     ]
cms  |   },
cms  |   plugins: [
cms  |     HtmlWebpackPlugin {
cms  |       userOptions: [Object],
cms  |       version: 5,
cms  |       options: [Object]
cms  |     },
cms  |     DefinePlugin { definitions: [Object] },
cms  |     MiniCssExtractPlugin {
cms  |       _sortedModulesCache: [WeakMap],
cms  |       options: [Object],
cms  |       runtimeOptions: [Object]
cms  |     }
cms  |   ],
cms  |   stats: 'errors-only',
cms  |   mode: 'production',
cms  |   bail: true,
cms  |   devtool: false,
cms  |   output: {
cms  |     path: '/opt/app/build',
cms  |     publicPath: '/admin/',
cms  |     filename: '[name].[contenthash:8].js',
cms  |     chunkFilename: '[name].[contenthash:8].chunk.js'
cms  |   },
cms  |   optimization: {
cms  |     minimize: undefined,
cms  |     minimizer: [ [ESBuildMinifyPlugin] ],
cms  |     moduleIds: 'deterministic',
cms  |     runtimeChunk: true
cms  |   }
cms  | }
cms  | [ERROR] Module not found: Error: Can't resolve '@strapi/icons/Search' in '/opt/app/node_modules/@strapi/plugin-seo/admin/src/components/PluginIcon'
cms  | [ERROR]  There seems to be an unexpected error, try again with --debug for more information 
```

I'm including my `Dockerfile`, `package.json`, and `package-lock.json` if anyone wants to replicate this.

Already cleared my image cache and rebuild from scratch a few times.

Below is a `docker-compose.yaml` snippet you can use with the included `Dockerfile`

```Dockerfile
ARG NODE_VERSION
FROM node:${NODE_VERSION}
RUN mkdir -p /opt/app
RUN chown -R node:node /opt/app
# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add curl bash build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev

USER node

WORKDIR /opt/app
ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}
COPY --chown=node:node package.json package-lock.json ./
RUN npm install
ENV PATH /opt/app/node_modules/.bin:$PATH
COPY --chown=node:node config ./config
COPY --chown=node:node database ./database
COPY --chown=node:node public ./public
COPY --chown=node:node src ./src
COPY --chown=node:node favicon.png ./favicon.png

CMD ["npm", "run", "develop"]
```

```yaml
services:
  strapi-cms:
    container_name: strapi-cms
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 18-alpine3.19
        NODE_ENV: development
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 10
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 1337
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: database/data.db
      DATABASE_HOST: db
      JWT_SECRET: aaa
      ADMIN_JWT_SECRET: bbb
      SENDGRID_API_KEY: ccc
      SENDGRID_SENDER_EMAIL: ddd
      APP_KEYS: eee,fff,ggg,hhh
      API_TOKEN_SALT: iii
      TRANSFER_TOKEN_SALT: jjj
      WEB_URL: http://web-container:3000
      CMS_URL: http://strapi-cms:1337
    volumes:
      - ./config:/opt/app/config
      - ./database:/opt/app/database
      - ./public:/opt/app/public
      - ./src:/opt/app/src
      - ./favicon.png:/opt/app/favicon.png
      - ./seeds:/opt/app/seeds:ro
      - ./exports:/opt/app/exports
      - ./package.json:/opt/app/package.json
      - ./package-lock.json:/opt/app/package-lock.json
```

[package-lock.json](https://github.com/strapi/strapi/files/14556743/package-lock.json)
[package.json](https://github.com/strapi/strapi/files/14556744/package.json)

**Comment by ProfXponent** [comment]
Ok, @gregg-cbs so after resolving the dependency issue above I can confirm that the error is present on `strapi@4.20.3` and seems to be resolved on `strapi@4.20.4`.

I don't see any mention of it in the release notes so I'm not sure if it was an actual bug fix or something that got resolved incidentally.

**Comment by Melly5** [comment]
had the same issue with strapi version `4.20.3`, error was shown as internal error, but didn't appear in the UI Admin Panel

can confirm, that upgrading to  `4.20.4` and following the [gregg-cbs](https://github.com/gregg-cbs) instructions fixed the problem (let's hope this is a longterm fix)

> Yeah this can be very frustrating. Just make sure to delete node_modules after bumping up to 4.20.4.
> 
> 1. Change version in package.json file
> 2. Delete node_modules folder
> 3. npm i
> 4. npm run build
> 5. npm run dev

**Comment by obafunmiso-olufemi** [comment]
> had the same issue with strapi version `4.20.3`, error was shown as internal error, but didn't appear in the UI Admin Panel
> 
> can confirm, that upgrading to `4.20.4` and following the [gregg-cbs](https://github.com/gregg-cbs) instructions fixed the problem (let's hope this is a longterm fix)
> 
> > Yeah this can be very frustrating. Just make sure to delete node_modules after bumping up to 4.20.4.
> > 
> > 1. Change version in package.json file
> > 2. Delete node_modules folder
> > 3. npm i
> > 4. npm run build
> > 5. npm run dev

I am still experiencing same issue even after doing the above

**Comment by gregg-cbs** [comment]
@obafunmiso-olufemi What is your node version?

**Comment by obafunmiso-olufemi** [comment]
Hi @gregg-cbs 
**18.19.1**
Was formally on **Alpine 18.17.1** but moved to alpine **18.19**

**Comment by gregg-cbs** [comment]
I will try 18.19.1 tomorrow and see if it has any effects on our errors

**Comment by obafunmiso-olufemi** [comment]
Hi @kasonde 
i am still having same issue

strapi version 4.21.0
 node v18.20.2

**Comment by gregg-cbs** [comment]
I just experienced this issue on our production server. It was using a higher version of Node then my local. I have fixed the projects node version to 18.16.0 . I am on strapi 4.20.4.

@obafunmiso-olufemi

**Comment by gregg-cbs** [comment]
@obafunmiso-olufemi  - we just tested strapi 4.20.4 with node 18.20.2 and it worked fine. fwiw.

**Comment by obafunmiso-olufemi** [comment]
Thanks @gregg-cbs 
This is working for a local plugin
But when I push the plugin to github package and install.. The error is not displaying on UI ..  it only showing on. network tab

**Comment by kasonde** [comment]
Hi all, this is currently a known issue. For ease of tracking, I"ll close this and set it as a duplicate of #19495.

**Comment by roman-karagodin-ovpn** [comment]
As for me, synchronizing the versions of `@strapi/strapi` & `@strapi/utils` has helped: currently I'm using Strapi v.4.25.2, and when I was importing `ApplicationError` from Strapi Utils v.4.25.3, the server responded with 500 Internal server error; but once I downgraded Strapi Utils to v4.25.2, the server responds with status 400, and Application Error with the correct text is shown.

**Comment by pakoc** [comment]
The versions of these packages must be the same, for example:

```code 
@strapi/plugin-users-permissions: 4.25.2
@strapi/strapi: 4.25.2
@strapi/utils: 4.25.2
```
Keeping the versions consistent will ensure everything works correctly.
