### ISSUE TITLE
Front End Filter missing 'contains' option searching against linked field

### ISSUE THREAD

**Issue by 8ozStudios** [strapi/strapi#19999]
### Required System information

- Node.js version: v16.20.2
- NPM version: 6.4.1
- Strapi version: 4.20.1
- Database: postgres
- Operating system: MacOS on my localhost, Ubuntu on the server
- Is your project Javascript or Typescript: Javascript

### Describe the bug

The front end Collection Type entries list view is missing the ability to Filter by 'contains' against a relational field's display field. 

### Steps to reproduce the behavior

1. First you need 2 Collection Types, where Collection Type 1 has a relational field linking to Collection Type 2
2. Set the display field for the relational field to a string, like Title, so Title is what displays in the view instead of the ID. 
3. Go to the Entries List view in the Admin area for Collection Type 1
4. Click Filters, select the relational field. 
5. Click on the Operators (is, is not, etc) -- there is no "Contains" options because these operators are based on field type of the relational field instead of the field type for the Display Field (I think that's what's happening, anyway). 

### Expected behavior

In v3, the 'contains' operator was available, allowing my users to search by putting in a substring of the display field. This is the behavior I'd expect to see as it was very useful. 

### Screenshots

This doesn't really show all that much, but maybe it helps make clear what I'm describing above. The relational field is called 'tracker_nominee' so it is an ID in the database but the display field is Tracker_nominee.Name. My users would like to be able to search by typing in the first few letters of the display field but they cannot. 
<img width="1322" alt="Screen Shot 2024-04-02 at 3 00 53 PM" src="https://github.com/strapi/strapi/assets/1435572/d2ce32ee-8a52-42af-a822-d8bb1b53e929">

### Code snippets

Not applicable. 

### Additional context

Seems like this worked in v3, maybe some early v4 versions but is lost in 4.20.1.

**Comment by derrickmehaffy** [comment]
I checked in Strapi 5 with this user on Discord and in v5 the relation does have contains now however it forces it on the id of the relationship, not the display field used.

**Comment by derrickmehaffy** [comment]
Most likely the filter isn't shown in v4 because it considers the relationship and integer id field and not the type of the display field.

Hey @8ozStudios looks like you might be lucky (and should probably buy a lotto ticket).

I realized this was a duplicate to https://github.com/strapi/strapi/issues/19532 and looks like there was a PR created to fix it. We will know for sure when it's merged and releases.

I'm gonna close this one as a duplicate sorry for having you create this.

**Comment by derrickmehaffy** [comment]
Closing as should be fixed by https://github.com/strapi/strapi/pull/19970 to be released in 4.22.1

**Comment by 8ozStudios** [comment]
@derrickmehaffy I just upgraded to 4.22.1 and the issue is not resolved for me. Can you confirm that this issue resolution was included in this release? Thanks

**Comment by 8ozStudios** [comment]
@derrickmehaffy Nevermind, 4.23.0 included the fix. Thank you!
