### ISSUE TITLE
v5 The "path" argument must be of type string. Received undefined ERROR

### ISSUE THREAD

**Issue by heshed1** [strapi/strapi#20057]
### Required System information

Environment: development
OS: win32-x64
Strapi Version: 5.0.0-beta.2
Node/Yarn Version: yarn/1.22.22 npm/? node/v18.19.1 win32 x64
Edition: Community
Database: sqlite

### Describe the bug
After create component,  The "path" argument must be of type string. Received undefined ERROR appear and close my project.

My component's json is here

`{
  "collectionName": "components_block_heroes",
  "info": {
    "displayName": "hero"
  },
  "options": {},
  "attributes": {
    "media": {
      "allowedTypes": [
        "images",
        "files",
        "videos",
        "audios"
      ],
      "type": "media",
      "multiple": false
    }
  }
}
`

It's problem with node_modules/@strapi/core/dist/loaders/components.js file

So I fixed this code
`    Object.keys(map[category]).forEach((key) => {
      const schema = map[category][key];
      if (!schema.collectionName) {
        const filePath = path.join(strapi.dirs.app.components, category, schema.__filename__);
        return strapi.stopWithError(
          `Component ${key} is missing a "collectionName" property.
Verify file ${filePath}.`
        );
      }
`

to this
`    Object.keys(map[category]).forEach((key) => {
      let schema = map[category][key];
      if (!schema.collectionName) schema =map[category];
      console.log(schema.collectionName, schema);
      if (!schema.collectionName) {
        const filePath = path.join(strapi.dirs.app.components, category, schema.__filename__);
        return strapi.stopWithError(
          `Component ${key} is missing a "collectionName" property.
Verify file ${filePath}.`
        );
      }
`
then It work fine but I cannot sure it work everywhere.

**Comment by heshed1** [comment]
`
  const categories = {};
  Object.keys(map).map(v=>{
    const keys = v.split('\\');
    if(!categories[keys[0]]){
      categories[keys[0]] = {};
    }
    categories[keys[0]][keys[1]] = map[v]
  })
  const components = Object.keys(categories).reduce((acc, category) => {
    Object.keys(categories[category]).forEach((key) => {
      const schema = categories[category][key];
      console.log(schema)
      if (!schema.collectionName) {
        const filePath = path.join(strapi.dirs.app.components, category, schema.__filename__);
        return strapi.stopWithError(
          `Component ${key} is missing a "collectionName" property.
Verify file ${filePath}.`
        );
      }
      const uid = `${category}.${key}`;
      acc[uid] = Object.assign(schema, {
        __schema__: ___default.default.cloneDeep(schema),
        uid,
        category,
        modelType: "component",
        modelName: key,
        globalId: schema.globalId || ___default.default.upperFirst(___default.default.camelCase(`component_${uid}`))
      });
    });
    return acc;
  }, {});
  strapi.get("components").add(components);
}
`
it work more fine

**Comment by circular-dependency** [comment]
I got the same error on a Windows machine. On a Macbook (or probably every other Unix-based system) this error would not appear.
Turns out there seems to be a parsing issue, when Strapi tries to parse the component's JSON files into an object.

Inside `node_modules/@strapi/core/dist/utils/filepath-to-prop-path.js` on line 9, the filepath is being split:

`const prop = cleanPath.replace(/(\.settings|\.json|\.js)/g, "").toLowerCase().split("/").map((p) => ___default.default.trimStart(p, ".")).join(".").split(".");`

at `/`.

In my case there was no foreslash in the filepath on the Windows machine, but a backslash. Which is usual behaviour on Windows, yet still odd if most Windows users wouldn't have noticed this issue, when working with Strapi components.

**Comment by justadaniel** [comment]
I have the same issue. I haven't been able to start the project on Windows whatsoever, but macOS is just fine. I've tested it on a DigitalOcean instance and it seems to work just fine (when it comes to this specific issue). Here's a screen grab for a contributor to find it.

![2024-05-13 19_13_42-](https://github.com/strapi/strapi/assets/1112585/062a5969-e3f0-4b9c-a63e-bb4a2363585f)

**Comment by Convly** [comment]
Hey there, I'm trying to reproduce your issue but haven't had any chance so far.

I've created a brand new Windows 11 installation, installed Node, ran my project and created a component. Paths are returned with forward slashes (running everything from PowerShell).

If you could provide the following, it would be very helpful:
- What version of Windows are you using?
- What shell are you using?
- Are you using yarn or npm?

Note: In theory I agree that we should support backward slashes as it's quite standard on Windows, but to fix the issue, I need to be able to reproduce it first

**Comment by AleksDrop** [comment]
> Hey there, I'm trying to reproduce your issue but haven't had any chance so far.
> 
> I've created a brand new Windows 11 installation, installed Node, ran my project and created a component. Paths are returned with forward slashes (running everything from PowerShell).
> 
> If you could provide the following, it would be very helpful:
> 
> * What version of Windows are you using?
> * What shell are you using?
> * Are you using yarn or npm?
> 
> Note: In theory I agree that we should support backward slashes as it's quite standard on Windows, but to fix the issue, I need to be able to reproduce it first

There are 2 duplicate bugs linked now, with reproduction steps.

**Comment by Rushikeshp2002** [comment]
> `const categories = {}; Object.keys(map).map(v=>{ const keys = v.split('\\'); if(!categories[keys[0]]){ categories[keys[0]] = {}; } categories[keys[0]][keys[1]] = map[v] }) const components = Object.keys(categories).reduce((acc, category) => { Object.keys(categories[category]).forEach((key) => { const schema = categories[category][key]; console.log(schema) if (!schema.collectionName) { const filePath = path.join(strapi.dirs.app.components, category, schema.__filename__); return strapi.stopWithError(`Component ${key} is missing a "collectionName" property. Verify file ${filePath}.`); } const uid =`${category}.${key}`; acc[uid] = Object.assign(schema, { __schema__: ___default.default.cloneDeep(schema), uid, category, modelType: "component", modelName: key, globalId: schema.globalId || ___default.default.upperFirst(___default.default.camelCase(`component_${uid}`)) }); }); return acc; }, {}); strapi.get("components").add(components); } ` it work more fine

You are a savior bro💖

**Comment by Webbist-dev** [comment]
Also experiencing this. 

On fresh install, created a new component in a collection, breaks then on reboot as reported. 

```
│       TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined                            
│       at Object.join (node:path:433:7)                                                                                        
│       at D:\personal\website\api\node_modules\@strapi\core\dist\loaders\components.js:17:31                                   
│       at Array.forEach (<anonymous>)                                                                                          
│       at D:\personal\website\api\node_modules\@strapi\core\dist\loaders\components.js:14:32                                   
│       at Array.reduce (<anonymous>)                                                                                           
│       at loadComponents (D:\personal\website\api\node_modules\@strapi\core\dist\loaders\components.js:13:39)                  
│       at async Promise.all (index 5)                                                                                          
│       at async Module.loadApplicationContext (D:\personal\website\api\node_modules\@strapi\core\dist\loaders\index.js:12:3)   │
│       at async Object.register (D:\personal\website\api\node_modules\@strapi\core\dist\providers\registries.js:26:5)          
│       at async Strapi.register (D:\personal\website\api\node_modules\@strapi\core\dist\Strapi.js:322:7)```

**Comment by AleksDrop** [comment]
Is there any movement on this? This is completely critical functionality and I believe the title doesn't reflect that. While the error is about the path argument, the actual reproduction steps are: 

1. npx create-strapi-app@beta betalatest --quickstart
2. Start the admin panel
3. Create a simple component with 2 text fields
4. Get the error on reload (see above)

**Comment by Convly** [comment]
Hi, I've released an experimental version with a potential fix.

If someone could try this version `0.0.0-experimental.545ccead2ee1717bbc7ab950455dbb0ddb9924a3` and tell me wether it fixes the issue or not, that would be awesome.

**Comment by morneluckybeard** [comment]
> 0.0.0-experimental.545ccead2ee1717bbc7ab950455dbb0ddb9924a3

I just ran the experimental with a fresh install,
![image](https://github.com/strapi/strapi/assets/58560781/4e9ae0dd-2855-46cf-8b43-42913f7f4a6d)


I created a component with a text field and hit save :( :

![image](https://github.com/strapi/strapi/assets/58560781/f3b340be-1d2d-4e53-b26d-f366587e2cc6)

**Comment by morneluckybeard** [comment]
@Convly After logging from the components.js file, I see that the schema.__filename__ is undefined, and I'm guessing the path.join is not liking it, thus complaining it must be of type string.

![image](https://github.com/strapi/strapi/assets/58560781/9bd4f56e-d260-44df-87a8-f32f039423ac)

**Comment by Convly** [comment]
Damn, that makes no sense :slightly_frowning_face: 
I'm still trying to reproduce that on Windows, but so far no luck, I've only tried to apply a blind fix.
I will continue to try. Thanks for testing though

**Comment by morneluckybeard** [comment]
I'm not sure why it's working for others, but in my case the `const schema = map[category][key];` is actually assigning the value of the properties as the schema on each iteration, so `schema = collectionName` and when checking `schema.collectionName`, it's undefined.

![image](https://github.com/strapi/strapi/assets/58560781/9e67b368-5002-475b-bfde-442893a895be)

**Comment by Convly** [comment]
Alright, so I've tested with a new experimental `0.0.0-experimental.a9a5a36dd73072c19eadeff5f387e8286b2a4d22` and it appears to be fixed.

I'll wait to see if other can confirm as well :slightly_smiling_face:

**Comment by morneluckybeard** [comment]
Works for me :) Thanks @Convly !

**Comment by AleksDrop** [comment]
> Alright, so I've tested with a new experimental `0.0.0-experimental.a9a5a36dd73072c19eadeff5f387e8286b2a4d22` and it appears to be fixed.
> 
> I'll wait to see if other can confirm as well 🙂

Seems to be working. Thanks @Convly! Please roll it out soon.

**Comment by Convly** [comment]
Glad to hear it's working for both of you!

The PR is being reviewed and will be released after that

**Comment by hanpaine** [comment]
Resolved by #20680

**Comment by AleksDrop** [comment]
Still present in the latest RC build
```
npx create-strapi-app@rc rc5 --quickstart
Need to install the following packages:
create-strapi-app@5.0.0-rc.2
```
Same repro steps with creating a simple component crashes the app .

**Comment by ktx-kirtan** [comment]
Yes, tested on rc2. Same steps,

1. Install rc2 with create-strapi-app
2. Create a component with 2 text fields
3. Hit, save, server restarts
4. Got the error:

![image](https://github.com/strapi/strapi/assets/124270523/ca05d894-b2e8-4c67-b9ed-0e5e19dc15b9)

**Comment by hanpaine** [comment]
Hi @AleksDrop @ktx-kirtan the fix will be in rc-3 coming today 😁 thank you for the speediness of checking! Please let us know if you still find it present on rc-3 🙏

**Comment by DanielASMPT** [comment]
Got the issue now on Microsoft Windows Server 2016 Standard now on version 4.25.3 ->  V4. Wokrs fine on Version 4.24.2. Node Version 18

![image](https://github.com/strapi/strapi/assets/63778582/775aa9fe-50bc-46f5-ad5e-3e45107c1529)

**Comment by derrickmehaffy** [comment]
> Got the issue now on Microsoft Windows Server 2016 Standard on version 4.25.3 -> V4. Works fine on Version 4.25.2 Node Version 18
> 
> ![image](https://private-user-images.githubusercontent.com/63778582/347481515-775aa9fe-50bc-46f5-ad5e-3e45107c1529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NDA2NDksIm5iZiI6MTcyMDY0MDM0OSwicGF0aCI6Ii82Mzc3ODU4Mi8zNDc0ODE1MTUtNzc1YWE5ZmUtNTBiYy00NmY1LWFkNWUtM2U0NTEwN2MxNTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE5MzkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMTNhZDg2YzZmZWNhNjgxNjk2NTlhYTBjOWZjNmQwM2ZlM2QyMTg4Y2NmNjg5ZDE5N2Y1NDA0Mzg2NGRmODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VOKKOFVjiG5a7zOKurUw_b8LOZG1B3Pl8lOuacm_l2Q)

Just a heads up, we do not support Microsoft server in any capacity. We support local development on windows but deployment on windows server is not supported. (Not that it matters here but just a heads up)
