### ISSUE TITLE
@strapi/email/package.json missing from new project v5

### ISSUE THREAD

**Issue by exoer** [strapi/strapi#20614]
### Required System information

- Node.js version: v20.14.0
- NPM version:  10.7.0
- Strapi version:5.0.0-beta.15
- Database: SQLite
- Operating system: mac
- Is your project Javascript or Typescript: ts

### Describe the bug

> npm run start

[2024-06-24 20:05:44.488] error: Cannot find module '@strapi/email/package.json'

### Steps to reproduce the behavior

I started a new project 
 
> npx create-strapi@beta --quickstart proj

got it running in dev mode

> npm run start

### Expected behavior

It should build and run

**Comment by derrickmehaffy** [comment]
Fairly certain this has been fixed in recent versions as I haven't seen it for a while so gonna go ahead and close, if someone else hits this please comment back and we can reopen.

**Comment by saoudi-h** [comment]
Error still there for me, on a fresh installation with the latest version (5.0.2) using npm and SQLite on Windows 11.
Here is the error log:

❯ npm run start                                                                                                                                ─╯ 

> my-strapi-project@0.1.0 start
> strapi start

[2024-10-05 06:16:38.641] error: @strapi\email\package.json couldn't be resolved
Error: @strapi\email\package.json couldn't be resolved
    at toDetailedDeclaration (C:\DEV\JAVASCRIPT\strapi\my-strapi-project\node_modules\@strapi\core\dist\loaders\plugins\get-enabled-plugins.js:65:17)
    at Module.getEnabledPlugins (C:\DEV\JAVASCRIPT\strapi\my-strapi-project\node_modules\@strapi\core\dist\loaders\plugins\get-enabled-plugins.js:83:10)
    at loadPlugins (C:\DEV\JAVASCRIPT\strapi\my-strapi-project\node_modules\@strapi\core\dist\loaders\plugins\index.js:96:50)
    at Module.loadApplicationContext (C:\DEV\JAVASCRIPT\strapi\my-strapi-project\node_modules\@strapi\core\dist\loaders\index.js:16:5)
    at Object.register (C:\DEV\JAVASCRIPT\strapi\my-strapi-project\node_modules\@strapi\core\dist\providers\registries.js:26:17)
    at Strapi.register (C:\DEV\JAVASCRIPT\strapi\my-strapi-project\node_modules\@strapi\core\dist\Strapi.js:322:32)
    at Strapi.load (C:\DEV\JAVASCRIPT\strapi\my-strapi-project\node_modules\@strapi\core\dist\Strapi.js:314:16)
    at Strapi.start (C:\DEV\JAVASCRIPT\strapi\my-strapi-project\node_modules\@strapi\core\dist\Strapi.js:207:20)
    at action (C:\DEV\JAVASCRIPT\strapi\my-strapi-project\node_modules\@strapi\strapi\dist\cli\commands\start.js:21:42)
[2024-10-05 06:16:38.643] info: Shutting down Strapi
