### ISSUE TITLE
Transfer Feature Hangs on Asset Transfer

### ISSUE THREAD

**Issue by MihaiSandor** [strapi/strapi#21068]
### Required System Information

- **Node.js version**: v20.12.2
- **NPM version**: 10.8.2
- **Strapi version**: 4.25.8
- **Database**: PostgreSQL
- **Operating system**: Darwin arm64 (macOS on ARM)
- **Project Language**: JavaScript (please confirm or correct to TypeScript if applicable)

### Describe the Bug

The asset transfer feature hangs during the transfer process. When attempting to transfer assets from a remote Strapi CMS deployed on Strapi Cloud to a local instance, the transfer begins but does not complete, persistently stalling at the assets transfer step.

### Steps to Reproduce the Behavior

1. Start the asset transfer via the command `yarn strapi transfer --from https://cms.domain.org/admin`.
2. Enter the necessary transfer token and confirm the deletion of local assets and database to proceed.
3. Confirm continuation despite schema differences between the source and destination.
4. Observe that the entities transfer completes successfully but the asset transfer hangs indefinitely (over 266 seconds observed with no completion).

### Expected Behavior

The transfer process should complete successfully without hanging, allowing all entities and assets to be transferred from the source to the destination within a reasonable time frame.

### Screenshots

*Not applicable*

### Code Snippets

```bash
yarn strapi transfer --from https://cms.domain.org/admin
? Please enter your transfer token for the remote Strapi source [hidden]
? The transfer will delete all the local Strapi assets and its database. Are you sure you want to proceed? Yes
[2024-08-21 19:22:34.754] warn: (Schema Integrity) Review workflows feature does not exist on destination
? There are differences in schema between the source and destination, and the data listed above will be lost. Are you sure you want to continue? Yes
Starting transfer...
✔ entities: 1265 transferred (size: 897.2 KB) (elapsed: 4581 ms)
⠇ assets: 511 transferred (size: 262.4 MB) (elapsed: 266200 ms) (1009.3 KB/s)
```

### Additional Context

This issue occurred under the development environment with Strapi Community Edition. The size of the assets being transferred is significant, and there might be an underlying issue with how large data transfers are handled or a potential timeout/interruption issue that isn't adequately surfaced in the logs.

**Comment by KubaZachacz** [comment]
Ok, what I've noticed after that I also got stuck with previous versions transfer from self hosted remote to local, 
is I used same config for S3 provider, and after I wrote a comment for previous issue, I've just skipped excluded files `--exclude files` in the cli transfer command, so it just pulled locally everything without touching bucket, and everything worked fine. Files stayed where they were but local media library got proper references. 
So maybe @MihaiSandor you can play around some providers config. 
But it general that transfers sometimes works sometimes don't for me. And as it just stuck on some unknown file it also used to crash with error on some other files previously....

**Comment by ryanvanderpol** [comment]
I have also been dealing with this issue. However, unlike @KubaZachacz, if I include the `--exclude files` option, all of my media has incorrect references (eg. image URLs are wrong, etc.)

The original issue here is for Strapi `v4`, but I'm on `v5.0.0` and still encountering this problem.

Looks like the related issues are more than 1 year old. I'm not sure why this has been such a low priority to resolve.

**Comment by hanpaine** [comment]
Hi @MihaiSandor thanks for raising this and your patience - I appreciate this must be frustrating. The team have been flat out working on v5 in recent months hence why some areas with issues have not been prioritised, however we are aiming to make improvements to the DTS in coming weeks. 

@ryanvanderpol I think the URL loss you're referring to is the same as #21027 ?

**Comment by Bassel17** [comment]
Hello, just to get more context are you only facing this with the pull transfer from cloud to local ?
or do you face the same thing if you attempt a push ?

**Comment by ryanvanderpol** [comment]
@Bassel17 I have only ever attempted a pull from cloud to local because I'm often trying to set up a dev environment that mirrors production. Content editing happens in prod because devs don't create the content.

**Comment by dylan-hoefsloot** [comment]
@Bassel17 I am having the same issue, but can confirm pushing content to production from local works fine, but pulling content from production from local will hang.

**Comment by MauricioKruijer** [comment]
I'm experiencing the same issue, I am using `"@strapi/provider-upload-aws-s3": "^5.5.0"` locally

**Comment by GifCo** [comment]
How is this still not fixed!!! To busy adding paid features to bother with this??  Its been literal years now.

**Comment by rafaell-lycan** [comment]
I've found a workaround for now:

```
npm run strapi transfer -- --to https://cms.domain.com/admin --exclude files
```

This will migrate your data if you don't have any assets from the application itself. Works fine if you have your assets on S3 or a different provider 👍

I hope Strapi Team fix it this soon 🙏

**Comment by Tekbits** [comment]
Just wanted to add that I also get the same issue....

**Comment by innerdvations** [comment]
I believe many cases of this have been fixed in 5.11.0 (both sides of the transfer, local and remote). If anyone who had this problem can try again in 5.11.0 and let us know in this thread:

- was it fixed or not?
- either way, let us know if you are using `from` or `to`, if you have a remote file provider, or anything else you feel might be relevant
- if it is still failing on 5.11.0, logs with the `--verbose` flag

That would help a lot to provide clues to what is happening. Thanks!

**Comment by innerdvations** [comment]
This should be fixed in the upcoming v5 release on Wednesday March 26. We are considering adding the fix to v4 as well, but I can't guarantee it or give a timeline.

**Comment by hanpaine** [comment]
Hi all; for now, we are not going to back-port this fix to V4. If you are not upgrading to v5, please start with updating your DTS package to 5.12.0 or later. We can reopen this if the issue is unresolved.

**Comment by karthicashokan** [comment]
The current system here is that issues remain open indefinitely until a new version is released, after which the older tickets are simply closed. This issue is still present in Strapi version 5.17.0 without any fix!
