### ISSUE TITLE
[Design] Disabled checkboxes in Super Admin settings have a blue border and the check hasn’t the right color

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#22032]
### Current design

![Image](https://github.com/user-attachments/assets/f4d5f1d6-57fc-410b-a357-5176cc7bd595)

### Expected design

![Image](https://github.com/user-attachments/assets/d1ae9803-2e24-4509-9a35-4e317ede4d58)

Figma file: https://www.figma.com/design/NmL2GP7zw2bS4G5CW1xVqm/%5BEXPERIMENTAL%5D-Strapi-CMS---UI-Kit?node-id=16985-51790&node-type=frame&t=7oMHD4xIfBLoVvKe-0

**Comment by mukulpadwal** [comment]
Hi @yanniskadiri,

I wanted to clarify a couple of things. It seems intentional to display the disabled checkboxes in a different way, perhaps to indicate that they can't be edited by super-users, while the editable ones are highlighted in purple. I could be mistaken, though.

If the goal is to standardize the color for all checkboxes, I’d be happy to take on this task.

**Comment by rami-pro** [comment]
@yanniskadiri  @mukulpadwal  it's indeed a styling issue in @strapi/design-system, I took the initiative to fix it at the following [PR](https://github.com/strapi/design-system/pull/1806)

**Comment by Adzouz** [comment]
Hi @yanniskadiri, I see that the checkboxes are now fixed and follow the correct design.
Feel free to reopen if you think it's necessary.
Thanks 🚀

**Comment by lucasboilly** [comment]
@Adzouz I still see them with the wrong design in the admin, could it be because it's in the last version of the DS? Or maybe it's additional CSS coming from the admin?

![Image](https://github.com/user-attachments/assets/621d55f0-9491-4d64-9ffb-98795120a48b)

**Comment by Adzouz** [comment]
Oops good catch, I wasn't looking at the right place. Reopening and will investigate!

**Comment by Adzouz** [comment]
Hi @lucasboilly, thanks again it was fixed and part of release 5.16.0 🚀
Closed now!
