### ISSUE TITLE
Locale Field Ignored During Content Creation via API in Strapi 5

### ISSUE THREAD

**Issue by Inkosar** [strapi/strapi#22135]
### Required System information

- Node.js version: 20.18.0
- NPM version: 
- Strapi version: 5.3.0
- Database: SQLite
- Operating system: Ubuntu 22.04
- Is your project Javascript or Typescript:

### Describe the bug

I'm encountering an issue with Strapi 5 when attempting to create localized content entries via the API. Specifically, when providing the locale field in the payload for a new entry, Strapi ignores the provided locale and instead defaults to the system's default locale.

### Steps to reproduce the behavior

1. The content type (words) has localization enabled.

2. Default locale is set to uk.

3. Send a POST request to create a new entry with a different locale (e.g., en or pl) via the API.

Example curl command:
curl -X POST http://localhost:1337/api/words \
-H "Authorization: Bearer YOUR_API_TOKEN" \
-H "Content-Type: application/json" \
-d '{
  "data": {
    "title": "Test Entry",
    "slug": "test-entry",
    "locale": "en",
    "transcription": "test-transcription"
  }
}'

### Expected behavior

The entry should be created with the locale specified in the payload (locale: "en").

### Actual behavior

The entry is always created using the default locale (uk), regardless of the locale specified in the request payload.

What I've Tried:

1. Change Default Locale:

2. Changing the default locale to en results in all entries being created in en, irrespective of the locale field in the request payload.

API Tests:
Tested the same POST request with different locales (en, pl).
The locale field in the response and database is always set to the default locale.

3. Lifecycle Hooks:
Verified that lifecycle hooks (beforeCreate, beforeUpdate) are not modifying the locale field during entry creation.
Manual Entry Creation:

Creating entries manually via the Admin Panel allows me to correctly select and assign locales.

### Logs

Here’s an example log when trying to create an entry in en:
json
{
  "data": {
    "id": 257,
    "documentId": "l1x7a83t179db7k4nacb5ys6",
    "title": "Test Entry",
    "transcription": "test-transcription",
    "slug": "test-entry",
    "createdAt": "2024-11-12T13:43:28.932Z",
    "updatedAt": "2024-11-12T13:43:28.932Z",
    "publishedAt": "2024-11-12T13:43:28.942Z",
    "locale": "uk",   // <--- Always defaults to the default locale
    "hanjawriting": null
  },
  "meta": {}
}

### Additional context

It seems that the locale field is either ignored or overwritten with the system's default locale during entry creation via the API. This prevents the creation of localized content in languages other than the default. I suggest that the API should correctly respect the locale field provided in the request payload.

Expected Outcome:
The API should honor the locale field provided in the request payload and create entries with the specified locale, instead of defaulting to the system’s default locale.

Thank you for your support in resolving this issue.

**Comment by codeit-ninja** [comment]
I am not sure why severity is only set to `medium` as this completly breaks the workings of localization.

**Comment by leomunizq** [comment]
it worked for me by specifying the language in the call url like this:

http://localhost:1337/api/articles?locale=en

**Comment by Inkosar** [comment]
If I fetch data, similar as in your example, fetching by locales works well but if I trying to import data to needed locale it save all data to one default locale. Here an example fragment of my json file where I set needed locale but it imports always to default uk locale.

[
  {
    "locale": "en",
    "title": "자연",
    "transcription": "jayeon",
--------

**Comment by codeit-ninja** [comment]
> it worked for me by specifying the language in the call url like this:
> 
> http://localhost:1337/api/articles?locale=en

We are talking about a POST request, not a GET request. In a POST request specifying the locale has no effect.

Sorry to say towards the strapi team. But I have completely dumped strapi from my stack. Its code design is horrible, to many inconsistenties, working out of web standards and breaking bugs.

**Comment by Inkosar** [comment]
UPD:
If we add locale to the url it imports to correct locale
Example curl command:
curl -X POST "http://localhost:1337/api/words?locale=en"
-H "Authorization: Bearer YOUR_API_TOKEN"
-H "Content-Type: application/json"
-d '{
"data": {
"title": "Test Entry",
"slug": "test-entry",
"transcription": "test-transcription"
}
}'

But how we can link created entries on different locales, for example "Test Entry" in en locale belongs to "Test Entry ukr" on uk language?

**Comment by Inkosar** [comment]
RESOLVED
it links via [PUT /api/restaurantsdocumentId?locale=en
according documentation https://docs.strapi.io/dev-docs/i18n

Before I tried to set locale via json but strapi set it via link. Now its clear for me and seems like here it is not bug.

**Comment by codeit-ninja** [comment]
> RESOLVED it links via [PUT /api/restaurantsdocumentId?locale=en according documentation https://docs.strapi.io/dev-docs/i18n
> 
> Before I tried to set locale via json but strapi set it via link. Now its clear for me and seems like here it is not bug.

It is not resolved, put and post are different types of requests. That its working in a put request does not resolve the issue, which is that the locale is ignored in a post request.

**Comment by Inkosar** [comment]
> It is not resolved, put and post are different types of requests. That its working in a put request does not resolve the issue, which is that the locale is ignored in a post request.

In my case curl -X POST "http://localhost:1337/api/words?locale=en" create new entry in en locale as well.
