### ISSUE TITLE
Can't use GraphQL in a Heroku instance

### ISSUE THREAD

**Issue by andre-av** [strapi/strapi#2276]
**Informations**
- **Node.js version**: 11.1.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.4.0
- **Database**: mLab

**What is the current behavior?**

Graphql playground and requests works fine on the local environment, but when I build it on Heroku I get this response when I request anything: 

`Status Code: 400 Bad Request`

Sometimes I get the data I want, other times server response is:

`{
  "error": "Response not successful: Received status code 400"
}
`

I tried using the git of graphql as a dependency in the plugin, also downgrading to 0.13.2, but still the same issue. Could this be an issue with graphql-strapi or something to do with Heroku? I can recall that everything was working fine until I updated to Strapi 14.

Thanks for the help.

**Steps to reproduce the problem**

- Created a new Strapi project
- Copied old generated apis
- Installed graphql plugin
- Pushed project to Heroku
- Tried to make a request to /graphql

**What is the expected behavior?**

**Suggested solutions**

**Comment by andre-av** [comment]
The response happens with any query: `

**Comment by belgianwolfie** [comment]
so this remains open ? Cannot use graphql at all on Heroku ?

**Comment by yareyaredesuyo** [comment]
Me too, in my case i cannot connect to graphql endpoint.

**Comment by yareyaredesuyo** [comment]
sorry it is just a playgroundAlways settings matter. I changed it true and it works at playground.

/plugins/graphql/config/settings.json 

```
{
  "endpoint": "/graphql",
  "shadowCRUD": true,
  "playgroundAlways": true,
  "depthLimit": 7,
  "amountLimit": 100
}
```

**Comment by yareyaredesuyo** [comment]
maybe related to this

https://github.com/apollographql/apollo-server/issues/1773

https://www.apollographql.com/docs/apollo-server/api/apollo-server.html#constructor-options-lt-ApolloServer-gt

**Comment by yareyaredesuyo** [comment]
OK.

add introspection: true params to plugins/graphql/hooks/index.js and it works well. 

```
const serverParams = {
  typeDefs,
  resolvers,
  context: async ({ ctx }) => ({
    context: ctx,
  }),
  validationRules: [depthLimit(strapi.plugins.graphql.config.depthLimit)],
  playground: false,
  introspection: true // add this param
};
```

**Comment by andre-av** [comment]
Ok, it seems it has to do with the parameter `instrospection` been `false` on production builds. This should be documented, or we could add it as an option in `packages/strapi-plugin-graphql/config/settings.json`. Shall I close this issue?

**Comment by lauriejim** [comment]
Fixed by this PR https://github.com/strapi/strapi/pull/2595

**Comment by jtan4nih** [comment]
This is not fixed even in strapi-plugin-graphql@3.0.0-alpha.26.2. When is it going to be merged/fixed?

**Comment by micheleriva** [comment]
Is it possible to configure this setting without having to wait for the PR to be included inside a release?

**Comment by lauriejim** [comment]
Hello @micheleriva , we are in beta `beta.17.5`
This issue is on the beta - it have been released from a wild.

**Comment by micheleriva** [comment]
Hi @lauriejim , I've also tried customizing the settings as written in the [docs](https://strapi.io/documentation/3.0.0-beta.x/plugins/graphql.html#configurations).

```json
{
  ...
  "introspection": true
}
```

but it doesn't work 😞 

At the moment I'm using the `3.0.0-beta.17.5` in production but the error persists

**Comment by lauriejim** [comment]
Hello @micheleriva.
Here your issue is due to the way configurations are applied.
[Here is the code](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/hooks/graphql/index.js#L69) that load configurations to setup the GraphQL server.
I suggest you open an issue about that OR just open a PR to allow `introspection` config.
I suggest you code it by yourself and submit a PR, it will be the fastest way to have to feature available in the next version.
Thank you.

**Comment by micheleriva** [comment]
Thank you @lauriejim ,
I'll dig into the code and I'll open a PR asap!

**Comment by BaptisteMonet** [comment]
I'm still having a problem with this 

    Strapi version: 3.4.1
    Database: postgresql

any idea ?

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
