### ISSUE TITLE
Pages randomly switch to loading spinner after already showing content normally for a few minutes

### ISSUE THREAD

**Issue by goguda** [strapi/strapi#22797]
### Node Version

20.18.2

### NPM/Yarn/PNPM Version

Yarn 1.22.22

### Strapi Version

5.9.0

### Operating System

Linux (Host: openSUSE Leap 15.6, app running in docker container under Alpine 3.21)

### Database

PostgreSQL

### Javascript or Typescript

Javascript

### Bug Description

After loading successfully and letting a page sit for a few minutes, the page may randomly switch to a loading spinner that never completes. Only refreshing the page brings back the content.

First visit:

![Image](https://github.com/user-attachments/assets/53b69538-65e0-4283-a480-8437d2daa547)

After 1-3 minutes of the page just sitting (seems pretty random):

![Image](https://github.com/user-attachments/assets/7a130d5b-1bb9-45cd-bdb1-cca306d67926)

The screenshots use a collection type page, but I've seen it happen on various other pages throughout the app (such as in the settings pages). It also doesn't happen every time; it seems very random, although it does seem to happen more frequently when the page is completely inactive (i.e. haven't interacted with the page for several minutes).

I also monitored the console and network requests in my browser during the switch to see if there might be some request or something logged that might indicate the issue, but there is nothing logged and no network requests made between the page loading successfully and switching to the loading spinner. Nothing in the server logs either.

This instance was also recently upgraded from 4.25.20 to 5.9.0. Not sure if this might have something to do with it.

If other people aren't able to reproduce this I can perhaps try making a skeleton reproduction of our app and posting it. Not sure if anyone else is seeing this since I don't see another issue on it.

### Steps to Reproduce

1. Visit any page that contains a potential loading state
2. Just let the page sit for a few minutes after loading
3. Observe it switch from the content to the loading spinner

If it doesn't happen after 1-3 minutes, you might need to refresh the page and try again.

### Expected Behavior

Pages should not randomly switch from content to loading state

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

**Comment by IceBreaker8** [comment]
Got the same problem here. Strapi v5.9.0, node v20.18.0, npm 10.8.2, postgres 16

**Comment by Lordtyger** [comment]
Same issue. The page refreshes every few minutes. I thought it was something to do with the JWT but I have set that to 7 days and it is still refreshing. 
Strapi Version: v5.8.1
Operating System:
Database: mysql
Node Version: v20.3.0
NPM Version: 9.6.7

**Comment by goguda** [comment]
> Same issue. The page refreshes every few minutes. I thought it was something to do with the JWT but I have set that to 7 days and it is still refreshing. So my issue is slightly different but related. I dont have to manually refresh the page. Strapi Version: v5.8.1 Operating System: Database: mysql Node Version: v20.3.0 NPM Version: 9.6.7

Interesting, what browser are you using? Firefox here.

**Comment by goguda** [comment]
Observed another variation of (what could be) the same issue today, no loading spinner but all content blocks randomly disappeared while editing...

![Image](https://github.com/user-attachments/assets/4cfa9b2e-51b1-472f-996c-e518a0eb4382)

**Comment by derrickmehaffy** [comment]
Fixed in 5.10.x+ it was fixed in either 5.10.0 or 5.10.1 but we had a hotfix up to 5.10.2

**Comment by zjjtm** [comment]
This problem still remain on 5.10.2

The refresh is triggered at approximately 2 minutes and 3 seconds:
https://github.com/user-attachments/assets/e0529c39-075b-407b-88ff-d11885406777

**Comment by Lordtyger** [comment]
> > Same issue. The page refreshes every few minutes. I thought it was something to do with the JWT but I have set that to 7 days and it is still refreshing. So my issue is slightly different but related. I dont have to manually refresh the page. Strapi Version: v5.8.1 Operating System: Database: mysql Node Version: v20.3.0 NPM Version: 9.6.7
> 
> Interesting, what browser are you using? Firefox here.

I was using Chrome Version 131.0.6778.86. I updated to the latest Strapi and it was still doing the refresh. I changed to Safari so I didnt have to deal with CORS issues and the constant refreshing has stopped.

**Comment by DusanDragulaGR** [comment]
Same issue for me on v5.10.3 and also on Safari and Chrome. Randomly showing Loading spinner when I'm creating content and then I must to refresh page (and losing data).
I think it happens only when I'm creating new document, maybe issue with obtaining documentId on this page / line?

https://github.com/strapi/strapi/blob/fdac61dd05ca665168f51f655f1d165b55ec4231/packages/core/content-manager/admin/src/pages/EditView/EditViewPage.tsx#L103

**Comment by goguda** [comment]
Interestingly enough, this issue seems completely fixed for us on 5.10.2. I haven't seen it happen all week on Firefox, and I just let Chrome sit for awhile without it happening, too.

There must be more than one thing triggering this issue.

**Comment by zjjtm** [comment]
Still happen on v5.10.3 under Chrome

**Comment by denvermullets** [comment]
Still happening on v5.10.3 using Chrome, for me and a coworker

**Comment by DusanDragulaGR** [comment]
I initialized a completely new empty Strapi v5. Then, I copied the API and config from my existing version, which was causing the mentioned issues. First, I regenerated the types using `npm run develop`. After deploying this version to production, I no longer experienced the loading issue. Previously, I encountered problems every time I created new content. Since making this adjustment, everything has been running smoothly for three days.

**Comment by goguda** [comment]
I wonder if everyone here has done a full build since updating to 5.10+?

We didn't have to create a new project to resolve this, but we do run a full build any time we're upgrading Strapi dependencies. We ran a full build going from 5.9.0 to 5.10.2, and since that the issue has been resolved for us.

**Comment by javialon26** [comment]
It's still happening on v5.0.14. I'm rebuilding the application on every deployment. I use a custom docker file, ppm, and turborepo. On v4, everything works as expected; I updated the code base from v4 to v5.

NodeJs version: 20.17.0

Dockerfile:
```
ARG NODE_VERSION

FROM node:${NODE_VERSION}-alpine AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN npm i -g -f --ignore-scripts corepack@0.31.0 && corepack enable

WORKDIR /app

# Builder stage - Prune cms app with Turborepo
FROM base AS builder

COPY . .
RUN corepack pnpm add -g --ignore-scripts turbo@^2
RUN corepack pnpm exec turbo prune --scope=@repo/cms --docker

# Installer stage - Add lockfile and package.json's of isolated subworkspace
FROM base AS installer

# First install the dependencies (as they change less often)
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml

RUN --mount=type=cache,id=pnpm,target=/pnpm/store corepack pnpm install --frozen-lockfile

# Build the project
COPY --from=builder /app/out/full/ .
COPY --from=builder /app/turbo.json .
RUN corepack pnpm run tasks:build --filter=@repo/cms

# Runner stage - Copy files and set the CMD
FROM base AS runner

ENV NODE_ENV="production"

COPY --from=installer --chmod=0755 /app/node_modules /app/node_modules
COPY --from=installer --chmod=0755 /app/apps/cms/node_modules /app/apps/cms/node_modules
COPY --from=installer --chmod=0755 /app/apps/cms/dist /app/apps/cms/dist
COPY --from=installer --chmod=0755 /app/apps/cms/database /app/apps/cms/database
COPY --from=installer --chmod=0755 /app/apps/cms/package.json /app/apps/cms/package.json
COPY --from=installer --chmod=0755 /app/apps/cms/favicon.png /app/apps/cms/favicon.png
COPY --from=installer --chmod=0755 /app/apps/cms/public/robots.txt /app/apps/cms/public/robots.txt
COPY --from=installer --chmod=0755 /app/apps/cms/types /app/apps/cms/types

WORKDIR /app/apps/cms

RUN mkdir -p public/uploads

USER node

CMD ["node", "dist/server"]
```

Do you have any ideas or logs that I can check?

**Comment by glenturner** [comment]
Here's a video of what's happening, will this issue ever get prioritized?

https://www.loom.com/share/f2e01b98b8bc42cf9df198e260f88aa9?sid=234653e3-e50f-4cca-8669-d8bbf141d587
