### ISSUE TITLE
Strapi Dashboard only show Content Types after a fresh login. Once browser refreshes only Users is shown.

### ISSUE THREAD

**Issue by nom4da** [strapi/strapi#2306]
**Informations**
- **Node.js version**:  10.13.0
- **npm version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.14.5
- **Database**:  MongoDB 3.4.17
- **Operating system**: Ubuntu 16.04

**What is the current behavior?**
Created content types are only shown on a fresh login. If you refresh browser only Users is shown.

**Steps to reproduce the problem**
1. Create a couple (or one) of content types. 
2. Log out.
3. Refresh browser
4. Login. You should see al content types created.
5. Refresh browser. Created content types will disappear, only Users is shown. 

**What is the expected behavior?**
All content types must be listed always.

**Suggested solutions**
I notice that on browser refresh after login, the following request does not happen:
http://localhost:1337/content-manager/models , thus the content types are not loaded. I see this request happens in plugins/content-manager/bootstrap.js, but seems is only running once after logging in. Why?

**Comment by mnlbox** [comment]
Me too :cry:

**Comment by kameas** [comment]
I re-created the project with alpha 14.5 and the problem is solved

**Comment by derrickmehaffy** [comment]
For those of you who tried to migrate using the wiki migration article, you may try instead to use my method to update: https://github.com/strapi/strapi/issues/1880

My guess is there was a problem when you copied over the new build folders somewhere.

**Comment by derrickmehaffy** [comment]
@mnlbox @kameas @nom4da 

I'm going to guess all 3 of you are on Firefox and not chrome, most likely OSX as your client OS?

**Comment by derrickmehaffy** [comment]
Also make sure all of you completely clear your browser cache. Your browser may have an old cached copy of 14.4's files

**Comment by derrickmehaffy** [comment]
@soupette @lauriejim I could not reproduce this issue on Ubuntu Chrome nor Firefox.

**Comment by mnlbox** [comment]
@derrickmehaffy I'm using Linux Mint + Firefox.

**Comment by derrickmehaffy** [comment]
same @mnlbox and I can't reproduce this :cry:

**Comment by soupette** [comment]
It should have been fixed in 14.5

> I notice that on browser refresh after login, the following request does not happen:
http://localhost:1337/content-manager/models , thus the content types are not loaded. I see this request happens in plugins/content-manager/bootstrap.js, but seems is only running once after logging in. Why?

If you have the `users-permissions` plugin installed, you need to be authenticated to get the data so the request is made after login in.

**Comment by merijnvanessen** [comment]
It seems that only when fresh logged in the strapi admin, 
the GET to models is in my XHR requests

Fresh login
![schermafbeelding 2018-11-14 om 12 27 26](https://user-images.githubusercontent.com/23075300/48480024-657f6e80-e809-11e8-996f-1bf1a8a33d72.png)

Refresh 
![schermafbeelding 2018-11-14 om 12 30 55](https://user-images.githubusercontent.com/23075300/48480022-644e4180-e809-11e8-9397-45d291fad5b4.png)

Sorry for the crooked screenshots

osx 10.11.6
firefox 63.0.1 
nodejs v10.6.0
npm 6.1.0
strapi 3.0.0-alpha.14.5

**Comment by nom4da** [comment]
I created a new project on Strapi 14.5 and issue persist. On both, Chrome and Firefox. 

Here's Firefox:
![image](https://user-images.githubusercontent.com/1816294/48483450-7b793900-e7e1-11e8-8084-d4c8f56a743e.png)

After refresh:
![image](https://user-images.githubusercontent.com/1816294/48483476-8d5adc00-e7e1-11e8-8565-1ec87695fdf6.png)

**Comment by derrickmehaffy** [comment]
Provide your browser console screenshot please to see if there is an error being given

**Comment by derrickmehaffy** [comment]
Also try opening the admin in incognito mode and see if the same issue

**Comment by nom4da** [comment]
On fresh login on Chrome (incognito mode):
![image](https://user-images.githubusercontent.com/1816294/48484068-250cfa00-e7e3-11e8-9647-de7ef487b58d.png)

On refresh:
![image](https://user-images.githubusercontent.com/1816294/48484109-44a42280-e7e3-11e8-8bf5-1175e9a962f2.png)

**Comment by soupette** [comment]
@nom4da do you have a repository I can check I'm unable to reproduce the bug

**Comment by nom4da** [comment]
All I did was "Strapi new test", created a "test" content type, and tested with it.

Here's the repository:
git@github.com:nom4da/strapitest.git

**Comment by nom4da** [comment]
@soupette oh wow, I recall my global version being 14.5 when I created "test".

I created a new one, made sure it was 14.5, and it works. Sorry for that guys. Will double check next time I think there's an issue. 

Thanks a lot for everything. This is a great tool. 
Best

**Comment by merijnvanessen** [comment]
I tested it with a new install instead of updating my current app. 
Now all content types are visible in firefox. Well done!
Then I'd better make a new install for my current app and try to migrate the data
