### ISSUE TITLE
Duplicate relations with identical documentId returned

### ISSUE THREAD

**Issue by channyeintun** [strapi/strapi#23524]
### Node Version

20

### NPM/Yarn/PNPM Version

10.8.2

### Strapi Version

5.13.0

### Operating System

MacOS

### Database

PostgreSQL

### Javascript or Typescript

Typescript

### Reproduction URL

https://github.com/channyeintun/strapi-starter-duplicate-relations

### Bug Description

With default sample data for articles and categories,
I used `"@strapi/plugin-graphql": "^5.13.0"` to query categories together with its articles. The reponse includes articles duplicating.
Query is as follows: 
```
query Categories {
  categories {
    name
    articles {
      documentId
      title
    }
  }
}
```
The response is as follows:
```
{
  "data": {
    "categories": [
      {
        "name": "test",
        "articles": [
          {
            "documentId": "zb5p1h2ct1ays90gypvy28jb",
            "title": "test"
          },
          {
            "documentId": "zb5p1h2ct1ays90gypvy28jb",
            "title": "test"
          }
        ]
      }
    ]
  }
}
```

You can see two articles with same documentId.
I have not enabled internationalization.
I only created a single article and a single category with default sample content types and relationships.

### Steps to Reproduce

1. Clone reproduced repo and go to the location.
2. Run docker command to run postgres container as described in README.md
3. Run `npm install` 
4. Run `npm run dev`
5. Add sample data for category and article in the admin panel
6. Go to `localhost:1337/graphql` and run the query described above and see the result

### Expected Behavior

Relations data should not have items duplicated.

### Logs

```shell

```

### Code Snippets

```
query Categories {
  categories {
    name
    articles {
      documentId
      title
    }
  }
}
```

### Media

<img width="957" alt="Image" src="https://github.com/user-attachments/assets/f0d11e06-224a-48e9-9304-c2c74965ec8b" />

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

**Comment by amarinsam** [comment]
I'm running into this as well.  For each single piece of content in Strapi CMS, the Postgres database returns two entry.  However, when I make a request to the relevant Strapi deployed endpoint via the REST API, it returns the correct content, deduplicated.  

I also tested that, saving a document as a draft, and not publishing it only creates 1 row in Postgres.

I'm wondering if Strapi stores drafts and published posts as separate entries?

**Comment by alexortizl** [comment]
Also running into this. I played around with the query and noticed that is returning `"publishedAt": null` for one document and `"publishedAt": "2025-05-30T14:17:15.629Z"` for the other. Seems to me that it's returning both the published and draft versions of the document, I also made sure to send `"status": "PUBLISHED"` in the query but still same results. This is holding back an important deployment for one of our apps.

**Comment by PeterBowater** [comment]
We are seeing similar responses when using REST, so it is not limited to graphql.

**Comment by Krislunde** [comment]
I'm also here because a relation field (one to many) in a dynamic zone component is returning duplicate results (published and draft) in the REST api.

Example query:
```
{
    status: 'published',
      fields: ['title'],
          populate: {
              content: {
                  on: {
                      'hero': {
                          fields: ['title', 'body'],
                          populate: {
                              featuredProducts: {
                              populate: {
                                  products: {
                                      fields: ['title', 'slug', 'amount'],
                                  }
                              }
                          }
                      }
                  },
              }
          }
      }
}
```

Example result: 
```
{
    "data": {
        "id": 1,
        "documentId": "hbsculg9a7vta8locwnm260m",
        "title": "Home",
        "content": [
            {
                "__component": "hero",
                "id": 1,
                "title": "title goes here",
                "body": "more of a description goes here",
                "featuredProducts": {
                    "id": 1,
                    "title": "another title here",
                    "products": [
                        {
                            "id": 79,
                            "title": "Testsssss",
                            "slug": "testss",
                            "amount": "360.00",
                            "createdAt": "2025-06-02T15:24:16.629Z",
                            "updatedAt": "2025-06-02T16:56:10.791Z",
                            "publishedAt": null,
                            "documentId": "btspenkfcizvag7yf6lkr4k4"
                        },
                        {
                            "id": 80,
                            "title": "Testsssss",
                            "slug": "testss",
                            "amount": "360.00",
                            "createdAt": "2025-06-02T15:24:16.629Z",
                            "updatedAt": "2025-06-02T16:56:10.791Z",
                            "publishedAt": "2025-06-02T16:56:10.854Z",
                            "documentId": "btspenkfcizvag7yf6lkr4k4" 
                        }
                    ]
                }
            }
        ]
    }
}
```

**Comment by alexandrebodin** [comment]
Hello everyone, 

Can you please share the schema.json files you are using ? we are not able to reproduce with just this level of details 🙏 Can you provide:

- schema.json configs (of both types)
- the full requests you are making (REST in particular what params etc)

**Comment by channyeintun** [comment]
> Hello everyone,
> 
> Can you please share the schema.json files you are using ? we are not able to reproduce with just this level of details 🙏 Can you provide:
> 
> * schema.json configs (of both types)
> * the full requests you are making (REST in particular what params etc)

Have you checked the Reproduction URL?
You got every details there.

**Comment by remidej** [comment]
> I also tested that, saving a document as a draft, and not publishing it only creates 1 row in Postgres.
> I'm wondering if Strapi stores drafts and published posts as separate entries?

@amarinsam yes, having rows in your database is normal, this is what powers our draft & publish feature with the new "modified" status. It's just an implementation detail on our end however, when querying the content API or the document service you should never see both versions of the same entry. We're looking into it

**Comment by alexandrebodin** [comment]
> > Hello everyone,
> > Can you please share the schema.json files you are using ? we are not able to reproduce with just this level of details 🙏 Can you provide:
> > 
> > * schema.json configs (of both types)
> > * the full requests you are making (REST in particular what params etc)
> 
> Have you checked the Reproduction URL? You got every details there.

Yup we only got yours, and right now can't reproduce. have you done a v4 to v5 migration by any chance ?

**Comment by channyeintun** [comment]
@alexandrebodin I've reproduced it using Strapi v5.

**Comment by channyeintun** [comment]
@alexandrebodin It only happens when I use strapi-graphql plugin. It's ok in strapi client.

**Comment by markkaylor** [comment]
I am able to reproduce the issue now with postgresql and graphql. 
Unable tor reproduce in the REST response. ~Un~able to reproduce with sqlite

**Comment by markkaylor** [comment]
@channyeintun I'm still investigating and working on a fix but in the meantime as a workaround you should be able to filter the published related documents with a query like:

```
query Categories {
  categories {
    name
    articles(filters: {publishedAt: {null: false}})  {
      documentId
      title
    }
  }
}
```

**Comment by channyeintun** [comment]
> @channyeintun I'm still investigating and working on a fix but in the meantime as a workaround you should be able to filter the published related documents with a query like:
> 
> ```
> query Categories {
>   categories {
>     name
>     articles(filters: {publishedAt: {null: false}})  {
>       documentId
>       title
>     }
>   }
> }
> ```

No worry. I used strapi client for that.

**Comment by markkaylor** [comment]
Hello @channyeintun  @Krislunde #23673 I believe should resolve both of your issues. I've created an experimental release. If you are able to test it that would be very helpful 🙏 

```
npx create-strapi-app@0.0.0-experimental.74ebdf402d90857bc7282394855d43aad6d283e6
```

**Comment by channyeintun** [comment]
After checking, I found that it is still happening exactly the same as before.

**Comment by channyeintun** [comment]
@markkaylor Here're the steps I've done to check the issue:

1. Create the project using `npx create-strapi-app@0.0.0-experimental.74ebdf402d90857bc7282394855d43aad6d283e6`
2. Select `postgres` for database
3. Install strapi-graphql plugin using `npm install @strapi/plugin-graphql --force`
4. In case you need to run postgres using docker, use this `docker run --name postgres-strapi -e POSTGRES_DB=strapi -e POSTGRES_USER=strapi -e POSTGRES_PASSWORD=strapi -p 5432:5432 -d postgres`
5. Create sample content for category and article in content builder
6. Test the issue in graphql playground `localhost:1337/graphql` by using the following query:
```
query Categories {
  categories {
    name
    articles {
      documentId
      title
    }
  }
}
```

**Comment by markkaylor** [comment]
> [@markkaylor](https://github.com/markkaylor) Here're the steps I've done to check the issue:
> 
> 1. Create the project using `npx create-strapi-app@0.0.0-experimental.74ebdf402d90857bc7282394855d43aad6d283e6`
> 2. Select `postgres` for database
> 3. Install strapi-graphql plugin using `npm install @strapi/plugin-graphql --force`
> 4. In case you need to run postgres using docker, use this `docker run --name postgres-strapi -e POSTGRES_DB=strapi -e POSTGRES_USER=strapi -e POSTGRES_PASSWORD=strapi -p 5432:5432 -d postgres`
> 5. Create sample content for category and article in content builder
> 6. Test the issue in graphql playground `localhost:1337/graphql` by using the following query:
> 
> ```
> query Categories {
>   categories {
>     name
>     articles {
>       documentId
>       title
>     }
>   }
> }
> ```


Thanks for testing! Sorry I forgot to mention you have to install graphql with the same experimental version

```
  "dependencies": {
    "@strapi/plugin-cloud": "0.0.0-experimental.74ebdf402d90857bc7282394855d43aad6d283e6",
    "@strapi/plugin-graphql": "0.0.0-experimental.74ebdf402d90857bc7282394855d43aad6d283e6",
    "@strapi/plugin-users-permissions": "0.0.0-experimental.74ebdf402d90857bc7282394855d43aad6d283e6",
    "@strapi/strapi": "0.0.0-experimental.74ebdf402d90857bc7282394855d43aad6d283e6",
    "better-sqlite3": "11.3.0",
    "fs-extra": "^10.0.0",
    "mime-types": "^2.1.27",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.0.0",
    "styled-components": "^6.0.0"
  },
```

with npm I had to do `npm install @strapi/@0.0.0-experimental.74ebdf402d90857bc7282394855d43aad6d283e6  -f` for this

**Comment by Krislunde** [comment]
@markkaylor That experimental release actually seems to have solved the issue for me, using the rest api (on mysql, if that matters).

Tested with the same scenario I had issues with on my real project. A component in a dynamic zone with a nested relational field. Both with and without a nested component inside the parent dynamic zone component: 

Request: 
/api/home?fields[0]=title&populate[dynamiczone][on][flex.hero][fields][0]=title&populate[dynamiczone][on][flex.hero][populate][products][fields][0]=title&populate[dynamiczone][on][flex.hero][populate][products][populate][image][fields][0]=url&populate[dynamiczone][on][flex.hero][populate][products][populate][image][fields][1]=alternativeText

```
{
	fields: ['title'],
	populate: {
		dynamiczone: {
			on: {
				'flex.hero': {
					fields: ['title', 'price'],
					populate: {
						products: {
							fields: ['title'],
							populate: {
								image: {
									fields: ['url', 'alternativeText'],
								}
							}
						}
					}
				}
			}
		}
	},
}
```

Response: 

```
{
	"data": {
		"id": 5,
		"documentId": "rwpr6paokzxwi7q38uqaqye9",
		"title": "This is the title",
		"dynamiczone": [
			{
				"__component": "flex.hero",
				"id": 5,
				"title": "This is the hero title",
				"products": [
					{
						"id": 4,
						"documentId": "ua0yqjkrvpkodghgcg81ykrt",
						"title": "This is product B",
						"image": {
							"id": 2,
							"documentId": "emzin79jd7rbc5sbyctetx9t",
							"url": "/uploads/stockists_2_37e1d1e81c.jpg",
							"alternativeText": null
						}
					},
					{
						"id": 2,
						"documentId": "tzv24o72ziyeu5z8f9z6vi8f",
						"title": "This is product A",
						"image": {
							"id": 1,
							"documentId": "v2m35vyj8h28yg94abtt69bu",
							"url": "/uploads/noosa_surf_f940099d49.jpg",
							"alternativeText": null
						}
					}
				]
			}
		]
	}
}
```

And with a nested component inside the `dynamiczone` 

/api/home?fields[0]=title&populate[dynamiczone][on][flex.herotwo][fields][0]=title&populate[dynamiczone][on][flex.herotwo][populate][featuredProducts][fields][0]=title&populate[dynamiczone][on][flex.herotwo][populate][featuredProducts][populate][products][fields][0]=title&populate[dynamiczone][on][flex.herotwo][populate][featuredProducts][populate][products][fields][1]=price&populate[dynamiczone][on][flex.herotwo][populate][featuredProducts][populate][products][populate][image][fields][0]=url&populate[dynamiczone][on][flex.herotwo][populate][featuredProducts][populate][products][populate][image][fields][1]=alternativeText

```
{
	fields: ['title'],
	populate: {
		dynamiczone: {
			on: {
				'flex.herotwo': {
					fields: ['title'],
					populate: {
						featuredProducts: {
							fields: ['title'],
							populate: {
								products: {
									fields: ['title', 'price'],
									populate: {
										image: {
											fields: ['url', 'alternativeText'],
										}
									}
								}
							}
						}
					}
				}
			}
		}
	},
}
```

Response: 

```
{
	"data": {
		"id": 5,
		"documentId": "rwpr6paokzxwi7q38uqaqye9",
		"title": "This is the title",
		"dynamiczone": [
			{
				"__component": "flex.herotwo",
				"id": 3,
				"title": "This is the herotwo title",
				"featuredProducts": {
					"id": 3,
					"title": "Featured Products nested component title",
					"products": [
						{
							"id": 2,
							"documentId": "tzv24o72ziyeu5z8f9z6vi8f",
							"title": "This is product A",
							"price": 50,
							"image": {
								"id": 1,
								"documentId": "v2m35vyj8h28yg94abtt69bu",
								"url": "/uploads/noosa_surf_f940099d49.jpg",
								"alternativeText": null
							}
						},
						{
							"id": 4,
							"documentId": "ua0yqjkrvpkodghgcg81ykrt",
							"title": "This is product B",
							"price": 20,
							"image": {
								"id": 2,
								"documentId": "emzin79jd7rbc5sbyctetx9t",
								"url": "/uploads/stockists_2_37e1d1e81c.jpg",
								"alternativeText": null
							}
						}
					]
				}
			}
		]
	}
}
```

Fantastic! :)

Any ETA on a potential build release?

**Comment by markkaylor** [comment]
@Krislunde awesome thanks for confirming! 

> Any ETA on a potential build release?

I'm doing my best to get this merged and in the release next Wednesday

**Comment by channyeintun** [comment]
> > [@markkaylor](https://github.com/markkaylor) Here're the steps I've done to check the issue:
> > 
> > 1. Create the project using `npx create-strapi-app@0.0.0-experimental.74ebdf402d90857bc7282394855d43aad6d283e6`
> > 2. Select `postgres` for database
> > 3. Install strapi-graphql plugin using `npm install @strapi/plugin-graphql --force`
> > 4. In case you need to run postgres using docker, use this `docker run --name postgres-strapi -e POSTGRES_DB=strapi -e POSTGRES_USER=strapi -e POSTGRES_PASSWORD=strapi -p 5432:5432 -d postgres`
> > 5. Create sample content for category and article in content builder
> > 6. Test the issue in graphql playground `localhost:1337/graphql` by using the following query:
> > 
> > ```
> > query Categories {
> >   categories {
> >     name
> >     articles {
> >       documentId
> >       title
> >     }
> >   }
> > }
> > ```
> 
> Thanks for testing! Sorry I forgot to mention you have to install graphql with the same experimental version
> 
> ```
>   "dependencies": {
>     "@strapi/plugin-cloud": "0.0.0-experimental.74ebdf402d90857bc7282394855d43aad6d283e6",
>     "@strapi/plugin-graphql": "0.0.0-experimental.74ebdf402d90857bc7282394855d43aad6d283e6",
>     "@strapi/plugin-users-permissions": "0.0.0-experimental.74ebdf402d90857bc7282394855d43aad6d283e6",
>     "@strapi/strapi": "0.0.0-experimental.74ebdf402d90857bc7282394855d43aad6d283e6",
>     "better-sqlite3": "11.3.0",
>     "fs-extra": "^10.0.0",
>     "mime-types": "^2.1.27",
>     "react": "^18.0.0",
>     "react-dom": "^18.0.0",
>     "react-router-dom": "^6.0.0",
>     "styled-components": "^6.0.0"
>   },
> ```
> 
> with npm I had to do `npm install @strapi/@0.0.0-experimental.74ebdf402d90857bc7282394855d43aad6d283e6 -f` for this

@markkaylor  I tested again and it works perfectly. I really appreciate you for putting effort into this. Thanks for your precious time.

**Comment by markkaylor** [comment]
@channyeintun awesome thanks so much for testing

**Comment by broksonic21** [comment]
@markkaylor We are seeing after we tried upgrading to 5.15.1 (that has this change) that our graphql is now returning _no content_ for dynamic zones for pages that are published, but we are requesting the draft versions of. What's the correct approach to query those now - we used to get results

**Comment by markkaylor** [comment]
> [@markkaylor](https://github.com/markkaylor) We are seeing after we tried upgrading to 5.15.1 (that has this change) that our graphql is now returning _no content_ for dynamic zones for pages that are published, but we are requesting the draft versions of. What's the correct approach to query those now - we used to get results

I will look into it today. If you could share an example schema and query to reproduce that would be very helpful.

**Comment by markkaylor** [comment]
@broksonic21 I'm able to reproduce the issue 😢 

When requesting a draft document we should get draft for the parent document and draft related documents all the way down. This works for the root level (issue reported by the OP). For DZ components with relations, the workaround is to request the draft document AND filter the dz component relation. 

Example query:

```
query Articles {
  articles(status: DRAFT) {
    documentId
    publishedAt
    categories {
      documentId
      name
      locale
      publishedAt
    }
    dz {
      ... on ComponentDefaultRelations {
        categories(filters: { publishedAt:  {
           notNull: false
        }}) {
          documentId
          name
          locale
          publishedAt
        }
      }
    }
  }
}
```

https://github.com/user-attachments/assets/bed55d53-af33-4856-82ed-3dd6bb3ab028

Side note: This works as expected for the REST API with no additional filtering

I will look into a fix asap

**Comment by broksonic21** [comment]
@markkaylor thanks! Sorry, you found it before I could work up a repro. Thanks for digging in and fix in advance!

**Comment by markkaylor** [comment]
@broksonic21 I've created an experimental release for testing. If you have the time to test the fix that could be really helpful 🙏 

`0.0.0-experimental.ae2010c73ea60e398b726874a9b7b2bf3faada51`

See instructions here: https://github.com/strapi/strapi/issues/23524#issuecomment-2949280982

**Comment by yehudabortz** [comment]
@markkaylor Testing this out on behalf of @broksonic21. Content is still not being return with `0.0.0-experimental.ae2010c73ea60e398b726874a9b7b2bf3faada51`.

**Comment by markkaylor** [comment]
> [@markkaylor](https://github.com/markkaylor) Testing this out on behalf of [@broksonic21](https://github.com/broksonic21). Content is still not being return with `0.0.0-experimental.ae2010c73ea60e398b726874a9b7b2bf3faada51`.


Thank you @yehudabortz for testing. Could you maybe share some more context about how you setup to test it and the queries you ran?

I just tested the experimental and see it working. See video below.

Here's what I did:

I created a new strapi app and selected the option to create an app with a content structure and data

`npx create-strapi-app@0.0.0-experimental.ae2010c73ea60e398b726874a9b7b2bf3faada51`

Then I installed graphql plugin with:

`npm install -f @strapi/plugin-graphql@0.0.0-experimental.ae2010c73ea60e398b726874a9b7b2bf3faada51`

I updated category to have draft and published. On the category content-type I added a dynamic zone with a component containing a toMany relation to articles.

https://github.com/user-attachments/assets/d11b7a94-6ed7-446d-bd82-7cd9b679b00a

**Comment by markkaylor** [comment]
Possibly related: https://github.com/strapi/strapi/issues/23759.

Confirmed: non draft and publish relations on a draft and publish parent are not returned when requesting the parent as draft. 
Expected: non draft and publish relations should always be returned regardless of requests parent publication state

**Comment by yehudabortz** [comment]
@markkaylor Here is my query. 

Essentially, it is  a page with a component that references a collection of other prefilled components. All works normally when the status is `PUBLISHED`, but breaks when `DRAFT`.  

### Query
```graphql
query Query($status: PublicationStatus, $documentId: ID!) {
  page(documentId: $documentId, status:$status) {
    components {
      ... on ComponentTemplatesSharedComponent {
        id
        instance {
          components {
            ... on ComponentOrganismsMegaNavigation {
              id
              logo {
                height
              }
              loginButton {
                label
              }
              getStartedButton {
                label
              }
            }
          }
        }
      }
    }
  }
}
```

### Params

```json
{
  "status": "DRAFT",
  "documentId": "...."
}
```

#### Response

```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field ComponentOrganismsMegaNavigation.logo.",
      "locations": [
        {
          "line": 10,
          "column": 15
        }
      ],
      "path": [
        "page",
        "components",
        3,
        "instance",
        "components",
        0,
        "logo"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "Error: Cannot return null for non-nullable field ComponentOrganismsMegaNavigation.logo.",
          "    at completeValue (/node_modules/graphql/execution/execute.js:613:13)",
          "    at /node_modules/graphql/execution/execute.js:505:9",
          "    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)",
          "    at async Promise.all (index 1)",
          "    at async Promise.all (index 0)",
          "    at async Promise.all (index 0)",
          "    at async Promise.all (index 1)",
          "    at async Promise.all (index 3)",
          "    at async Promise.all (index 0)",
          "    at async Promise.all (index 0)"
        ]
      }
    }
  ],
  "data": {
    "page": {
      "components": [
        {},
        {},
        {},
        {
          "id": "1281",
          "instance": {
            "components": [
              null
            ]
          }
        },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {
          "id": "1282",
          "instance": {
            "components": [
              {}
            ]
          }
        }
      ]
    }
  }
}
```

--- 

#### package.json
```json
"@strapi/strapi": "0.0.0-experimental.ae2010c73ea60e398b726874a9b7b2bf3faada51",
"@strapi/plugin-users-permissions": "0.0.0-experimental.ae2010c73ea60e398b726874a9b7b2bf3faada51",
"@strapi/plugin-graphql": "0.0.0-experimental.ae2010c73ea60e398b726874a9b7b2bf3faada51",
"@strapi/plugin-users-permissions": "0.0.0-experimental.ae2010c73ea60e398b726874a9b7b2bf3faada51",
```

**Comment by yehudabortz** [comment]
@markkaylor This also only occurs when there is an image nested within my query.

**Comment by yehudabortz** [comment]
@markkaylor `0.0.0-experimental.cf7b5567d5aec466707a9d9685676df38c5b7c5c` seems to have resolved this issue!

**Comment by markkaylor** [comment]
@dmitrysmagin for your issue on https://github.com/strapi/strapi/issues/23759 I've pushed a fix and created a new experimental release: `0.0.0-experimental.cf7b5567d5aec466707a9d9685676df38c5b7c5c`

@yehudabortz thanks for the information. I think in your case you have relations that do NOT have draft and publish. If that is the case then you could try this experimental as well. 

We are still testing this internally as well. I have tested every type of relation with and without draft and publish: https://github.com/strapi/strapi/pull/23737#issuecomment-2980635007

**Comment by markkaylor** [comment]
> [@markkaylor](https://github.com/markkaylor) `0.0.0-experimental.cf7b5567d5aec466707a9d9685676df38c5b7c5c` seems to have resolved this issue!

oh nice great!!! thanks for trying it out so quick

**Comment by dmitrysmagin** [comment]
Tried latest 5.16.0 and #23759 is still not fixed. Was the experimental branch merged?

**Comment by markkaylor** [comment]
@dmitrysmagin the PR has not been merged yet. Doing my best to get the fix in next week's release.

**Comment by sami-shukerov** [comment]
Hi @markkaylor,
In addition to the issue we discussed in #23673 , I’m attaching a video that demonstrates the problem in more detail. I’ve noticed that it works correctly with all auto-generated GraphQL queries. However, the issue arises when using a custom query — and in this case, it’s a very simple one, so it should be easy to reproduce.

https://github.com/user-attachments/assets/9ba543f4-3488-462d-bf44-ccb444d10182

And this is my schema of the whole structure -  Page -> Subsection ->Dynamic zone component with relation -> Accordion

![Image](https://github.com/user-attachments/assets/134bae8a-1ce1-4151-a364-d2e9e0439a01)

**Comment by markkaylor** [comment]
closed by #23737
