### ISSUE TITLE
Cannot Save Collection Type After Manually Changing API ID (contentType.invalidUID)

### ISSUE THREAD

**Issue by smolikja** [strapi/strapi#23736]
### Node Version

22.16.0

### NPM/Yarn/PNPM Version

NPM 10.9.2, Yarn 1.22.22

### Strapi Version

5.15.1

### Operating System

MacOS

### Database

SQLite

### Javascript or Typescript

Typescript

### Bug Description

When creating a new collection type using the Content-Type Builder, if the user **manually edits the "Singular name (API ID)"** field (e.g. changing `products` to `product`), the schema cannot be saved. A `400 Bad Request` is returned from the server, and the following error appears in the UI:

> An error occurred

The backend responds with `contentType.invalidUID`, even though the edited ID is a valid lowercase identifier.

### Steps to Reproduce

1. Go to **Content-Type Builder**
2. Click **Create new collection type**
3. Set the display name to: `Products`
4. Change the auto-filled **Singular name (API ID)** from `products` to `product`
5. Click **Continue**
6. Click **Save**
7. Observe error:  
   - Warning in UI: `An error occurred`
   - Network tab: `POST /content-type-builder/update-schema` → **400 Bad Request**
   - Console log:  
     ```
     FetchError: contentType.invalidUID
     ```

### Expected Behavior

Manually editing the "Singular name (API ID)" field with a valid UID should **not prevent saving** the collection type. The content type should be created successfully regardless of whether the UID was auto-generated or customized by the user.

### Logs

```shell
[2025-06-13 10:11:31.518] http: POST /content-type-builder/update-schema (41 ms) 400
[2025-06-13 10:11:33.892] http: GET /.well-known/appspecific/com.chrome.devtools.json (8 ms) 404
[2025-06-13 10:12:20.737] http: POST /content-type-builder/update-schema (12 ms) 400
```

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

**Comment by joeldacuma123** [comment]
I am experiencing this issue as well for MacOS npm version 22.13.1 strapi version 15.5.1

**Comment by 712163** [comment]
Query: 
http://localhost:1337/content-type-builder/update-schema

Query Data:  
{"data":{"components":[],"contentTypes":[{"action":"create","uid":"api::.","status":"NEW","modelType":"contentType","attributes":[{"action":"create","name":"websiteName","properties":{"type":"string","required":true,"default":"webflyer"}}],"kind":"collectionType","modelName":"网站","globalId":"网站","draftAndPublish":false,"displayName":"网站","singularName":"website","pluralName":"websites"}]}},   

Response：  
{
    "error": {
        "name": "ApplicationError",
        "message": "contentType.invalidUID",
        "details": {}
    }
}

Reason:     Create a collection type ->  [ Display name ] is Chinese characters.

**Comment by philipyong** [comment]
same here

**Comment by philipyong** [comment]
Reverting the dependencies to
"@strapi/plugin-cloud": "5.15.0",
"@strapi/plugin-users-permissions": "5.15.0",
"@strapi/strapi": "5.15.0",

fixed it.

**Comment by yindeqiang** [comment]
same

**Comment by JKtechhw** [comment]
Same here.
I've tested all minor versions with the new Content Type Builder, but unfortunately, none of them worked. The last working version was v5.13.0. I'm still getting the same error across all versions. This is very frustrating.

OS: Arch Linux 6.15.3-zen1-1-zen
npm: v11.4.2
Node: v20.19.3

**Comment by jatters** [comment]
Same here

**Comment by nmbrthirteen** [comment]
Same here, anyone fixed that?

**Comment by creadot** [comment]
Same here

**Comment by eliasleyton** [comment]
Same error here:

- 5.15.0
- 5.15.1
- 5.17.0

**Comment by JKtechhw** [comment]
I was able to "resolve" this by generating the content type using the command `npm run strapi generate`. I added the first attribute, and then editing the content type from the admin panel started working as expected.

**Comment by kasonde** [comment]
Hi, just going through our list of issues. I'll close this and mark it as a duplicate of #23711 (only because it was the first reported issue similar to this).

**Comment by eruiz-impact** [comment]
@JKtechhw , I had to do the same thing which worked. On strapi 5.19.0

**Comment by gberidze-bl** [comment]
i have same issue 
error
: 
"contentType.invalidUID"

**Comment by ArchShop** [comment]
I'm having the same problem 5.19.0 :(

**Comment by troyere** [comment]
Same here on 5.23.0

**Comment by troyere** [comment]
> I was able to "resolve" this by generating the content type using the command `npm run strapi generate`. I added the first attribute, and then editing the content type from the admin panel started working as expected.

You're my savior ! ❤️❤️❤️

**Comment by bgomes-bacardi** [comment]
Same on 5.23.1, by putting Reports, report_id and reports_id doesn't even work. If i give other names to pass, it throws the http://localhost:1337/content-type-builder/update-schema 400 (Bad Request)

<img width="1631" height="695" alt="Image" src="https://github.com/user-attachments/assets/c14b4cc1-aad0-4f98-ae74-704ef6bac324" />

Tested in 5.13.0 doesn't work also.

**Comment by HakobjanyanHayk** [comment]
Same here. 

"@strapi/strapi": "5.22.0"
"better-sqlite3": "11.3.0"

node - 20.6.1

<img width="1264" height="722" alt="Image" src="https://github.com/user-attachments/assets/0873daaf-336c-4bb9-9b1e-1335c8815f80" />

**Comment by RayForst** [comment]
Gentlemen, allow me to sit down with you!

    "@strapi/strapi": "5.23.3",
    "better-sqlite3": "11.3.0",

Previously, everything worked through the graphical interface, but the gentleman above suggested an effective way to solve the problem:

> I was able to "resolve" this by generating the content type using the command `npm run strapi generate`. I added the first attribute, and then editing the content type from the admin panel started working as expected.

Thank you, sir!
Hope it will be fixed soon.. or not

**Comment by VadimElFamoso** [comment]
Same here, i'm having issue on Strapi 5.
