### ISSUE TITLE
_start and _limit filter not working

### ISSUE THREAD

**Issue by jacargentina** [strapi/strapi#2413]
**Informations**
- **Node.js version**: v10
- **NPM version**: 6.4.1
- **Strapi version**: v3.0.0-alpha.15
- **Database**: MongoDB 4.0.4
- **Operating system**:  macOS Mojave

**What is the current behavior?**

`GET /blogs` => i have 10 items returned
`GET /blogs?_start=3&_limit=3` => empty result

**Steps to reproduce the problem**

Create a simple standard API, create many instances

**What is the expected behavior?**

Pagination should just work, like previous alpha

**Suggested solutions**

Search for the bug and fix it!

**Comment by jacargentina** [comment]
Was a typo! Sorry, but It doesn’t work

**Comment by kamalbennani** [comment]
Probably related to: https://github.com/strapi/strapi/pull/2419

**Comment by lauriejim** [comment]
Fixed in `alpha.16`

**Comment by mamartins** [comment]
not working also on graphQL and also results never return more than 100 itens, even when limit is set to 150 for eg. Still happening in alhpa.16
