### ISSUE TITLE
"Some of the provided components are not related to the entity" error when restoring a Content History version after schema update

### ISSUE THREAD

**Issue by datsenkoboos** [strapi/strapi#24433]
### Node Version

22.19.0

### NPM/Yarn/PNPM Version

PNPM 9.15.9

### Strapi Version

5.23.6

### Operating System

MacOS

### Database

PostgreSQL

### Javascript or Typescript

Typescript

### Reproduction URL

https://github.com/datsenkoboos/strapi-content-history-issue

### Bug Description

After a schema update, Content History incorrectly determines what components are available inside a Dynamic Zone, which breaks the "Restore" functionality.

### Steps to Reproduce

[Short reproduction video](https://www.loom.com/share/5e156e365c6d4251b432f01ba6b9e0f5?sid=b3b04213-23c2-40a6-8040-b99ed0844f1f)

1. Checkout commit [0ad3737](https://github.com/datsenkoboos/strapi-content-history-issue/commit/0ad3737761ed0df0575000b4aa891cf141c1403c)
2. Publish IndexPage with components `a,b,d,e` inside the Dynamic Zone
3. Checkout commit [c21d451](https://github.com/datsenkoboos/strapi-content-history-issue/commit/c21d451c6232dfe4b0c88834c5d62e38f86a9c61)
4. Add components `f,g,h` to IndexPage and publish the updates
5. Remove component `c` from the IndexPage schema
6. Try restoring the IndexPage version from step 2. Restoration succeeds
7. Try restoring the IndexPage version from step 4. Restoration fails with the error: 
  `Some of the provided components in blocks are not related to the entity`

### Expected Behavior

It should be possible to restore the Content History version from step 4, since it doesn't conflict with the current IndexPage schema.

### Logs

```shell

```

### Media

[Short reproduction video](https://www.loom.com/share/5e156e365c6d4251b432f01ba6b9e0f5?sid=b3b04213-23c2-40a6-8040-b99ed0844f1f)

### Additional information

It's also possible that this issue leads to complete Content History deletion. This happened shortly after we discovered that version restoration wasn't working.

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

**Comment by OcneanuVlad** [comment]
May be related to https://github.com/strapi/strapi/issues/23909

**Comment by kasonde** [comment]
Internal TID: 4667

**Comment by Adzouz** [comment]
Hey @datsenkoboos, sorry for the delay but I think this was resolved already. Can you confirm? There's another current issue with deleted components, relations and dynamic zones but it's a separated topic.
PR is open for review: https://github.com/strapi/strapi/pull/26245

**Comment by michael-sanchez-uvi** [comment]
> Hey [@datsenkoboos](https://github.com/datsenkoboos), sorry for the delay but I think this was resolved already. Can you confirm? There's another current issue with deleted components, relations and dynamic zones but it's a separated topic. PR is open for review: [#26245](https://github.com/strapi/strapi/pull/26245)

@datsenkoboos @Adzouz  Hello, could you please confirm if this has been fixed? Just for peace of mind, I encountered this bug once, but I haven’t seen it happen again since then.

**Comment by datsenkoboos** [comment]
@Adzouz Hi, unfortunately the error from the issue description is still reproducible on 5.47.1. Restoring the IndexPage version from step 4 fails.

cc @michael-sanchez-uvi
