### ISSUE TITLE
Duplicating entry in default locale does not duplicate relations and dynamic zones

### ISSUE THREAD

**Issue by Magiczne** [strapi/strapi#24662]
### Node Version

20.19.3

### NPM/Yarn/PNPM Version

4.9.2

### Strapi Version

5.29.0

### Operating System

Linux (Debian/Ubuntu)

### Database

PostgreSQL

### Javascript or Typescript

Typescript

### Reproduction URL

*No response*

### Bug Description

Having an collection type, which has dynamic zones and relations, those are not saved when duplicated entry is in the locale set as default. However, when duplicating entry that is created in different locale than default everything is working just fine. I have attached videos of the bug

### Steps to Reproduce

1. Setup a content type which has a relation and dynamic zone
2. Setup internationalization with 2 or more locales
3. Create entry of content type in default locale
4. Duplicate it, save and publish.
5. Observe published tab (relations and dynamic zones are empty)
6. Edit one of the entry relations or components inside dynamic zone
7. Save and publish
8. everything is saved correctly.

Point 6-8 should not be required. You can try doing steps 1-5 using entry created in locale that is not default, and it is working correctly.

### Expected Behavior

Duplicating entry in default locale should correctly duplicate relations, as in locales that are not set as default.

### Media

In default locale (mp4):<br>https://github.com/user-attachments/assets/883eafd2-c902-4ea1-b774-e5ef29b1a914

Not in default locale  (mp4):<br>https://github.com/user-attachments/assets/258d1c34-17e5-4e21-a654-49f98c343e2e

### Additional information

*No response*

### Confirmation Checklist

- [X] I have checked the existing [issues](<https://github.com/strapi/strapi/issues>) for duplicates.
- [X] I agree to follow this project's [Code of Conduct](<https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md>).

**Comment by oiorain** [comment]
Hi there,

Thanks for reporting this. I believe this is a known bug but we'll look into it. We're currently working on i18n bugs in v5.

Have a good day!

**Comment by mathildeleg** [comment]
Hi there! 👋

I tried to reproduce the bug you described but I was unable to observe the issue, everything seems to behave correctly now. It’s possible this problem has already been fixed in release v5.30.1, through this [PR](https://github.com/strapi/strapi/pull/24659) maybe

Could you give it another try using v5.30.1 (or a more recent version)? If it still occurs, I’d appreciate if you could share updated reproduction steps so we can investigate further.

Thanks! 🙏

**Comment by Magiczne** [comment]
@mathildeleg actually we've tried today on the latest version available (5.31.2) and the problem still exist, what's more, we have managed to non-deterministically make this break even on locales which are not default. Reproduction steps for the default locale are still the same.

If I manage to reproduce it deterministically with non default locale I will post here

**Comment by MarionLemaire** [comment]
@mathildeleg I've reproduced the step on our latest version 5.32 : 
- DZs were correctly duplicated
- Relations : if D&P is enabled, only Published relations will be duplicated in Published tab. If D&P is disabled, relations will be duplicated in Published tab.
Let me know if you need further investigation :)

**Comment by Magiczne** [comment]
@mathildeleg is there a chance that this bug will be handled in one of coming releases?

**Comment by mathildeleg** [comment]
@Magiczne Hi there, I'll be taking a look at it next week or the week after, it's on my priority list 🙏🏻

**Comment by mathildeleg** [comment]
Hey @Magiczne, sorry for the delays! I believe this [PR](https://github.com/strapi/strapi/pull/25307), which has just been merged but will part of next week's release, is fixing your issue. Could you confirm once it's been released, so I can close this issue? Thanks so much 🙏🏻

**Comment by Magiczne** [comment]
Sure, will check this after release!

**Comment by Magiczne** [comment]
@mathildeleg unfortunately after updating to 5.36.0 we still see this issue, exact reproduction steps from the original message

**Comment by OcneanuVlad** [comment]
Hey there, I tried to reproduce the issue again using the steps provided, as well as the recording showing the reproduction, but I wasn’t able to reproduce it on my end. Could you please try reproducing it in a fresh Strapi project and let us know how it goes?

Also, if you can share a repository where the issue can be reproduced consistently, that would help us a lot and speed up the investigation.

**Comment by Magiczne** [comment]
@OcneanuVlad There is an improvement - I cannot reproduce it on an entirely fresh instance, but...

the problem still exists with connection to two another issues that I have reported, and that's probably why we're going back and forth :D

So now in order to reproduce it now the setup is as follows (I have just used getstarted app from the main repo):
1. Enable `experimental_firstPublishedAt` by adding `experimental_firstPublishedAt: true` into `future` section inside `config/features`
2. Since `firstPublishedAt` is a bit broken because of https://github.com/strapi/strapi/issues/24377 apply the workaround I have posted in the ticket inside `src/index.js` that removes firstPublishedAt from the cloned entry - this seems to be breaking everything, but I have no idea why, since it's only updating a model. Javascript version here:
```js
  bootstrap({ strapi }) {
    // https://github.com/strapi/strapi/issues/24377
    strapi.db.lifecycles.subscribe(async (event) => {
      if (event.action === 'afterCreate') {
        const result = event.result

        if (typeof result.firstPublishedAt !== 'undefined' && typeof result.publishedAt !== 'undefined') {
          if (result.firstPublishedAt !== null && result.publishedAt === null) {
            await strapi.documents(event.model.uid).update({
              documentId: result.documentId,
              data: {
                firstPublishedAt: null,
              },
            })
          }
        }
      }
    })
  },
```
3. Make sure that there are 2 languages setup in the internationalization
4. Create new collection type with Draft & Publish and internationalization as on the screen:<img width="831" height="341" alt="Image" src="https://github.com/user-attachments/assets/2ec4d256-9576-4a4f-bf5f-597ec59e9502" /> 
4. Create an entry of that newly created Collection type, save, publish
5. make sure that everything is published, because the bug from https://github.com/strapi/strapi/issues/25196 still appears sometimes, and the published tab shows empty content. If it's empty make slight modifications and publish again so the Draft version is the same as the published one.
6. Go to the list of newly created collection types
7. Duplicate and publish
8. Observe draft tab - it's correctly cloned
9. Observe puhlished tab - it's empty.

Attaching video:
https://github.com/user-attachments/assets/f5eea5b6-5dbc-4c1d-ae24-0b06d6b9efc7

So probably these three tickets are entirely connected and maybe caused by the same thing:
https://github.com/strapi/strapi/issues/24377
https://github.com/strapi/strapi/issues/24662
https://github.com/strapi/strapi/issues/25196

Using setup above I'm able to consistently reproduce error

**Comment by mathildeleg** [comment]
Sorry this has been closed, I've not reproduced it on my end but will again ask @OcneanuVlad to test out too :)
Thanks for your patience, it's a bit tricky when we have trouble reproducing the issue 🙏🏻

**Comment by Magiczne** [comment]
No problem, since this i a bit tricky reproduction as well :)

**Comment by mathildeleg** [comment]
I'm unable to reproduce it again on the latest version (v5.41.1), where this [PR](https://github.com/strapi/strapi/pull/25947) might have fixed your [issue](https://github.com/strapi/strapi/issues/25196) since it also solved.
I'm sorry to ask this again, could you try upgrading your Strapi project and see if you still encounter the issue? 🙏🏻

**Comment by Magiczne** [comment]
I have checked on the earlier version, then checked out `develop` branch and issue still exists, as well as #24377 - which workaround to is probably causing this bug, but the workaround is so simple it should not be causing this kind of a mess :D 

I have created branch with reproduction setup:
https://github.com/Magiczne/strapi/compare/issue-24662-reproducer

with only one commit:
https://github.com/strapi/strapi/compare/develop...Magiczne:strapi:issue-24662-reproducer

steps identical as in comment above. I'm able to reproduce it in every case.
Use the Issue 24662/24337 Reproducer content type

Hope it helps!

**Comment by Adzouz** [comment]
Hi @Magiczne,
Thanks a lot for your patience 🙏 I have to admit that this one is giving headaches since nobody on our side was able to reproduce 😅 Here's a video of my test on my side. I checkout your branch to have the same configuration, I added another locale that I put it as default (FR) and tried to reproduce the same steps as you (creating an entry -> publish -> duplicate from list -> publish).
Can you tell me what I'm doing wrong so I can better understand what's going on? 🙏

https://github.com/user-attachments/assets/783dffc5-45c3-4e6b-a09f-8f72f2eec795

I also tried to remove draft and publish on the relation in the dynamic zone but it's the same result 😢

**Comment by Magiczne** [comment]
Ok, that's actually a bit impressive, because today I have tried to reproduce it on my branch - managed to, then rebased to the latest develop again, run `yarn setup` again (as yesterday when creating reproduction branch), and could not reproduce the issue...

Let me check tomorrow on our dockerized setup with PSQL as a Database, and I will come back with some info. Now this looks like magic

**Comment by Magiczne** [comment]
Sorry for a bit delayed, but the bug from the ticket is no longer appearing.

We have encountered some issues with sorting by the first published at field but will check that more and report as a separate bug.

It seems that release you have linked above fixes this. Thanks!

**Comment by mathildeleg** [comment]
I'm really glad to hear that ✨💪🏻
Don't hesitate to open that other issue once you've confirmed it!
Thanks for your help on this one 😊
