### ISSUE TITLE
PostgreSQL needs special case for _contains selector

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#2765]
**Informations**
- **Node.js version**: 10.8.0
- **NPM version**:  6.2.0
- **Strapi version**: alpha v22
- **Database**:  psql
- **Operating system**:  WSL/Ubuntu

**What is the current behavior?**

Postgres is case sensitive.
In order to support the `_contains` (case insensitive) filter on APIs, we would need to make a postgres-specific change in the bookshelf hook plugin. Maybe there is also an alternative that works for both pg and mysql

**Steps to reproduce the problem**

* create a content type "pet"
* add a `name` field
* create a new object with name `Cat`
* query for `pets/?name_contains=cat`
* get no results

**What is the expected behavior?**

actually, you should get results.

**Suggested solutions**

There are some solutions, but they are not really nice:
https://stackoverflow.com/questions/7005302/postgresql-how-to-make-case-insensitive-query

* Postgres comes with an `ILIKE` case insensitive operator but is really slow.
* turn to lowercase, but make indexes meaningless: `WHERE LOWER(name)=LOWER('Administrator')`

Some other article that points that out: http://mwiki.gichd.org/IM/Difference_MySQL_PostGreSQL

**Comment by lauriejim** [comment]
Thank you @MartinMuzatko for this report!
Can you please submit a PR to fix it.
Will appreciate your contribution!

**Comment by MartinMuzatko** [comment]
What would be the preferred solution? Check for db to run on pg and use `ILIKE` instead?
I have to look a little deeper into how the filters are composed, and if `ilike` can be used then.
Also the type of client has to be passed into `getQueryParams`, unlike there is a way to retrieve the client in that module? I saw there is `definition.client === 'mysql'` - maybe I can get that within that `getQueryParams` function.

**defined here:** https://github.com/strapi/strapi/blob/7d8507573f0e0810e6b44032e1243d660ec97738/packages/strapi-hook-bookshelf/lib/index.js#L1098-L1105

**called here:** https://github.com/strapi/strapi/blob/57e0f3e343dfc9378c93b0c99f0c577c158c7baf/packages/strapi-utils/lib/models.js#L447-L507

**Comment by kamalbennani** [comment]
Strapi doesn't implement yet the case-insensitive filter for relational dbs, it'll be the case once this PR is merged: https://github.com/strapi/strapi/pull/2452/commits/4318b0bb1151d908eb1189be5529b7fddcf90f6f

**Comment by lauriejim** [comment]
It have been fixed in laster version of Strapi `alpha.26`

**Comment by DrineTN** [comment]
i update to alpha.26 today and i still have the problem 
![image](https://user-images.githubusercontent.com/4802914/59341272-7c366700-8cff-11e9-8d94-dfeb567264a7.png)
