### ISSUE TITLE
Deleted attributes are returned by API

### ISSUE THREAD

**Issue by felideon** [strapi/strapi#3160]
**Information**
- **Node.js version**: v10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.26
- **Database**: SQLite
- **Operating system**: macOS 10.13.6

**What is the current behavior?**
When deleting a model's attribute via the admin UI (and saving), the Strapi API still returns the attribute in the JSON results—even after restarting the server, making the call in a new browser, and restarting the machine.

In the admin UI, `model.settings.json` file, and even `core_store` table, the attributes do not show. They only exist in the SQLite db.

Old instances of the model will continue to return their values, whereas new instances will return null.

**Steps to reproduce the problem**

- Create a new quick-started strapi project (or non-quickstart and choose SQLite).
- Register a new root user.
- In the admin UI, add a new content type called `article`, with two string fields: `title`, `summary`; save.
- Under the Articles content type, Add New Article with values "hello world" and "this is the first amazing article"; save.
- Add the find and findone permissions on the Article resources to the Public role; save
- Visit http://localhost:1337/articles/1 to confirm the model attributes and values return as expected.
- Back in the admin UI, delete the _summary_ field from the Article content type; save.
- _(optional)_ Quit the strapi server in the terminal, and `strapi start` again
- Refresh http://localhost:1337/articles/1

**What is the expected behavior?**
The `summary` field should not be included in the JSON results.

**Suggested solutions**
I understand that:

- On the database side, there is an enhancement currently under consideration on the roadmap: https://portal.productboard.com/strapi/c/22-delete-unnecessary-tables-collections-columns-in-the-databases
- SQLite has limited alter table functionality, so dropping columns requires cloning and recreating tables as outlined here: https://www.sqlite.org/lang_altertable.html#otheralter

However, I am not sure why the API does not honor the model. I am a newbie, so I wasn't exactly sure of the expected behavior. But according to someone from the Slack chat, it seems that this issue works as expected when using MongoDB.

I am not a Node.js dev, but one thing I did notice in the code was that the service template does not pass column names to the `bookshelf.model.fetch` call:

https://github.com/strapi/strapi/blob/master/packages/strapi-generate-api/templates/bookshelf/service.template#L51-L53

But then I tried changing the `Article.fetch` service function in my test project to pass the column names as so:

```js
return Article.forge(_.pick(params, 'id')).fetch({
  columns: ['name'],
  withRelated: populate
});
```

But that doesn't return the related fields, i.e. `created_at` and `updated_at` or if I had a media type attribute it wouldn't be returned either, just:

```js
{"id":"1","name":"hello world"}
```

In any case, my suggested solution would be to ensure the API honors the model rather than the database.

**Comment by lauriejim** [comment]
Since we introduce the `sanitizeEntity` function in the core controller, this issue has been fixed.

**Comment by FernandoBoza** [comment]
I'm still getting this behavior, I've modified the Collection and type, and it still shows the old properties with NULL as the value

Node.js version: v14.7.0
NPM version: 6.14.8
Strapi version: 3.2.5
Database: Postgres
Operating system: macOS 10.15.7

**Comment by derrickmehaffy** [comment]
Related: #1114

**Comment by FernandoBoza** [comment]
Would that be a driver issue?

**Comment by derrickmehaffy** [comment]
@FernandoBoza It's an issue with us not cleaning up the database, for the moment you will need to do the cleanup manually.
