### ISSUE TITLE
Rendering field more than once in admin page

### ISSUE THREAD

**Issue by zeybek** [strapi/strapi#3486]
![Screenshot_1](https://user-images.githubusercontent.com/30319707/59748723-5f141200-9284-11e9-8114-f40d791794dc.jpg)

**System**
- Node.js version: 10.16.0
- NPM version: 6.5.0
- Strapi version: 3.0.0-beta.3
- Database: MongoDB
- Operating system: Windows 10 build 1903

No problem while using, but I don't know why this happens

**Comment by soupette** [comment]
Unfortunately, I am pretty sure this is happening because of the `core_store_schema`, until the fix is released (we are currently working on it) you can fix this bug either by using the settings view:
- click on the `Content Manager` link in the left menu
- select the buggy content type in the list view
- go to the edit settings and delete the non desired fields

The other solution would be to delete the document in your database and restart your server.

**Comment by zeybek** [comment]
It didn't solve problem, just changed content type name then reverted back and problem gone
