### ISSUE TITLE
The relation autocomplete doesn't work well

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#4025]
**Describe the bug**

The relation autocomplete doesn't work well.

**Steps to reproduce the behavior**

Use any relation autocomplete.

**Screenshots**

![Sep-17-2019 09-21-25](https://user-images.githubusercontent.com/1007051/65019999-8f735700-d92c-11e9-9ef7-0b485cf6b5d8.gif)

**System**
- Node.js version: v10.16.0
- NPM version: v6.11.3
- Strapi version: v3.0.0-beta.16.3
- Database: MongoDB
- Operating system: macOS

**Comment by alexandrebodin** [comment]
@abdonrd This as been fixed in one of the latest releases if you update this should be good now. Don't forget to rebuild your admin before testing ;)

**Comment by abdonrd** [comment]
@alexandrebodin it still doesn't work well with the current last version:

![Screen Recording 2019-10-03 at 23 00 01](https://user-images.githubusercontent.com/1007051/66164073-1bc29100-e632-11e9-8e87-d915a20d0dc0.gif)

**Comment by alexandrebodin** [comment]
I cannot reproduce it. have you removed .cache and build folder and rebuilt your admin ?

**Comment by abdonrd** [comment]
Yes! I run this after update Strapi in the `package.json`:

```
> rm -rf .cache/ build/ exports/ node_modules/ yarn.lock
> yarn install
> yarn build
> yarn develop
```

**Comment by lauriejim** [comment]
I tested with a new application with Mongo and it works well also in my side.

**Comment by abdonrd** [comment]
Real example with the Chrome Dev Tools:

![Oct-12-2019 18-17-03](https://user-images.githubusercontent.com/1007051/66699832-89e71200-ed1c-11e9-9323-a939fde223b8.gif)

**Comment by lauriejim** [comment]
Thank y ou @abdonrd for this video.

**Comment by omarzion** [comment]
not exactly related, but typing in any record past the first 20 returns no results due to the _limit=20

**Comment by lauriejim** [comment]
Hello! There is another issue about this topic @omarzion.

**Comment by soupette** [comment]
I am closing the issue as it has been fixed with `beta.19`

**Comment by nickjanssen** [comment]
This is still a problem on `beta.19` @soupette 

![bug](https://user-images.githubusercontent.com/2780160/75895784-6b51f680-5e36-11ea-89b4-0868b39cde9a.gif)

**Comment by soupette** [comment]
Which db are you using?

**Comment by nickjanssen** [comment]
@soupette using MongoDB on a ubuntu box. I had upgraded to beta.19 just now

**Comment by lauriejim** [comment]
Hello @nickjanssen, I can confirm the issue with Mongo ID search.
Can you please open a new GitHub issue.
This works well when you search on a text field.

**Comment by soupette** [comment]
@petersg83 can you check if the issue is coming from the backend and I have also noticed that is does not work well with postgres

**Comment by dkarski** [comment]
@soupette the problem was with query params added in client-side.

> The solution I propose for both issues is :
The front uses param ?ID_contains=5d1 instead of ?_q=5d1

Finally, search functionality is similar to the search implemented in ListView of the content manager.
