### ISSUE TITLE
Graphql - querying deeply nested "has Many" One to Many relationship throws an exception

### ISSUE THREAD

**Issue by dankostov** [strapi/strapi#4353]
**Describe the bug**
Objects located deeper than 3 levels with "has Many" one-to-many relationship always throw exception when querying using GraphQL.

**Steps to reproduce the behavior**
I have deeply nested objects.  
building -> apartments (has Many relationship)
apartment -> rooms (has Many relationship)
The models are described in another bug (with the node that rooms are many-to-many relationship) here: https://github.com/strapi/strapi/issues/4288

**Request:**

```graphql
query {
 building(id:1) {
      number
 	apartments {
      rooms {
       number
     }
   }      
 }   
}
```

**Result:**

```json
{
  "errors": [
    {
      "message": "Your filters contain a field 'undefined' that doesn't appear on your model definition nor it's relations",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "building",
        "apartments",
        0,
        "rooms"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "status": 400,
          "stacktrace": [
            "Error: Your filters contain a field 'undefined' that doesn't appear on your model definition nor it's relations",
            "    at getAssociationFromFieldKey (/home/dan/strapi/project/node_modules/strapi-utils/lib/buildQuery.js:40:19)",
            "    at /home/dan/strapi/project/node_modules/strapi-utils/lib/buildQuery.js:120:50",
            "    at Array.map (<anonymous>)",
            "    at buildQuery (/home/dan/strapi/project/node_modules/strapi-utils/lib/buildQuery.js:119:8)",
            "    at Object.find (/home/dan/strapi/project/node_modules/strapi-hook-bookshelf/lib/queries.js:76:14)",
            "    at Object.fetchAll (/home/dan/strapi/project/node_modules/strapi-plugin-content-manager/services/ContentManager.js:26:47)",
            "    at Object.makeQuery (/home/dan/strapi/project/node_modules/strapi-plugin-graphql/services/Loaders.js:172:7)",
            "    at /home/dan/strapi/project/node_modules/strapi-plugin-graphql/services/Loaders.js:56:37",
            "    at Array.map (<anonymous>)",
            "    at /home/dan/strapi/project/node_modules/strapi-plugin-graphql/services/Loaders.js:56:19",
            "    at dispatchQueueBatch (/home/dan/strapi/project/node_modules/dataloader/index.js:246:22)",
            "    at dispatchQueue (/home/dan/strapi/project/node_modules/dataloader/index.js:233:5)",
            "    at /home/dan/strapi/project/node_modules/dataloader/index.js:70:20",
            "    at processTicksAndRejections (internal/process/task_queues.js:75:11)"
          ]
        }
      }
    },
    {
      "message": "Your filters contain a field 'undefined' that doesn't appear on your model definition nor it's relations",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "building",
        "apartments",
        1,
        "rooms"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "status": 400,
          "stacktrace": [
            "Error: Your filters contain a field 'undefined' that doesn't appear on your model definition nor it's relations",
            "    at getAssociationFromFieldKey (/home/dan/strapi/project/node_modules/strapi-utils/lib/buildQuery.js:40:19)",
            "    at /home/dan/strapi/project/node_modules/strapi-utils/lib/buildQuery.js:120:50",
            "    at Array.map (<anonymous>)",
            "    at buildQuery (/home/dan/strapi/project/node_modules/strapi-utils/lib/buildQuery.js:119:8)",
            "    at Object.find (/home/dan/strapi/project/node_modules/strapi-hook-bookshelf/lib/queries.js:76:14)",
            "    at Object.fetchAll (/home/dan/strapi/project/node_modules/strapi-plugin-content-manager/services/ContentManager.js:26:47)",
            "    at Object.makeQuery (/home/dan/strapi/project/node_modules/strapi-plugin-graphql/services/Loaders.js:172:7)",
            "    at /home/dan/strapi/project/node_modules/strapi-plugin-graphql/services/Loaders.js:56:37",
            "    at Array.map (<anonymous>)",
            "    at /home/dan/strapi/project/node_modules/strapi-plugin-graphql/services/Loaders.js:56:19",
            "    at dispatchQueueBatch (/home/dan/strapi/project/node_modules/dataloader/index.js:246:22)",
            "    at dispatchQueue (/home/dan/strapi/project/node_modules/dataloader/index.js:233:5)",
            "    at /home/dan/strapi/project/node_modules/dataloader/index.js:70:20",
            "    at processTicksAndRejections (internal/process/task_queues.js:75:11)"
          ]
        }
      }
    }
  ],
  "data": {
    "building": {
      "number": "12",
      "apartments": [
        {
          "rooms": null
        },
        {
          "rooms": null
        }
      ]
    }
  }
}
```

**Expected behavior**
It should return the rooms as well.

 
**System**
Node.js version: v12.12.0
NPM version: 6.11.3
Strapi version: 3.0.0-beta.17.2
Database: sqlite
Operating system: Ubuntu

**Comment by lauriejim** [comment]
Hello! I just tested with `3.0.0-beta.17.4` and it works fine.

In the query snippet your `apartments` key is not correct.
It should be `appartments` with 2 `p`

![Screenshot 2019-10-26 at 6 21 22 PM](https://user-images.githubusercontent.com/5716596/67622755-9a6bb200-f81d-11e9-94a2-15e62756a1be.png)

**Comment by bolbosenco** [comment]
I have the same problem. :(

**Comment by obmarg** [comment]
We just encountered a similar issue: deleting the data from our table and recreting it appears to have fixed.  Obviously not practical for everyone, but helped for us.

We'd been making lots of structural changes at the time, and looked like a few of our browser tabs hadn't been refreshed with the new content structure.  Possible that we inserted data in a tab with an old copy of the structure cached?

**Comment by dankostov** [comment]
I am also having the same problem, It happens only when you have deeper nested objects with has many relationship. I dropped the inner nested tabled and recreated them again but didn't work.

**Comment by dankostov** [comment]
I tried this with fresh install, re-creating all tables. It gives the same error.

**Comment by obmarg** [comment]
We actually encountered this again shortly after deleting our data, so think I may have been incorrect in my message above.  We _seem_ to have had a bit of luck recreating our nested relationships from the inner entity to the outer entity - so to use a blog as an example, setting up the relationships from comment -> post -> blog.  Previously we were using the blog page to create the relationship to posts, and the posts page to create a relationship to comments.

**Comment by lauriejim** [comment]
Hello! Another opened issue exists about that.
and should be fixed normally.
Stay tuned on the next Strapi version.

**Comment by obmarg** [comment]
@lauriejim do you have a link to this other issue please?  Would like to keep an eye on this, but can't find anything myself.

**Comment by chris-kobrzak** [comment]
Hi @lauriejim, I believe this issue should be re-opened as it looks like querying nested content types still throws the `Your filters contain a field 'undefined' that doesn't appear on your model definition nor it's relations` error.

I've tried creating a sample `artist -> record -> review` Content Type relationship where artists can have multiple records and records can have multiple reviews. So they're both using the `has many` option available in the admin GUI.

Even with a entry in the database, the following GraphQL query returns an error:

```
query AllArtists {
  artists {
    label,
    records {
      title,
      reviews {
        source
      }
    }
  }
}
```

Strapi version: 3.0.0-beta.18.3
Tested DB adapters: PostgreSQL and SQLite (quick starter).

**Comment by regisMartini** [comment]
Having same error here. Any updates on this issue?

**Comment by jballands** [comment]
We've had luck changing "has many" to "belongs to many". Obviously this isn't ideal but it seems to resolve the issue.

**Comment by chris-kobrzak** [comment]
> We've had luck changing "has many" to "belongs to many". Obviously this isn't ideal but it seems to resolve the issue.

Many thanks for sharing this tip, @jballands. Confirmed, this hack (?) has worked for me as well.

**Comment by lauriejim** [comment]
Hello @chris-kobrzak !
Can you please send me your 3 models to let me reproduce your issue.
Thank you.

**Comment by chris-kobrzak** [comment]
> Can you please send me your 3 models to let me reproduce your issue.

No probs, there you go:

`artist.settings.json`
```json
{
  "connection": "default",
  "collectionName": "artists",
  "info": {
    "name": "artist"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true
    },
    "records": {
      "collection": "record"
    }
  }
}
```

`record.settings.json`
```json
{
  "connection": "default",
  "collectionName": "records",
  "info": {
    "name": "record"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "title": {
      "type": "string",
      "required": true
    },
    "reviews": {
      "collection": "review"
    },
    "artist": {
      "model": "artist"
    }
  }
}
```

`review.settings.json`
```json
{
  "connection": "default",
  "collectionName": "reviews",
  "info": {
    "name": "review"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "heading": {
      "type": "string",
      "required": true
    },
    "content": {
      "type": "richtext"
    },
    "record": {
      "model": "record"
    }
  }
}
```

**Comment by jballands** [comment]
I can supply our models too since we're having the same issue:

GQL call:
```gql
query GetVoyage {
    voyage(id: 1) {
       Journey {
          Chapters {
              id
           }
        }
    }
}
```

Output:

```
{
  "errors": [
    {
      "message": "Your filters contain a field 'undefined' that doesn't appear on your model definition nor it's relations",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "voyage",
        "Journey",
        "Chapters"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "status": 400,
          "stacktrace": [
            "Error: Your filters contain a field 'undefined' that doesn't appear on your model definition nor it's relations",
            "    at getAssociationFromFieldKey (~/lnd-strapi/node_modules/strapi-utils/lib/buildQuery.js:46:19)",
            "    at ~/lnd-strapi/node_modules/strapi-utils/lib/buildQuery.js:109:50",
            "    at Array.map (<anonymous>)",
            "    at buildQuery (~/lnd-strapi/node_modules/strapi-utils/lib/buildQuery.js:108:8)",
            "    at Object.find (~/lnd-strapi/node_modules/strapi-connector-bookshelf/lib/queries.js:76:14)",
            "    at Query.find (~/lnd-strapi/node_modules/strapi-database/lib/queries/create-query.js:47:32)",
            "    at Object.fetchAll (~/lnd-strapi/node_modules/strapi-plugin-content-manager/services/ContentManager.js:24:39)",
            "    at Object.makeQuery (~/lnd-strapi/extensions/graphql/services/Loaders.js:171:5)",
            "    at ~/lnd-strapi/extensions/graphql/services/Loaders.js:54:32",
            "    at Array.map (<anonymous>)",
            "    at ~/lnd-strapi/extensions/graphql/services/Loaders.js:54:14",
            "    at dispatchQueueBatch (~/lnd-strapi/node_modules/dataloader/index.js:246:22)",
            "    at dispatchQueue (~/lnd-strapi/node_modules/dataloader/index.js:233:5)",
            "    at ~/lnd-strapi/node_modules/dataloader/index.js:70:20",
            "    at processTicksAndRejections (internal/process/task_queues.js:82:9)"
          ]
        }
      }
    }
  ],
  "data": {
    "voyage": {
      "Journey": {
        "Chapters": null
      }
    }
  }
}
```

Models:

```json
// Voyage.settings.json

{
  "connection": "default",
  "collectionName": "voyages",
  "info": {
    "name": "voyage",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "Journey": {
      "via": "Voyage",
      "model": "journey"
    }
  }
}

// Journey.settings.json
// Note that Chapters is a one-way relationship!! This is important to exhibit the bug.

{
  "connection": "default",
  "collectionName": "journeys",
  "info": {
    "name": "journey",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": [
      "created_at",
      "updated_at"
    ],
    "comment": ""
  },
  "attributes": {
    "Voyage": {
      "model": "voyage",
      "via": "Journey"
    },
    "Chapters": {
      "collection": "journeychapter"
    }
  }
}

// Journeychapter.settings.json

{
  "connection": "default",
  "collectionName": "journeychapters",
  "info": {
    "name": "journeychapter",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": [
      "created_at",
      "updated_at"
    ],
    "comment": ""
  },
  "attributes": {
    "title": {
      "type": "string"
    }
  }
}
```

---

Please note, if we start at `Journey` as the root, the query works:

```gql
query GetJourney {
    journey(id: 1) {
        Chapters {
            id
        }
    }
} 
```

Output:

```
{
  "data": {
    "journey": {
      "Chapters": [
        {
          "id": "1"
        }
      ]
    }
  }
}
```

This is why people have been saying it only affects "deep" queries.

**Comment by wkuch** [comment]
I have the same issue on version `3.0.0-beta.19.3`:

I'm using three content types: 
'Image' -> has a `Title` field and a `image` field
'ImageSelection' -> has a `Title` and many `Images`
'RequestFormContent' -> has many `imageSelections` 

I can query the `ImageSelection` and the images inside. I can also query the `RequestFormContent`  and the `ImageSelections` with the `Title`.
But when the query is to deep and I want to get the `Images` inside the `ImageSelection` inside the `RequestFormContent` it throws an error.

works:
```
{
  imageSelections {
    Title
    images {
      image {
        id
      }
    }
  }
}
```
also works:
```
{
  requestFormContents {
    image_selections {
      Title
    }
  }
}
```
error:
```
{
  requestFormContents {
    image_selections {
      Title
      images {id}
    }
  }
}
```
-> 
```
...
 "code": "INTERNAL_SERVER_ERROR",
...
"status": 400,
 "stacktrace": [
     "Error: Your filters contain a field 'undefined' that doesn't appear on your model definition nor it's 
     relations"
...
```

**Comment by roelbeerens** [comment]
I experienced the same issue with 3.0.0-beta.19.5. One level deep is work just fine, Two levels deep throws an error.

**Comment by Fezzzi** [comment]
Had the same issue, remodeling relations between collection types from one-to-many to many-to-many solved the problem for me, some stuff about relations can be found [here](https://strapi.io/documentation/3.0.0-beta.x/getting-started/quick-start-tutorial.html#_4-create-a-new-content-type-called-category). Hope it might help someone!

**Comment by abanchev** [comment]
I managed to track the bug down partially, however I am not so familiar with the codebase to fix it.
The problem is in **strapi-plugin-graphql**/services/type-definitions.js

line 186-189

```
            if (
                ((association.nature === 'manyToMany' && association.dominant) ||
                  association.nature === 'manyWay') &&
                _.has(obj, association.alias) // if populated
              )
```

Nature is manyWay, however it is not populated because of an unknown to me reason(**obj** is missing the fields that are manyWay). This causes it to use **association.via** in the query, however **via** is null for this association and this causes the exception later.

**Comment by deyceg** [comment]
Had something which may be related...

DailyMenu (specific day) has a Menu which has many Dishes

Querying the DailyMenu doesnt give me the Dishes (empty array)

Querying the Menu gives me the Dishes

**Comment by abanchev** [comment]
https://github.com/abanchev/strapi-issues-test
here is a simple sample project with the latest beta, the readme contains a query that will cause this issue

**Comment by andylacko** [comment]
please reopen this issue, I am getting the same error and I am running `3.0.1`

**Comment by derrickmehaffy** [comment]
@andylacko it would be better to create a new issue related to the stable, this issue is old.
