### ISSUE TITLE
Admin path does not work for non-root proxy host

### ISSUE THREAD

**Issue by pbjer** [strapi/strapi#4513]
**Describe the bug**
Admin dashboard non-functional when host proxy name includes subdirectory.

**Steps to reproduce the behavior**
1. Setup server config for production environment using proxy
2. Specify `proxy.host = 'www.website.com/example-path'`
3. Leave `admin.path = '/admin'`
4. Build admin dashboard with production settings
5. Start application

**Expected behavior**
Admin dashboard should be available and functional at `www.website.com/example-path/admin`

**Code snippets**
In the above example, index.html for admin is in the correct place at `www.website.com/example-path/admin` but is requesting resources from the wrong path relative to the project:
```
<script type="text/javascript" src="/admin/runtime~main.f7ebb0d0.js"></script>
```
```
<script type="text/javascript" src="/admin/main.c81d41af.chunk.js">
```
src for the above should be `/example-path/admin/...` to reflect the proxy settings

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.17.5
- Database: postgres
- Operating system: ubuntu 18.04

**Additional context**
I believe the issue is related to the webpack config for strapi-admin.
```
output: {
      path: dest,
      publicPath: options.publicPath,
      // Utilize long-term caching by adding content hashes (not compilation hashes)
      // to compiled assets for production
      filename: isProduction ? '[name].[contenthash:8].js' : 'bundle.js',
      chunkFilename: isProduction
        ? '[name].[contenthash:8].chunk.js'
        : '[name].chunk.js',
    },
```

Here is my config from `config/environments/production/server.json`:
```
{
  "host": "${process.env.STRAPI_HOST || 'localhost'}",
  "port": "${process.env.STRAPI_PORT || 1337}",
  "production": true,
  "proxy": {
    "enabled": true,
    "host": "www.examplewebsite.com/content",
    "ssl": true
  },
  "cron": {
    "enabled": false
  },
  "admin": {
    "path": "/admin",
    "autoOpen": false
  }
}

```

Possibly unrelated but this is another issue here in `node_modules/strapi-admin/src/public-path.js`

```
  // Relative URL (ex: /dashboard)
  if (process.env.REMOTE_URL[0] === '/') {
    return (window.location.origin + process.env.REMOTE_URL).replace(/\/$/, '');
  }
```
window.location.origin will always resolve to the root host - `www.website.com` vs `website.com/example-path` in my case.

**Comment by pbjer** [comment]
@lauriejim pinging you because it seems this report was missed during triage from the last couple of weeks - no solution found except for using a non-root proxy.

**Comment by derrickmehaffy** [comment]
Yeah short answer here, Strapi would need to re-add prefix (was removed some time ago because they didn't have the time to fix it). That or you would need to handle all of your endpoint rewrites in your nginx config

**Comment by lauriejim** [comment]
Hello! Proxy in strapi are good to manage sub-domaine. but when there is a subpath, it's not enough well managed.
As @derrickmehaffy said. I suggest you to use a nginx config to manage that.

**Comment by pbjer** [comment]
Thanks for the response -  For now I suppose I will just be using a subdomain as a workaround because nginx can't fix the issue of webpack building the wrong relative path.

**Comment by derrickmehaffy** [comment]
Agreed yeah @pbjer without prefixes it would be quite difficult

**Comment by alexandrebodin** [comment]
@pbjer Have you tried setting the admin path option to `/content/admin` ?

**Comment by pbjer** [comment]
@alexandrebodin Yes

**Comment by Deepankar01** [comment]
any update on this ?
is there any possible way to run on prefixes ?

**Comment by derrickmehaffy** [comment]
@Deepankar01 this will require the Strapi team to re-implement the removed prefix option that was removed some time ago.

I believe @lauriejim had a small discussion on it in slack as well.

**Comment by Deepankar01** [comment]
@derrickmehaffy ok checking it 
i was able to manage it differently 

- strapi api's runs on different sub-route /cms (via nginx-proxy)
- api's admin runs on different sub-route /cms-admin (copied build folder in the html folder for nginx)
it works like a charm 

since admin is a simple react project i changed the path in the config for admin and  
updated the server url with sub-route . (with proxy)

**Comment by derrickmehaffy** [comment]
This issue was fixed with https://github.com/strapi/strapi/pull/5833 and will be released in rc.1 currently there is no plan to backport to beta versions. I'm marking this issue as closed.

**Comment by rubms** [comment]
I am still having problems with this issue in v3.0.0-rc.1.

I am running Strapi on Kubernetes, exposing it behind an ingress (Nginx reverse proxy) under the `/strapi` subpath.

I am using the following `server.js` configuration:
```javascript
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('PUBLIC_URL', 'http://127.0.0.1:1337'),
  admin: {
    url: env('PUBLIC_ADMIN_URL', 'http://127.0.0.1:1337/admin'),
  }
});
```

I set the `PUBLIC_URL` and `PUBLIC_ADMIN_URL` environment variables to the appropriate values:
```
PUBLIC_URL=http://localhost/strapi
PUBLIC_ADMIN_URL=http://localhost/strapi/admin
```

When starting, Strapi shows the appropriate path for the admin website: http://localhost/strapi/admin. However, every time I access the admin website I keep getting a blank page. The bundled resources cannot be found because they are still being retrieved from `/admin`: `http://localhost/admin/runtime~main.1268513a.js`

I have tried with the following combinations of configuration, but I always get the same invalid result.
```
PUBLIC_URL=http://localhost/strapi
PUBLIC_ADMIN_URL=http://localhost/strapi/admin

PUBLIC_URL=http://localhost/strapi
PUBLIC_ADMIN_URL=/admin

PUBLIC_URL=http://localhost/
PUBLIC_ADMIN_URL=/strapi/admin
```

Am I doing something wrong? Is this also happening to other users?

Thanks in advance.

**Comment by vivex** [comment]
I upgraded strapi installation to  `strapi@v3.0.0-rc.1` in hope of fixing sub route installation, but it is giving the same error:  `domain.com/strapi/users-permissions/init` not found on admin page.

**Comment by petersg83** [comment]
@vivex Can you please open an issue with your configuration?
