### ISSUE TITLE
date is not set correctly

### ISSUE THREAD

**Issue by piLeoni** [strapi/strapi#4841]
**Describe the bug**

If i set a date, let's say April 1 2020, seems to be correctly set.
However, i open that content again, and it say march 31.
Seems to be always one day behind.

If that can be a timezone problem, I'm in Cambridge, Massachusetts.

**Expected behavior**
Getting the date set correctly.

**System**
- Node.js version: v10.14.0
- NPM version: 6.4.1
- Strapi version: 3.0.0-alpha.26.2
- Database: sqlite
- Operating system: Ubuntu 14.04.4 LTS

**Additional context**

**Comment by lauriejim** [comment]
Hello! You are using an old version of strapi.
The current version is `beta.18.3` and the bug has been fixed.

**Comment by piLeoni** [comment]
Not really, updated and rebuild, even re-created the app from scratch and still the same problem.
Mu package json.
{
  "name": "cms",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "strapi": "3.0.0-beta.18.3",
    "strapi-admin": "3.0.0-beta.18.3",
    "strapi-utils": "3.0.0-beta.18.3",
    "strapi-plugin-content-type-builder": "3.0.0-beta.18.3",
    "strapi-plugin-content-manager": "3.0.0-beta.18.3",
    "strapi-plugin-users-permissions": "3.0.0-beta.18.3",
    "strapi-plugin-email": "3.0.0-beta.18.3",
    "strapi-plugin-upload": "3.0.0-beta.18.3",
    "strapi-connector-bookshelf": "3.0.0-beta.18.3",
    "knex": "<0.20.0",
    "sqlite3": "latest"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "3be5e7fc-59c2-493f-94fa-83e8aed82ee8"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

**Comment by lauriejim** [comment]
Can you please check the date that is sent in the request from the Admin Panel.
And log the SQL request that creates your entry.
