### ISSUE TITLE
Fix error message when register function fail because of required constraint

### ISSUE THREAD

**Issue by marcin-stasiak** [strapi/strapi#5479]
**Reproduction**
1. Add to: _extensions/users-permissions/models/User.settings.json_
```
    "slug": {
      "type": "uid",
      "targetField": "username",
      "required": true,
      "minLength": 3
    },
```
2. Send POST registration request to: _auth/local/register_
```
{
  "username": "test1",
  "email": "test1@test.pl",
  "password": "test"
}
```
3. You get incorrect information: _Username already taken_ 
```{
  "statusCode": 400,
  "error": "Bad Request",
  "message": [
    {
      "messages": [
        {
          "id": "Auth.form.error.username.taken",
          "message": "Username already taken"
        }
      ]
    }
  ],
  "data": [
    {
      "messages": [
        {
          "id": "Auth.form.error.username.taken",
          "message": "Username already taken"
        }
      ]
    }
  ]
}
```
**Expected behavior**
Information about missing slug.

**Screenshots**
![Zrzut ekranu z 2020-03-09 17-48-04](https://user-images.githubusercontent.com/52074703/76237385-83f34f80-622e-11ea-94e2-103f2afc772c.png)

**System**
- Node.js version: 12.16.1
- NPM version: 6.14.2
- Strapi version: beta 19.1
- Database: PostgreSQL 11.7
- Operating system: Debian 10.3

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this.
I would like @Aurelsicoko @alexandrebodin @soupette to give us the `id` and `message` to set up for this error.

**Comment by soupette** [comment]
I think it would be best if the back-end could juste send the error message without an `id`

**Comment by lanceliamll** [comment]
is there any response with this ? im experiencing this right now. just deployed my strapi. please help :(

**Comment by stijn-gravity** [comment]
What is the current status of this? We have been experiencing this issue for a while

**Comment by reld** [comment]
I am experiencing the same issue.
I try to create a new user using /auth/local/register but get.
`{
  "statusCode": 400,
  "error": "Bad Request",
  "message": [
    {
      "messages": [
        {
          "id": "Auth.form.error.email.taken",
          "message": "Email already taken"
        }
      ]
    }
  ],
  "data": [
    {
      "messages": [
        {
          "id": "Auth.form.error.email.taken",
          "message": "Email already taken"
        }
      ]
    }
  ]
}`

I double confirm that the email was not already taken.
Are there any workarounds?
Thank you.
cheers
R

**Comment by derrickmehaffy** [comment]
> Now I will test if I can also pass a role. That would be great if it works.

You will not be able to pass a role without customizing the code via extensions. We specifically disabled this as it's a security risk.

**Comment by ckyleda** [comment]
I have this issue, with additional fields (none set to required, but some components) in the user table.

This causes the aforementioned
```
"id":` "Auth.form.error.email.taken",
"message": "Email already taken"
```
What's the solution? At the very least this shouldn't be throwing back a useless red herring of an error.

Are custom fields on the user table not allowed? Is this documented anywhere? 

Using Strapi 3.2.5

**Comment by stijn-gravity** [comment]
@ckyleda we eventually ended up ignoring the default Strapi duplicate email message with a try catch, and implemented our own.

**Comment by marcopadillo** [comment]
It seems that any validation error thrown during registration will result to the `Email already taken` error message. I logged the `err` in this catch block in `extensions/users-permissions/controllers/Auth.js`
```
		} catch (err) {
			console.log(err);
			const existingUsernameError = {
				id: 'Auth.form.error.username.taken',
				message: 'Username already taken',
			};

			const adminError = _.includes(err.message, 'username')
				? existingUsernameError
				: { id: 'Auth.form.error.email.taken', message: 'Email already taken' };

			ctx.badRequest(null, formatError(adminError));
		}
```
and got:
```
Error: user validation failed: title: `1` is not a valid enum value for path `title`.
```
After fixing the value being passed by the front-end, I was able to register successfully. No need to remove those required fields. Just find out the exact validation error being thrown.

P.S. If you don't require `username` during registration, you should set it with the same value as the email.

**Comment by AxelPariss** [comment]
This error is probably because you have required fields to your User model. For example, I added "firstname" as required and I need to provide this field in my request to have a success result.

**Comment by kindziora** [comment]
having the same issue on: v3.5.3

As mentioned by @derrickmehaffy in https://github.com/strapi/strapi/issues/9398 input validation for user registration does not work correctly and code needs larger refactoring... is there already a branch we can work on / or test (bc this bug seems like a year old)?

Another easy improvement would be the following:

renaming the error from:
` message: 'Email already taken' 
`

to something like:

` message: 'Unkown validation error occured'
`

Located here:

https://github.com/strapi/strapi/blob/3065d72a4b9ef04a94bb5f3f62683cf59712e69b/packages/strapi-plugin-users-permissions/controllers/Auth.js#L514,L519

Because otherwise its quite missleading ;)

**Thanks**

**Comment by derrickmehaffy** [comment]
> As mentioned by @derrickmehaffy in #9398 input validation for user registration does not work correctly and code needs larger refactoring... is there already a branch we can work on / or test (bc this bug seems like a year old)?

No we haven't started working on it.

**Comment by ahmadkhudeish** [comment]
@derrickmehaffy Further to the comment above by @marcopadillo 
My experience with this issue was that I created a unique (non-required) string field inside the Users content type. 
When I was registering a user through this endpoint, it was giving me an error related to the Email being taken which isn't the case as I don't have that email or username. When I added the field to my registration payload the problem stopped happening. The error I received for the email taken has nothing to do with the actual error that occurred which was related to the unique value not in the payload I supplied.

**Comment by JonathanSchndr** [comment]
Very important tip, this was also a bug with me: If you extend the user entity with own fields, which are required fields, unfortunately also the error "Email already taken" comes - although of course not the mail are the error, but your missing required field :)

**Comment by moadw** [comment]
This is related to username. It's mandatory although you add required false. If you create a user 1  without username, the field  will be empty. Trying to create a second user without username will equal the empty username in user 1. It is returning an incorrect message (talking about the email), but the register endpoint should only email or username. Not both.

**Comment by derrickmehaffy** [comment]
fixed in v4 I believe

**Comment by georgeiliadis91** [comment]
I am still experiencing this issue, on 3.6.8 (the image from docker hub)
