### ISSUE TITLE
Cannot add two decimals on number collection type

### ISSUE THREAD

**Issue by ssayanm** [strapi/strapi#7401]
**Describe the bug**
I cannot add two decimals on the number collection type 

**Steps to reproduce the behavior**

1. Go to 'Create a collection type and enter a Display name'
2. "Select a field for your collection type" -> Choose Number and choose "Number format" as either "decimal or "float"
3. Scroll down to 'Collection Types' and try to add a number ending with two or more than two decimal places like "40.12" or "100.234"

**Expected behavior**
I should be able to add numbers with more than two decimal places like 40.123 or 100.234

**Screenshots**
[Screenshot1](https://u.pcloud.link/publink/show?code=XZo52vkZnE9KRVEGNLunJpmtYr23qSPrqFAy)
[Screenshot2](https://u.pcloud.link/publink/show?code=XZLJ2vkZkWB28T5cOjYyo0bVnfPytjKnOIRk)

**System**

- Node.js version: 12.18.3 
- NPM version: 6.14.7
- Strapi version: v3.1.3 
- Database: SQLite
- Operating system: Mac Os Catalina

Thank you !

**Comment by derrickmehaffy** [comment]
Hi @ssayanm I have spoken with our frontend team to make them aware of this issue, I believe we have a fix and should have a PR made shortly. You will see the PR attached to the issue once it's ready and should be included in the next release (of course you can make the change manually in the short term using the extensions system if you need it).

**Comment by ssayanm** [comment]
@derrickmehaffy thank you so much !

**Comment by psycoder17** [comment]
I am also facing this issue when trying to store latitude/longitude values. Can you be more specific on where I can make the change in the extension/plugin system? I took a look through some of the modules but couldnt find exactly what I was looking for. Thanks!

**Comment by derrickmehaffy** [comment]
@psycoder17 @ssayanm this should be fixed in the 3.1.4 release

**Comment by ssayanm** [comment]
@derrickmehaffy you mean 3.1.5 release right? 
I am still getting that issue on v3.1.4

[screenshot](https://u.pcloud.link/publink/show?code=XZ4ASyXZSL4c358BAM8zOXj2Tp0SHfglRGqk)

**Comment by psycoder17** [comment]
I am also on 3.1.4 and can confirm the issue has not yet been resolved. I'm happy to test any suggestions your team has.

**Comment by derrickmehaffy** [comment]
Hi guys I just tested with a fresh 3.1.4 project and it appears to work fine for me, can you try to run a rebuild of your admin?

![image](https://user-images.githubusercontent.com/8593673/90645743-2c004200-e1eb-11ea-80be-2757a514a99f.png)

**Comment by psycoder17** [comment]
Just ran an `npm run build`. Still receiving this popup message, and am unable to save the record.
<img width="491" alt="Screen Shot 2020-08-19 at 10 19 10 AM" src="https://user-images.githubusercontent.com/64004929/90646778-94f4b380-e205-11ea-8152-f9a350804585.png">

**Comment by derrickmehaffy** [comment]
Do you have any mix/max values?

**Comment by ssayanm** [comment]
![Screenshot 2020-08-19 at 7 55 33 PM](https://user-images.githubusercontent.com/4533076/90647545-0c523380-e256-11ea-8b71-99ee636567c6.jpg)
working on brave and safari but not on firefox, i cleared cache, rebuild a few times but still not working on firefox.

**Comment by psycoder17** [comment]
I do not. Nothing is set in the Advanced Settings tab.

**Comment by psycoder17** [comment]
I am also using FF. Let me try Chrome.

**Comment by derrickmehaffy** [comment]
Yup it's there on firefox (I generally use chrome) I will ping @soupette and @HichamELBSI and let them know.

**Comment by ssayanm** [comment]
thank you @derrickmehaffy

**Comment by psycoder17** [comment]
Chrome seems to let me save the record, but still clips the decimal down to 2 decimal places after I press save.

**Comment by derrickmehaffy** [comment]
That is intended @psycoder17, currently the default accuracy level of decimal is only 2 places on certain databases (PG/MySQL/MariaDB) I already have an open request to allow configuration of this here: https://github.com/strapi/strapi/issues/1330

**Comment by psycoder17** [comment]
Got it. Thanks so much for your quick help!

**Comment by derrickmehaffy** [comment]
@psycoder17 @ssayanm can you guys try using the extensions system and update that file in the linked PR and see if that fixes your issue?

**Comment by psycoder17** [comment]
Left a comment on the PR. I tried that same solution last night and it wasnt working for me on FireFox, but all seems to be doing well now on Chrome. I can put a note in the README about the possible incompatibility when I have some time later if you'd like.

**Comment by psycoder17** [comment]
I used this as a reference for some of my troubleshooting last night: https://github.com/strapi/strapi/pull/7178
