### ISSUE TITLE
Plugin users-permissions providers Custom callback url doesn't work 

### ISSUE THREAD

**Issue by qunabu** [strapi/strapi#7405]
**Describe the bug**

Passing callback url instead of using the default registered provider callback doesn't seems to be working. In my case I'm using SPA on many domains with one API. In this case i need the API to redirect to correct SPA instance. 

```
GET https://API.com/connect/facebook?callback=https://DOMAIN1.com/en/auth/google
GET https://API.com//connect/facebook?callback=https://DOMAIN2.com/en/auth/google
GET https://API.com//connect/facebook?callback=https://DOMAIN3.com/en/auth/google
``` 
is not working as expected 

**Steps to reproduce the behavior**

Follow tutorial on https://strapi.io/documentation/v3.x/plugins/users-permissions.html#providers part that says 

> You can also pass a custom callback url instead of using the default registered provider callback, by passing callback in the query. eg: GET /connect/facebook?callback=https://my-frontend.com/en/auth/facebook.

I was testing Google OAuth. 

**Expected behavior**

URL like http://localhost:5000/connect/google?callback=http://localhost:3001/connect/google should redirect to http://localhost:3001/connect/google after successful login. 

Seems like `callback` is not a valid name to be passed to OAuth provider and this is trimmed from actual call, so once Provider redirects back to API callback url is lost. What I have found out that `state` is a parameter that can be used here (https://developers.google.com/identity/protocols/oauth2/web-server) 

> You can use this parameter for several purposes, such as directing the user to the correct resource in your application, sending nonces, and mitigating cross-site request forgery.

**Code snippets**

Changing the following code seems to be fixing the issue 
https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L264
```js
    // Ability to pass OAuth callback dynamically
    grantConfig[provider].callback = _.get(ctx, 'query.callback') || _.get(ctx, 'query.state') || grantConfig[provider].callback;
    grantConfig[provider].state = _.get(ctx, 'query.callback') || grantConfig[provider].callback;
```

**System**

- Node.js version: v12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.0
- Database: sqlite
- Operating system: MacOS 10.15.5

**Additional context**

I'm not creating a MR so far, because I'm not sure if my solution is valid, I'm not OAuth expert and I haven't tested any other providers except Google.

**Comment by derrickmehaffy** [comment]
>Strapi ^3

Can you please properly fill out this section so that we can try to reproduce the issue?

```
- Node.js version: <!-- Please ensure you are using the Node LTS version (v12) -->
- NPM version:
- Strapi version: <!-- Beta and Alpha versions are no longer supported -->
- Database:
- Operating system:
```

**Comment by qunabu** [comment]
> Can you please properly fill out this section so that we can try to reproduce the issue?

Done

**Comment by derrickmehaffy** [comment]
@petersg83 Is this already solved with https://github.com/strapi/strapi/pull/7132 and https://github.com/strapi/strapi/pull/7054 / https://github.com/strapi/strapi-examples/pull/164 ?

**Comment by petersg83** [comment]
Hi, thanks for the issue!
I don't think it's solved, it may be a regression. I'll look into it as soon as I can :)

**Comment by qunabu** [comment]
@petersg83 If you think my proposed solutions looks fine I can create a MR.

**Comment by petersg83** [comment]
Yes that would be nice, thank you :) I'll take a look at it probably next week

**Comment by qunabu** [comment]
@petersg83 https://github.com/strapi/strapi/pull/7578

**Comment by rkrueger11** [comment]
Hey there, I'm on Strapi 3.3.3 and I'm still having this issue (also using Facebook Login as a provider). However, I'm fairly inexperienced with OAuth, so I could just be misunderstanding the correct redirect flow.

It looks like the fix in #7578 correctly sets the callback for the initial request to the Strapi backend api route, but then when the provider hits the Strapi route with the `code`, it no longer contains the custom callback url. 

Do we need something to persist that custom callback url? Or maybe we need to be sending that along to the provider, so they can send it back to us?

**Comment by borm** [comment]
only `state` returning back when we provide that here
https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L264
```js
grantConfig[provider].custom_params = { state: 'SOME_STATE' };
```

**Comment by DavidVrgs** [comment]
> only returning back when we provide that here
> https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L264`state`
> 
> ```js
> grantConfig[provider].custom_params = {
>   state: 'SOME_STATE_WILL_RETURN_IN_QUERY',
>   some: 'SOME_WILL_NOT_RETURN_IN_QUERY'
> };
> 
> ...
> then
> _.get(ctx, 'query.state')
> ```
> 
> my tmp solution
> go to [Auth.js#L264](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L264) and change
> 
> ```
> grantConfig[provider].callback = _.get(ctx, 'query.callback') || grantConfig[provider].callback;
> ```
> 
> to
> 
> ```
> grantConfig[provider].custom_params = _.get(ctx, 'query');
> grantConfig[provider].callback = _.get(ctx, 'query.callback') || _.get(ctx, 'state.session.grant.dynamic.callback') || grantConfig[provider].callback;
> ```
> 
> about **Author** @qunabu solution, also good, but on my case we can send more params and read its then

Hello, I'm using Strapi 3.3.4 and in my project files does not find that auth.js file. I need to do something before to generate that file?

![image](https://user-images.githubusercontent.com/28511980/102516678-231a6280-405d-11eb-9307-d1c54fcd7733.png)

**Comment by kiril-daskalov** [comment]
Any update?

**Comment by petersg83** [comment]
Thank you all and thank you @borm for showing the fix.
I made the modification in #11825. Should be fixed once merged.
