### ISSUE TITLE
Count Metadata doesn't take filtering into account

### ISSUE THREAD

**Issue by sebqq** [strapi/strapi#7631]
Hello.

I have this situation, where `{entity}/count` REST endpoint with deep filtering and using '_or' clause is not working properly. Count value is even bigger than number of items that are stored in my db (of that type) at time of request.

So we have these two tables: Dogs and Colors. Every dog can have multiple colors assigned using following relation:

<img width="918" alt="Screenshot 2020-08-27 at 19 13 11" src="https://user-images.githubusercontent.com/33039909/91473947-e4884e80-e899-11ea-989a-7607ffe31774.png">

Please look at following picture to see, what query params are comming from our Frontend to strapi endpoint (endpoint is overriden only for purposes of this test. We normally use pre-generated endpoint):

<img width="865" alt="Screenshot 2020-08-27 at 19 26 00" src="https://user-images.githubusercontent.com/33039909/91474928-2a91e200-e89b-11ea-871b-15c3d28a0ef2.png">

As you can see, I have 11 dogs in my development DB, but count endpoint has provided **15** as result.

**Cause of the issue is the most probably a fact, that some of dogs have multiple colors assigned. When I use only 1 color per dog, thne the filtering problem dissapears.**

Does anyone know, what could be the reason for this behaviour?

Thank you so much and have a nice day!

**System**

- Strapi version: 3.1.4
- Database: tried on SQLite and PostgreSQL
- Operating system: macOS Catalina

**Comment by derrickmehaffy** [comment]
Hello,

I tested this on all supported databases and it appears to be working fine (not your custom controller but just the built in default count routes)

**Comment by emahuni** [comment]
I am having this issue as well

**Comment by emahuni** [comment]
le me try to have a go at it

**Comment by derrickmehaffy** [comment]
@emahuni can you provide any steps to reproduce the issue because I haven't been able to.

**Comment by emahuni** [comment]
I am trying to figure out the reason why it's happening. Here is the funny thing. The same code filtering the same model, but just different records is producing the bug and another is not. ie:

```graphql
query convs {
  conversationsConnection(
    where: {
      assignedTo: "115"
      disposition: { id: "136", departments_in: ["79", "83"] }
    }
  ) {
    aggregate {
      count
    }
  }
}
```
is counting 4 instead of 2 (note that it's always doubling when this happens), but the following:
```graphql
query convs2 {
  conversationsConnection(
    where: {
      assignedTo: "115"
      disposition: { id: "108", departments_in: ["79", "83"] }
    }
  ) {
    aggregate {
      count
    }
  }
}
```
is counting 12 as expected. So I want to go through each record to see any anomalies that I can associate with the bug, because it seems like there is something about the records that is causing the code to misinterpret things.

**Comment by emahuni** [comment]
important models and associations:

`Conversation.settings.json`:
```json
{
    "attributes": {
      "assignedTo": {
        "model": "employee",
        "via": "assignedConversations"
      },
      "disposition": {
        "model": "disposition"
      }
    }
}
```

`Disposition.settings.json`:
```json
  {
    "attributes": {
      "departments": {
        "via": "dispositions",
        "collection": "department",
        "dominant": true
      }
    }
  },
```

`Employee.settings.json`:
```json
  {
    "attributes": {
      "assignedConversations": {
        "via": "assignedTo",
        "collection": "conversation"
      }
    }
  }
```

**Comment by emahuni** [comment]
I think I now have a lead. You see, the records retrieved by the first query with disposition `136` are doubling becoz its disposition is associated with both departments it asked for, but the second query for disposition `108` is associated with only 1 of the departments it asked for.

One of the records values for the first query (producing bug), notice departments `79` and `83` are present in the following:
```json
"values": [
        {
          "id": "392",
          "disposition": {
            "id": "136",
            "departments": [
              {
                "id": "44"
              },
              {
                "id": "79"
              },
              {
                "id": "80"
              },
              {
                "id": "81"
              },
              {
                "id": "83"
              }
            ]
          }
        },
]
```

but not in one of the records values for the second query, notice only department `79` is present in the following (working query):
```json
"values": [
        {
          "id": "4",
          "disposition": {
            "id": "108",
            "departments": [
              {
                "id": "44"
              },
              {
                "id": "79"
              }
            ]
          }
        },
]
```

It works as expected if I remove department `83` and change the query to: 
```graphql
query convs {
  conversationsConnection(
    where: {
      assignedTo: "115"
      disposition: { id: "136", departments_in: ["79"] }
    }
  ) {
    aggregate {
      count
    }
  }
}
```

This means the code is counting for each department found when there is an `_in` filter. This is where we start from. Somehow the code is not counting correctly when it's like that.

So to reproduce, create those models with those associations and records as depicted. You should be able to reproduce it.

**Comment by emahuni** [comment]
Just to assert this, if I ask for department "80" on the above query to make the total of 3 departments associated with disposition `136` it triples. ie:
```graphql
query convs {
  conversationsConnection(
    where: {
      assignedTo: "115"
      disposition: { id: "136", departments_in: ["79", "83","80"] }
    }
  ) {
    aggregate {
      count
    }
  }
}
```
That produces `6` instead of 2. That's 2 for each department. Happens for each department I add that is associated with disposition.

**Comment by iksent** [comment]
I probably have the same bug:

![2020-11-13_14-40-56](https://user-images.githubusercontent.com/32956521/99057999-6006bb80-25be-11eb-9b20-2c610a91d8b2.png)

**Comment by derrickmehaffy** [comment]
@emahuni @iksent This issue is only for REST not GraphQL, there is a related issue for GraphQL related count aggregations here: https://github.com/strapi/strapi/issues/7547

**Comment by iksent** [comment]
Any updates on this?

There is probably no solution now for fetching "relational" items with count (neither with `aggregate.count,` nor with [this guide](https://strapi.io/documentation/v3.x/guides/count-graphql.html#setup-the-application) due [to the bug](https://github.com/strapi/strapi/issues/7547)).

So it's impossible to create paginated lists.

**Comment by Limonische** [comment]
So is there any workaround for REST?

**Comment by iksent** [comment]
My temporary solution:

`/api/MODEL/services/MODEL.js`

```
"use strict";
const size = require("lodash/size");
const omit = require("lodash/omit");
const { convertToQuery } = require("strapi-plugin-graphql/services/utils");
const { convertToParams } = require("strapi-plugin-graphql/services/utils");

module.exports = {
  async filter(params) {
    const filters = {
      ...convertToParams(omit(params, "where", "limit", "start")),
      ...convertToQuery(params.where),
    };
    const data = await strapi.query("doctor").find(filters);
    return {
      count: size(data),
      doctors:
        size(data) > 0 ? data.slice(params.start, params.start + params.limit) : [],
    };
  },
};
```

------

`/api/MODEL/config/schema.graphql.js`

```
module.exports = {
  definition: `
    type FilterOut {
      count: Int
      doctors: [Doctor]
    }
  `,
  query: `
    doctorsFilter(sort: String, limit: Int, start: Int, where: JSON): FilterOut
  `,
  resolver: {
    Query: {
      doctorsFilter: {
        description: "Return the list of filtered doctors",
        resolverOf: "application::doctor.doctor.find",
        policies: [],
        resolver: async (obj, options, ctx) => {
          return await strapi.api.doctor.services.doctor.filter(options);
        },
      },
    },
  },
};
```

**Comment by alexey13** [comment]
Same here. When we use filter count response incorrect. If the item in several entities it counts it every time. Example: t-shirt(product) in categories shirts and mens wear. /products/count?categories.slug=mens-wear&categories.slug=shirts result: 2

**Comment by goodpixels** [comment]
Same problem. I have a relation field many:many and the count returns the number of related items, not the count of the parent items.

**Comment by dimver1** [comment]
@derrickmehaffy Hello guys! Almost half a year this very important issue is open... Basically, every developer who builds for example an online store with simple filtering and of course pagination, is not able to do that without correct count of filtered items... am not sure why it is set to low priority as it is very important for hundreds of websites. Unfortunately all the temporary solutions are not good because those are absolutely not optimized and 10x times slower than correct count request to a database... (this issue is the same for grapghql and for REST requests).  thank you very much for understanding and for your work guys!

**Comment by obendi** [comment]
Any updates on this bug?

**Comment by SalahAdDin** [comment]
> My temporary solution is to retrieve all elements from DB, count it and slice on Strapi:
> 
> `/config/plugins.js`
> 
> ```
> module.exports = {
>   graphql: {
>     amountLimit: 1000, // Fix maximum 100 elements issue
>   },
> };
> ```
> 
> **Be aware: may be this won't work for REST, I was using it via graphql only**
> 
> `/api/MODEL/services/MODEL.js`
> 
> ```
> "use strict";
> const size = require("lodash/size");
> const omit = require("lodash/omit");
> const { convertToQuery } = require("strapi-plugin-graphql/services/utils");
> const { convertToParams } = require("strapi-plugin-graphql/services/utils");
> 
> module.exports = {
>   async filter(params) {
>     const filters = {
>       ...convertToParams(omit(params, "where", "limit", "start")),
>       ...convertToQuery(params.where),
>     };
>     const data = await strapi.query("doctor").find(filters);
>     return {
>       count: size(data),
>       doctors:
>         size(data) > 0 ? data.slice(params.start, params.start + params.limit) : [],
>     };
>   },
> };
> ```
> 
> `/api/MODEL/config/schema.graphql.js`
> 
> ```
> module.exports = {
>   definition: `
>     type FilterOut {
>       count: Int
>       doctors: [Doctor]
>     }
>   `,
>   query: `
>     doctorsFilter(sort: String, limit: Int, start: Int, where: JSON): FilterOut
>   `,
>   resolver: {
>     Query: {
>       doctorsFilter: {
>         description: "Return the list of filtered doctors",
>         resolverOf: "application::doctor.doctor.find",
>         policies: [],
>         resolver: async (obj, options, ctx) => {
>           return await strapi.api.doctor.services.doctor.filter(options);
>         },
>       },
>     },
>   },
> };
> ```

Can you give us an example about your query?

**Comment by iksent** [comment]
> Can you give us an example about your query?

Here is my query with `doctorsFilter` name:

```gql
query Doctors(
  $start: Int = 0
  $limit: Int
  $clinic: ID
  $specialty: ID
  $search: String
  $therapies: [String]
) {
  doctorsFilter(
    sort: "last_name:asc"
    start: $start
    limit: $limit
    where: {
      _or: [
        {
          therapies_null: true
          specialty: { id: $specialty, services: { therapies: { slug_in: $therapies } } } <<< THIS IS A PROBLEM for pagination
          clinics: $clinic
          _or: [
            { last_name_contains: $search }
            { first_name_contains: $search }
            { patronymic_contains: $search }
          ]
        }
        {
          therapies_null: false
          therapies: { slug_in: $therapies }
          specialty: { id: $specialty }
          clinics: $clinic
          _or: [
            { last_name_contains: $search }
            { first_name_contains: $search }
            { patronymic_contains: $search }
          ]
        }
      ]
    }
  ) {
    count
    doctors {
      ...
    }
  }
}
```

**Comment by dimver1** [comment]
Hi guys, this temporary solution is very slow, just because you will have to pull **all** your thousands of elements from db. 

@derrickmehaffy is it possible to fix this count issue so we can use Strapi on real projects? Thank you

**Comment by derrickmehaffy** [comment]
> Hi guys, this temporary solution is very slow, just because you will have to pull **all** your thousands of elements from db.
> 
> @derrickmehaffy is it possible to fix this count issue so we can use Strapi on real projects? Thank you

There are some fundamental issues at the database layer, most likely (since this is a bigger issue than just counting) it won't be fixed until the database layer rework in Q3 for the v4 but I am just spitballing here

**Comment by luixal** [comment]
Hi,

I'm not sure this is related, but I'm getting errors without deep filtering. My collections have relationships, but I'm only filtering data between 2 dates:

```
https://my.server.com/visits/count?updated_at_gt=2021-10-12T22:00:00.000Z&updated_at_lt=2021-10-15T21:59:59.999Z
```

it throws a 500 error, logging a related error in postgres:

```
2021-10-15 07:09:12.077 UTC [231] ERROR:  could not find pathkey item to sort
2021-10-15 07:09:12.077 UTC [231] STATEMENT:  select distinct count(*) as "count" from "visits" where "visits"."created_at" > $1 and "visits"."created_at" < $2
```

The same happens if I use the `count` method using `created_at_gt` and `created_at_lt`.

Thing is, this **used to** work it just stopped one day and then it keeps crashing.

**Comment by derrickmehaffy** [comment]
FYI the count route and GQL query will be removed in v4 as all requests will now return a count regardless

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed

**Comment by p-gw** [comment]
For me this issue is still present in v4. In my example I have an `article` content-type and a `tag` content-type which are connected by a many-to-may relationship. 

If I query `articles` using a deep filter on `tags` I still get the incorrect count of articles.

query: 
```
http://localhost:1337/api/articles?filters[tags][id][$in][0]=2&filters[tags][id][$in][1]=1&populate=tags
```

response:
```json
{
   "data":[
      {
         "id":3,
         "attributes":{
            "title":"Third article",
            "content":null,
            "createdAt":"2021-12-09T16:31:08.819Z",
            "updatedAt":"2021-12-09T16:31:08.819Z",
            "tags":{
               "data":[
                  {
                     "id":1,
                     "attributes":{
                        "tag":"tag 1",
                        "createdAt":"2021-12-09T15:59:57.202Z",
                        "updatedAt":"2021-12-09T15:59:57.202Z"
                     }
                  },
                  {
                     "id":2,
                     "attributes":{
                        "tag":"tag 2",
                        "createdAt":"2021-12-09T16:00:04.267Z",
                        "updatedAt":"2021-12-09T16:00:04.267Z"
                     }
                  }
               ]
            }
         }
      },
      {
         "id":2,
         "attributes":{
            "title":"Second Article",
            "content":null,
            "createdAt":"2021-12-09T16:00:56.962Z",
            "updatedAt":"2021-12-09T16:23:38.742Z",
            "tags":{
               "data":[
                  {
                     "id":1,
                     "attributes":{
                        "tag":"tag 1",
                        "createdAt":"2021-12-09T15:59:57.202Z",
                        "updatedAt":"2021-12-09T15:59:57.202Z"
                     }
                  },
                  {
                     "id":2,
                     "attributes":{
                        "tag":"tag 2",
                        "createdAt":"2021-12-09T16:00:04.267Z",
                        "updatedAt":"2021-12-09T16:00:04.267Z"
                     }
                  },
                  {
                     "id":3,
                     "attributes":{
                        "tag":"tag 3",
                        "createdAt":"2021-12-09T16:00:11.444Z",
                        "updatedAt":"2021-12-09T16:00:11.444Z"
                     }
                  }
               ]
            }
         }
      }
   ],
   "meta":{
      "pagination":{
         "page":1,
         "pageSize":25,
         "pageCount":1,
         "total":4
      }
   }
}
```

The total count of 4 is obviously wrong since the response only contains 2 articles.
The GraphQL API also gives the same incorrect count.

**Comment by derrickmehaffy** [comment]
Confirmed on v4, reopening the count isn't reflecting the filters.

**Comment by schicwp** [comment]
The generated for counting looks wrong to me:

`
select count(*) as `count` from  .....
`

Looks like what is used to get the pagination values - this is fine as long as you are not doing a join which results in multiple rows per queried entity. When filtering on a 1-to-many relationship this is a problem. 

I worked around this by having an a corrected count call (its a kind of ugly hack) which looks something like this `select count(distinct `t0`.`id`) as `count` from ... ` - but fixing this in the code would very good

**Comment by dqvn** [comment]
> The SQL generated for counting looks wrong to me:
> 
> `select count(*) as`count`from .....`
> 
> Looks like what is used to get the pagination values - this is fine as long as you are not doing a join which results in multiple rows per queried entity. When filtering on a 1-to-many relationship this is a problem.
> 
> I worked around this by having an a corrected count call (its a kind of ugly hack) which looks something like this `select count(distinct `t0`.`id`) as `count`from ...` - but fixing this in the core would very good

Could you please show more detail how to quick fix it outside the core-fixed? (Which file to be modified?)

**Comment by Webbist-dev** [comment]
This issue is causing us problems now, my only workaround is manually set a total in the frontend state from an initial query as a basis for the  page numbers

**Comment by giorgiPapava** [comment]
Is this in active development? How long would it take to fix this? And what's the best workaround for it so far? We need to override model right?

**Comment by derrickmehaffy** [comment]
Status: No ETA at the moment
In development: No, the Product manager needs to review the issue and schedule it in one of our sprints
Workaround: None atm

If anyone is willing to look at the issue and submit a fix, please feel free. We will get to it once we have some time, there is a lot of high priority tasks at the moment and we are still a small team :pray:

**Comment by Webbist-dev** [comment]
@derrickmehaffy There is a hacky workaround although it required multiple queries. We're using this in production at the moment. 
Make a query for all - to get count, basically, length check on a returned array. 
Use that to make pagination work in a second pagination query.

**Comment by SalahAdDin** [comment]
> @derrickmehaffy There is a hacky workaround although it required multiple queries. We're using this in production at the moment. Make a query for all - to get count, basically, length check on a returned array. Use that to make pagination work in a second pagination query.

isn't it bad regard to performance?

**Comment by RicardoLome** [comment]
Hello, I'm still quite new to this, and I hope I'm not saying something obvious, but doing different tests I realized the following. Explained in a simple way it would be something like this:

![image](https://user-images.githubusercontent.com/61388726/152858166-259150ff-1c2c-46e0-a5c0-bfec247e8d6e.png)

When you search product with the line what have the categorie === "Cat_1" bring result 2 products, but in meta.pagination.total = 4

**Comment by derrickmehaffy** [comment]
> > @derrickmehaffy There is a hacky workaround although it required multiple queries. We're using this in production at the moment. Make a query for all - to get count, basically, length check on a returned array. Use that to make pagination work in a second pagination query.
> 
> isn't it bad regard to performance?

very bad yes

**Comment by Webbist-dev** [comment]
Never said it was a good workaround, but luckily our production data sets currently max out at 200 items, we're using graphql, so we limit the response by just getting collections id's out and running a length check against the returned array

**Comment by derrickmehaffy** [comment]
> Never said it was a good workaround, but luckily our production data sets currently max out at 200 items, we're using graphql, so we limit the response by just getting collections id's out and running a length check against the returned array

Ideally the fix is simple, filters need to be passed into the count query and they aren't.

**Comment by Webbist-dev** [comment]
This appears to have been fixed in 4.1.2
At least the issue I previously had in GraphQL count doesn't seem to be an issue now.

**Comment by jimunfold** [comment]
I’m still having this issue in 4.1.2

**Comment by dqvn** [comment]
I am having Sites -- 1:M --> Districts
After my real logs I see the issue come from the count query. For detail, the count query is missing distinct conditions as the full data query as below:
![image](https://user-images.githubusercontent.com/7709802/158749687-78956079-9b06-408b-b0da-7d7d8741164a.png)

A/ Full dataquery: -> return 9 rows
sql: '**select distinct "t0"."name_with_type", "t0"."id", "t0"."name_with_type"** 
from "public"."districts" as "t0" left join "public"."sites_district_links" as "t1" on "t0"."id" = "t1"."district_id" left join "public"."sites" as "t2" on "t1"."site_id" = "t2"."id" left join "public"."districts_city_links" as "t3" on "t0"."id" = "t3"."district_id" left join "public"."cities" as "t4" on "t3"."city_id" = "t4"."id" where (not ("t2"."name" is null) and "t4"."id" = ?) order by "t0"."name_with_type" asc limit ?'

B/ Count data for meta pagingnation: -> return 16 rows
sql: '**select count(*) as "count"** 
from "public"."districts" as "t0" left join "public"."sites_district_links" as "t1" on "t0"."id" = "t1"."district_id" left join "public"."sites" as "t2" on "t1"."site_id" = "t2"."id" left join "public"."districts_city_links" as "t3" on "t0"."id" = "t3"."district_id" left join "public"."cities" as "t4" on "t3"."city_id" = "t4"."id" where (not ("t2"."name" is null) and "t4"."id" = ?) limit ?'

The right query for count (Full Dataquery) should be:
**select count( distinct "t0"."name_with_type") as "count"** 
from "public"."districts" as "t0" left join "public"."sites_district_links" as "t1" on "t0"."id" = "t1"."district_id" left join "public"."sites" as "t2" on "t1"."site_id" = "t2"."id" left join "public"."districts_city_links" as "t3" on "t0"."id" = "t3"."district_id" left join "public"."cities" as "t4" on "t3"."city_id" = "t4"."id" where (not ("t2"."name" is null) and "t4"."id" = ?) limit ?'

Does anyone know which class (file/func) is managing this SQL generation? I think we just modify by adding the distinct SQL on first field will solve the problem!!!

**Comment by ScyDev** [comment]
> Does anyone know which class (file/func) is managing this SQL generation? I think we just modify by adding the distinct SQL on first field will solve the problem!!!

@derrickmehaffy can you please give us a hint where this query is generated, so we could have a workaround?

**Comment by mchrapek** [comment]
I’m still having this issue in **4.1.8**

**Comment by avirankatz** [comment]
Any news on this issue? @derrickmehaffy could you please point us to the relevant query?

**Comment by derrickmehaffy** [comment]
> Any news on this issue? @derrickmehaffy could you please point us to the relevant query?

I haven't explored the issue in depth to be honest. I know the issue will likely be in the database package or in the core entityService but I haven't dug to locate the exact location.

**Comment by 43ClicksNorthDevs** [comment]
Be nice if this one was looked at - any data filtered by more than one filter returns an incorrect count.
This means pagination is impossible without a jank workaround. Impacting live projects for us now.

**Comment by derrickmehaffy** [comment]
> Be nice if this one was looked at - any data filtered by more than one filter returns an incorrect count. This means pagination is impossible without a jank workaround. Impacting live projects for us now.

We know the problem is troublesome, if anyone is willing and has the free time to dive into the issue to submit a pull request please feel free, else we will get it to in due course once we have some engineers free.

**Comment by emahuni** [comment]
This issue is preventing from using the aggregate feature at all coz we don't trust results. I've opted to using another library for analytics / business intelligence, but it's best if this fixed. As I said last time, the issue is with association. See related post above. As long as this is happening the issue is still there, that's I see all the time I try to use this feature. And @derrickmehaffy it is a graphql issue, that's all graphql not rest. I am sure it does the same with rest as well though, haven't tested it.

**Comment by derrickmehaffy** [comment]
This applies to both GraphQL and REST as the issue is in the database layer

**Comment by schicwp** [comment]
This is terrific, thank you very much - this really reduces the number
hacks and workarounds needed for some of the queries that come up.

**Comment by SalahAdDin** [comment]
> @mithenks awesome thank you so much.
> 
> CC @marcoautiero / @Convly

So, it is a definitive fix, right?

**Comment by derrickmehaffy** [comment]
> > @mithenks awesome thank you so much.
> > CC @marcoautiero / @Convly
> 
> So, it is a definitive fix, right?

Aren't sure yet, this is why I tagged some of our internal team to review :wink:

**Comment by ntarandek** [comment]
Manually edited the 4.1.12 - works like a charm! Please, if anyway possible, include it in next update since I am 100% sure this issue is a deal breaker for many people (me included of course ;))

**Comment by SalahAdDin** [comment]
> Manually edited the 4.1.12 - works like a charm! Please, if anyway possible, include it in next update since I am 100% sure this issue is a deal breaker for many people (me included of course ;))
> 
> Should have mentioned: I use REST queries in this particular instance.

Could you do a pull request or a gist?

Thank you!

**Comment by ntarandek** [comment]
Since I do not have dev evn setup for Strapi and am too budy with projects - best I can do at the moment is this c/p.
Just notice // HERE comments - that is exactly what @mithenks did - this is just in 4.1.12 code. 

If anyone is ready to create a PR - please do so.

`getKnexQuery() {
      if (!state.type) {
        this.select('*');
      }

      const aliasedTableName = this.mustUseAlias() ? `${tableName} as ${this.alias}` : tableName;
      const tableNameToUse = this.mustUseAlias() ? `${this.alias}` : tableName; // HERE - added line

      const qb = db.getConnection(aliasedTableName);

      if (this.shouldUseSubQuery()) {
        return this.runSubQuery();
      }

      this.processState();

      switch (state.type) {
        case 'select': {
          qb.select(state.select.map(column => this.aliasColumn(column)));

          if (this.shouldUseDistinct()) {€
            qb.distinct();
          }

          break;
        }
        case 'count': {
          // qb.count({ count: state.count }); // HERE - commented out
          if (_.has('id', meta.attributes)) { // HERE - added block
            qb.countDistinct({ count: `${tableNameToUse}.id` });
          } else {
            qb.count({ count: state.count });
          }
          break;
        }`

**Comment by mithenks** [comment]
For anyone that would to try this patch, please consider use `patch-package` instead of manually edit source code. 
See: https://www.npmjs.com/package/patch-package 

Basically you need to

1) add a `postinstall` task in `packages.json`

```
"scripts": {
+  "postinstall": "patch-package"
 }
```

2) install `patch-package` dependency with `npm i patch-package` or `yarn add patch-package postinstall-postinstall`

3) place the patch file (unzipped) in a `patches` directory inside your project 

4) run `npm install` or `yarn install`

Here attached you can find the patch for version `4.1.2` of Strapi

[@strapi+strapi+4.1.12.zip](https://github.com/strapi/strapi/files/8868423/%40strapi%2Bstrapi%2B4.1.12.zip)

**Comment by PrinzJuliano** [comment]
> Since I do not have dev env setup for Strapi and I'm too busy with project(s) - best I can do at the moment is this c/p. Just notice // HERE comments - that is exactly what @mithenks did - this is just in 4.1.12 code.
> 
> If anyone is ready to create a PR - please do so.
> 
> ` getKnexQuery() { if (!state.type) { this.select('*'); }
> 
> ```
>   const aliasedTableName = this.mustUseAlias() ? `${tableName} as ${this.alias}` : tableName;
>   const tableNameToUse = this.mustUseAlias() ? `${this.alias}` : tableName; // HERE - added line
> 
>   const qb = db.getConnection(aliasedTableName);
> 
>   if (this.shouldUseSubQuery()) {
>     return this.runSubQuery();
>   }
> 
>   this.processState();
> 
>   switch (state.type) {
>     case 'select': {
>       qb.select(state.select.map(column => this.aliasColumn(column)));
> 
>       if (this.shouldUseDistinct()) {€
>         qb.distinct();
>       }
> 
>       break;
>     }
>     case 'count': {
>       // qb.count({ count: state.count }); // HERE - commented out
>       if (_.has('id', meta.attributes)) { // HERE - added block
>         qb.countDistinct({ count: `${tableNameToUse}.id` });
>       } else {
>         qb.count({ count: state.count });
>       }
>       break;
>     }
> ```
> 
> `

This actually fixes issues with deeply filtered and nested filtered.

**Comment by ntarandek** [comment]
Please do not alter the code directly as I did - this was you a test.

**Comment by mithenks** [comment]
Patch updated for Strapi 4.2.0

[strapi+database+4.2.0.patch.zip](https://github.com/strapi/strapi/files/8963519/strapi%2Bdatabase%2B4.2.0.patch.zip)

**Comment by Kaherdin** [comment]
Thanks @mithenks !

**Comment by ntarandek** [comment]
Changes in 4.3.0 require new patch - so here it is.

[@strapi+database+4.3.0.patch.zip](https://github.com/strapi/strapi/files/9199725/%40strapi%2Bdatabase%2B4.3.0.patch.zip)

**Comment by Webbist-dev** [comment]
When is this going to be looked at and rolled into core?

**Comment by louiejakebell** [comment]
i included a patch for this in our build for `v4.3.0` (it works as expected and corrects the pagination count when running the server locally 🙌)

however, i noticed that when it deployed to an environment the application w/ the postinstall patch it still had an incorrect pagination count when queried

**Comment by SalahAdDin** [comment]
> i included a patch for this in our build for `v4.3.0` (it works as expected and corrects the pagination count when running the server locally 🙌)
> 
> however, i noticed that when it deployed to an environment, the postinstall patch wasn't applied correctly (still had an incorrect pagination count when queried)

It is not the official version, right?

**Comment by ntarandek** [comment]
This is just a quick patch that @mithenks originally made, and I just updated it for 4.3.0 since underlying code changed. I have two projects in pre-production and this **needs** to work ;)

Since this works for me just fine on two pre-production projects (local dev and on online staging servers), and the not so detailed info given, I can not say why it does not fully work for @louiejakebell.

**Comment by Bassel17** [comment]
Just wanted to let everyone know that I am currently working on this issue, and I do plan to have it fixed in the next release.
and thanks to the work you have done on this issue fixing this problem will be a lot easier.
@ntarandek I will look in to your patch and test it out, it might be the fix we need!

**Comment by ntarandek** [comment]
> Just wanted to let everyone know that I am currently working on this issue, and I do plan to have it fixed in the next release. and thanks to the work you have done on this issue fixing this problem will be a lot easier. @ntarandek I will look in to your patch and test it out, it might be the fix we need!

Great news! But, just to clarify again, I was only the one that updated the patch for latest Strapi - @mithenks is where credits for the original patch/fix is due!

**Comment by emahuni** [comment]
@ntarandek may you please push it for ver 3 as well? 🙏🏽

**Comment by ntarandek** [comment]
> @ntarandek may you please push it for ver 3 as well? 🙏🏽

Sorry, I am absolutely unfamiliar with v3 since I do not use it at all :/

**Comment by louiejakebell** [comment]
> i included a patch for this in our build for `v4.3.0` (it works as expected and corrects the pagination count when running the server locally 🙌)
> 
> however, i noticed that when it deployed to an environment, the postinstall patch isn't applied correctly (still had an incorrect pagination count when queried) but this is likely something related to setup our end so i will investigate separately!

if anyone was curious or needs to know in the future why my postinstall patch fix wasn't deployed correctly, i wasn't copying the patch folder inside my dockerfile `COPY ./patches ./patches` previously..

**Comment by BorisKamp** [comment]
This still is not fixed in the latest strapi version, correct!? Why is it taking so long?

**Comment by SalahAdDin** [comment]
> This still is not fixed in the latest strapi version, correct!? Why is it taking so long?

I think they have other priorities right now, isn't it @derrickmehaffy ?

**Comment by Boegie19** [comment]
@BorisKamp 

> > This still is not fixed in the latest strapi version, correct!? Why is it taking so long?

This issue was closed since the issue was fixed. If it is not then please open a new issue with recriationsteps.

**Comment by c3s4** [comment]
I have the same issue with strapi 4.11.7, but in another project, where I use the 4.10.0, the same query works correctly.
