### ISSUE TITLE
Annoying Admin panel bugs

### ISSUE THREAD

**Issue by iksent** [strapi/strapi#7669]
**Describe the bug + Steps + Screenshots**
There are some bugs:

1. No "window.onbeforeunload" notice when clicking on link at wysiwyg field:

![wysiwyg](https://user-images.githubusercontent.com/32956521/91814376-79e66280-ec4d-11ea-8f2b-6d4e7960ead8.png)

**Expected behavior:** Notice is shown to prevent form losing OR all the links at wysiwyg with the _blank target.

2. Go to Article (or any other collection type), that do not exists:
http://localhost:1337/admin/plugins/content-manager/collectionType/application::article.article/123
And you will get a notice, but no redirects: spinner will be visible forever.

![2020-09-01_12-24-29](https://user-images.githubusercontent.com/32956521/91815515-317b7480-ec4e-11ea-8b91-ce16bc980f85.png)

**Expected behavior:** Probably redirect to Articles' list.

3. Bug with "Published at" field.
3.1. Use https://github.com/strapi/strapi-starter-gatsby-blog-v2
3.2. Go to any Article.
3.3. Click Save without changes
3.4. Get validation error
![2020-09-01_12-27-47](https://user-images.githubusercontent.com/32956521/91817037-9f27a080-ec4e-11ea-839e-3c4a45dce14d.png)

**Expected behavior:** No errors at "Published at" field, because it is correctly filled.

4. Clicking on "Sign in", when you have no administrators yet at Database will do nothing (redirect back to registration), so you just can't understand, have you ever registered at this site or not.
![2020-09-01_14-04-08](https://user-images.githubusercontent.com/32956521/91830426-334c3480-ec5c-11ea-93f8-0a8f64b24807.png)

**Expected behavior:** No "Sign in" link, when you have no administrators yet OR alert with the notice about it by clicking on the link.

5. Click !== Hover effect, which is not comfortable.

![2020-09-04_15-48-43](https://user-images.githubusercontent.com/32956521/92231568-5e39c100-eec6-11ea-8bd5-60577b899903.png)

**Expected behavior:** Hover only at icon OR click available on the whole area.

6. Buttons have strange content alignment by vertical.

![2020-09-04_15-53-19](https://user-images.githubusercontent.com/32956521/92231845-e5873480-eec6-11ea-9c00-4bc907f019d8.png)

**Expected behavior:** If you remove bottom padding and set line height (this may be not correct, it only for tests), then you'll  see, that content of buttons is vertically centered.

7. Click at rows works like "Edit" at any place, but not in:
* Roles & Permissions
* Providers
* Email Templates

![2020-09-04_15-56-25](https://user-images.githubusercontent.com/32956521/92232151-78c06a00-eec7-11ea-80a8-e808102aec58.png)

**Expected behavior:** Click at row should open "Edit" anywhere OR (if there are any problems) you need remove "hover" effect for rows.

8. Probably incorrect alert text

![2020-09-04_17-19-05](https://user-images.githubusercontent.com/32956521/92238488-d0b09e00-eed2-11ea-9539-58fe966cb018.png)

**System**
- Node.js version: v12.14.0
- NPM version: 6.14.7
- Strapi version: 3.1.1
- Database: Local
- Operating system: Windows

**Comment by derrickmehaffy** [comment]
`Strapi version: 3.1.1` Can you please update to the latest release v3.1.4 as some of the bugs you mentioned should already be fixed.

**Comment by derrickmehaffy** [comment]
@soupette @HichamELBSI for issue 1, in this case would it be better to just set the target as `blank` and open the link in a new tab while in the admin?

For 2, we can just set a redirect back to the homepage while displaying the error

3 is fixed in v3.1.4

4 I'm not sure here, this seems like a very small thing you will only notice long enough to register a user.

**Comment by soupette** [comment]
> For 2, we can just set a redirect back to the homepage while displaying the er

I have implemented this behaviour in #7716 and I have also fixed the point 4.

**Comment by iksent** [comment]
Hello again, I have added new points 5 - 7 ;)

**Comment by elclanrs** [comment]
The alignment issues around buttons and icons are still present in v3.1.5. I posted similar screenshots in past here https://github.com/strapi/strapi/issues/5998

**Comment by soupette** [comment]
Hi @iksent and @elclanrs can you open separated issues so both community members and the core team can fix them more easily? 
Because for instance if I were to fix the point 4 of the first comment the PR will close this issue automatically.

Plus it will help us associate appropriate labels to each one of the reported bugs.


Thanks a lot.

**cc/** @derrickmehaffy

**Comment by iksent** [comment]
Hey, @soupette.
Honestly, I have no time to separate these issues, sorry.

**Comment by elclanrs** [comment]
@soupette the UI issues I'm seeing are the exact same as describe in https://github.com/strapi/strapi/issues/5998. Can that issue be reopened and tagged?
