### ISSUE TITLE
Datetime field converts to the other users time zone

### ISSUE THREAD

**Issue by MotaZor94** [strapi/strapi#8739]
## Bug report
**Datetime** field converts time to the users time zone
### Describe the bug

Date Time field converts time to the users time zone, I am in Prague and I created a Date Time field like this:

27, November 2020, 4:30PM.

The user in India opened Strapi and opened that content type and he sees:

27, November 2020, 21:00PM.

### Steps to reproduce the behavior

1. Go to 'Strapi'
2. Create a new custom type and add a Datetime field.
3. Choose a date and time for example: 27, November 2020, 4:30PM.
4. Open VPN or ask someone from another time zone to check the new content type you created
5. He will see a different time.
### Expected behavior

All the users should have the same time in their fields, for example, we run webinars and when the user creates a page with the date and time it should always show the same time. 

Expected behavior is that the time on the Frontend is equal to the time in the database (UTC).

### Screenshots

Here is a screenshot from Prague where you can see the Datetime to be: 27, November 2020, 11:30.
Right below it you can see a Webinar Time field that shows 17:00

<img width="1189" alt="Screenshot 2020-11-25 at 13 01 12" src="https://user-images.githubusercontent.com/45624002/100226535-3041a700-2f20-11eb-9867-0957c3d6b3bd.png">

Here is a screenshot from India( Hyderabad) where you can see the Datetime to be: 27, November 2020, 16:00.
 But the time field itself again shows 17:00

<img width="844" alt="Screenshot 2020-11-25 at 13 01 01" src="https://user-images.githubusercontent.com/45624002/100226526-2ae45c80-2f20-11eb-99eb-92cdb885ab8d.png">

So I created it to be at 11:30 and the other user sees 16:00, so his intuition is to immediately change it to 11:30 since the time is incorrect, what will cause an actual wrong time on the front end of the application.

### Version
**Strapi** version 3.0.0-beta.19.13

**Comment by aksdevac** [comment]
I think this is expected behaviour. datetime is actually saved as ISO string which will be based on UTC, & for display it will use browser's local timezone. in short its not dependant on particular zone.

**Comment by MotaZor94** [comment]
Ok, so how will the Marketer for example that doesn't know that a database is saving in UTC know this?

So let's say someone in London creates a task for one of the Marketers in India and the task is to create a new webinar page where the webinar time is 27th of November 2020 at 4:00 PM UK time.

 Does it mean that a person needs to calculate the time himself in order to create a task? That leads to a lot of wrong 
 calculations and errors which people are usually prone to.

**Comment by aksdevac** [comment]
@MotaZor94 front end can display it in any timezone, UTC date can be converted to any fixed/dynamic timezone, as per your requirement. you will need to store timezone field separately if it is fixed based on some params, & convert it in API or on front end. 
but if you are creating record from strapi admin it will create date using browser's local timezone & will save it in UTC.

**Comment by MotaZor94** [comment]
I'm not talking about Frontend here, but about the Admin panel displaying something that is not related to what is actually inside of the database.

**Comment by aksdevac** [comment]
Its common practice to display it in local timezone, so user can understand it easily, in custom admin panel also people display date in local timezone even if database save it in UTC or as a timestamp.

**Comment by MotaZor94** [comment]
> Its common practice to display it in local timezone, so user can understand it easily, in custom admin panel also people display date in local timezone even if database save it in UTC or as a timestamp.

Yes if you are creating custom cms for a small coffee shop. But for a tool that is shared all over the companies offices around the world, the people should at least know or see in which timezone their date picker is. Especially if they got briefed in a **.doc** file from someone in a different timezone.

**Comment by aksdevac** [comment]
Ok may be strapi can allow setting default timezone for calendar/date picker & displaying it cms. Don't know if there is a feature request for it.

**Comment by MotaZor94** [comment]
> Ok may be strapi can allow setting default timezone for calendar/date picker & displaying it cms. Don't know if there is a feature request for it.

Would be good, this way it just creates confusion if you work in teams that are around the globe.

**Comment by derrickmehaffy** [comment]
I'm going to set this as a feature request to allow the disabling of this, as it is very much intended and is the "norm" in projects like this where the backend only handles a specific time (typically UTC) and especially in storage while frontend facing that time is converted by the users time zone.

Even taking something like GitHub as an example, the timestamp messages you see for "1 minute ago" ect use a similar system. But I can understand where users may not want this, and it's not a straight forward process to disable it (hard coded in the admin).

I have no promises we will implement it, hence the feature request but just so everyone understands, the current action is how we intended it.

**Comment by derrickmehaffy** [comment]
Also see related forum thread: https://forum.strapi.io/t/change-displayed-value-of-edit-field/1310

**Comment by codfish** [comment]
@derrickmehaffy @aksdevac I agree with you in regards to the common practices of always storing dates in UTC and displaying in local time. However, I think there's issues with dates, not just a feature request. Please let me know if this is totally separate and I should create a new issue.

**Note**: I'm in NY, so it's currently UTC-05:00.

## Expected Behavior

I'll start by saying **the ultimate goal** and my expectation is that if I save a date time, date, or time in the CMS and refresh the page, I would expect it to show me exactly what I input, regardless of how the data is stored. Currently, that's not what's happening for me.

## Actual Behavior

- I have a book content type
- Books have a `release_date` field of type `date`
- Right now, it's approx 4:27pm (16:27) in NY and 9:27pm (21:27) in UTC

I select December 25, 2020 in the date field and submit. I check the network tab in dev console, and inspect the PUT request. It's being sent as `"release_date": "2020-12-24",`. Assuming the date field tries to adjust for UTC based on midnight local time, UTC would still be 2020-12-25 for me (at 5 am).

Then if I refresh, the date comes back from the API as `2020-12-24` which makes sense, even though I saved it as 2020-12-25 it was sent at `2020-12-24`. The problem is then on the next save it actually sends `2020-12-23`, and so on and so forth. So it's decrementing the date on the initial and every subsequent save of the entity.

So I'm not really sure what's happening, there seems to be some non-standard manipulation of these dates and it's definitely a bug.

**Aside**: The dates (and times) aren't appearing for me at all in the field after a refresh or if I leave the page and come back (safari and chrome).

Here's a screencast to show you the behavior I'm seeing: https://share.getcloudapp.com/rRu0O0w5

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy @aksdevac I agree with you in regards to the common practices of always storing dates in UTC and displaying in local time. However, I think there's issues with dates, not just a feature request. Please let me know if this is totally separate and I should create a new issue.
> 
> **Note**: I'm in NY, so it's currently UTC-05:00.
> 
> ## Expected Behavior
> 
> I'll start by saying **the ultimate goal** and my expectation is that if I save a date time, date, or time in the CMS and refresh the page, I would expect it to show me exactly what I input, regardless of how the data is stored. Currently, that's not what's happening for me.
> 
> ## Actual Behavior
> 
> - I have a book content type
> - Books have a `release_date` field of type `date`
> - Right now, it's approx 4:27pm (16:27) in NY and 9:27pm (21:27) in UTC
> 
> I select December 25, 2020 in the date field and submit. I check the network tab in dev console, and inspect the PUT request. It's being sent as `"release_date": "2020-12-24",`. Assuming the date field tries to adjust for UTC based on midnight local time, UTC would still be 2020-12-25 for me (at 5 am).
> 
> Then if I refresh, the date comes back from the API as `2020-12-24` which makes sense, even though I saved it as 2020-12-25 it was sent at `2020-12-24`. The problem is then on the next save it actually sends `2020-12-23`, and so on and so forth. So it's decrementing the date on the initial and every subsequent save of the entity.
> 
> So I'm not really sure what's happening, there seems to be some non-standard manipulation of these dates and it's definitely a bug.
> 
> **Aside**: The dates (and times) aren't appearing for me at all in the field after a refresh or if I leave the page and come back (safari and chrome).
> 
> Here's a screencast to show you the behavior I'm seeing: https://share.getcloudapp.com/rRu0O0w5

What your describing should not happen. Open a bug report please.

**Comment by aksdevac** [comment]
@codfish It should not happen date type is different than datetime, date type just saves it in fixed format as string, so it should save it as it is without any timezone conversions. Its definitely a bug.

**Comment by codfish** [comment]
@aksdevac @derrickmehaffy https://github.com/strapi/strapi/issues/8954

**Comment by derrickmehaffy** [comment]
> @codfish It should not happen date type is different than datetime, date type just saves it in fixed format as string, so it should save it as it is without any timezone conversions. Its definitely a bug.

Yup exactly, datetime should be the only conversion done.

Date and time should be static strings.

**Comment by msoler75** [comment]
I'm in the same problem making international events app, the timezones related to each event are altered and misunderstood by the different layers (admin, api). I would prefer that any conversion was done anywhere to allow doing timezone conversions by myself.

**Comment by derrickmehaffy** [comment]
currently fixed in v4, marking as closed

**Comment by bublinec** [comment]
Hey, has anyone found a workaround for this in strapi v3?

**Comment by 0speedy** [comment]
May I please ask why is this ticket closed when the feature request is still in "To Review" state? Can you provide a bit more details on how it's fixed in v4? I still experience the same issue on v4 as the Author. Thank you.

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
