### ISSUE TITLE
API access while unauthorized should return 401, but instead returns 403.

### ISSUE THREAD

**Issue by remygendron** [strapi/strapi#9512]
### Describe the bug

Calling Strapi's APIs without credentials on a protected route should return 401 (unauthorized).

Strapi currently returns 403. This should be the code used for a forbidden access once authorized, like accessing a content type for which you have no access rights.

### Steps to reproduce the behavior

This will fail:
await request(basePath).get(contentTypePath).expect(status.UNAUTHORIZED);

### Expected behavior

Test will pass.

- Node.js version: 14.15.5  LTS
- NPM version: 6.14.10
- Strapi version: 3.5.0
- Database: Postgres
- Operating system: Mac Big Sur

**Comment by derrickmehaffy** [comment]
Related file: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/policies/permissions.js

Marked as low as the report is correct but will add complexity to the permissions check, most likely won't be handled until we refactor the U&P plugin or if someone from the community submits a PR.

**Comment by derrickmehaffy** [comment]
I believe this should be fixed in v4 as we did a little bit of refactoring. If it's not feel free to open a new issue.

**Comment by QuarkAgency** [comment]
Issue still there.

**Sending (without any cookie/authorization)**
`GET api/users/me`

**Retrieving** 
`HTTP 403`

**Expected**
`HTTP 401`

It is problematic because I updated Strapi to use HttpOnly Cookie for authentication.
So I cannot differentiate a lack of permission or just a user with no JWT or not valid.

**Comment by frontBOI** [comment]
issue is still here, I really need Strapi to send me back 401 when no authorization has been provided, and 403 when the user is authenticated but not allowed.
